### PR TITLE
LocaleCanonicalizer refactor

### LINKED ISSUE #767: Split likely subtags from LocaleCanonicalizer into their own type LocaleExpander
In the review of #747, there was feedback that some users might only want to use likely subtags operations and not canonicalization and that we should provide a feature to make canonicalization optional to avoid having to package and load data that will not be used.

### PR DESCRIPTION
**Pull request by sffc**
Fixes #767

### CODE REVIEW

**Comment by sffc** [comment]
I'm going to merge this as-is and if there is feedback later I will address it.

**Comment by Manishearth** [comment]
Yeah I was going through this and it mostly seemed fine, but I'm not the person with opinions on this crate

**Comment by sffc** [comment]
@zbraniecki Feel free to leave post-merge feedback

**Comment by zbraniecki** [comment]
Looks good to me.
My request is that when you introduce a constructor called `try_new_unstable` to document what makes it `unstable`. Similarly for other constructors it would be helpful to have the constructors docs help the first-time user understand which constructor should be used.

My user story is - a new user, with no experience with ICU4X, tries to use `LocaleExpander`. They open docs and find themselves here: https://unicode-org.github.io/icu4x-docs/doc/icu_locid_transform/struct.LocaleExpander.html

Now, of course they can go and read extensive docs on `DataProvider` to understand what is `DataProvider`, `AnyProvider` and `BufferProvider`, but having to do that in order to even test the functionality is a friction point.

So having all such cases where we provide a number of constructors ditinguished by an esoteric type be helpful in saying "This is the default constructor. Use it for basic use cases." vs "Use this constructor if you want to optimize for lower data payload memory footprint by utilizing XProvider" would help people take a stab at ICU4X.

**Comment by sffc** [comment]
Acknowledged. Let's discuss in https://github.com/unicode-org/icu4x/issues/2348 and fix the docs for 1.0 final

**Pull request merged**
