### PR TITLE
Add `Date::new_from_iso(date_iso, X)` example for each calendar X

### PR DESCRIPTION
**Pull request by andrewpollack**
Adding a `Date::new_from_iso(date_iso, X)` example at the top level of each calendar.
* Skipped Japanese, leaving until future update when I understand examples for it better

---Below issue has been resolved. Thank you!---
Separately, I am running into issues with the Coptic calendar. Is there a missing permission on access to the type? To demonstrate, the following works:
```rust
use icu::calendar::{Date, DateTime, indian::Indian};

let date_iso = Date::new_iso_date_from_integers(1970, 1, 2).unwrap();
let date_indian = Date::new_from_iso(date_iso, Indian);
```

But the following does not work:
```rust
use icu::calendar::{Date, DateTime, coptic::Coptic};

let date_iso = Date::new_iso_date_from_integers(1970, 1, 2).unwrap();
let date_coptic = Date::new_from_iso(date_iso, Coptic);
```

With the error:
```
error[E0423]: expected value, found struct `Coptic`
let datetime_coptic = DateTime::new_from_iso(datetime_iso, Coptic);
                                                           ^^^^^^ constructor is not visible here due to private fields
```

### CODE REVIEW

**Comment by Manishearth** [comment]
For Coptic you have to call Coptic::new() for now, it's marked as `non_exhaustive` so it can't be constructed the usual way.

**Comment by andrewpollack** [comment]
Thanks for the followup @Manishearth !

I went ahead and added the Coptic examples, along with the Buddhist examples. This PR is now in a stable state to review when ready

**Comment by Manishearth** [comment]
Also i just realized Coptic should _not_ be `non_exhaustive`, that's a bug. I removed that bit in my other PR.

The thing with Japanese is that it has era data that changes occasionally, so we need to load it. Typically the thing to do in tests is to construct it with a `let provider = icu_testdata::get_provider();`.

**Comment by andrewpollack** [comment]
Adjusted the Coptic example with your changes, thanks @Manishearth ! 

Separately, I'm still running into issues getting the Japanese example working, so I'll work that into a separate PR/discussion. More specifically, getting `icu_testdata` properly into the `Cargo.toml` and running in the doctest environment is running into compiler errors that I have not seen before:
```
thread 'rustc' panicked at 'assertion failed: !new_self_ty.has_escaping_bound_vars()', compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:1688:9
...
query stack during panic:
#0 [typeck] type-checking `main::_doctest_main_src_japanese_rs_7_0`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: internal compiler error: trimmed_def_paths constructed
```

**Comment by andrewpollack** [comment]
Adjusted the Coptic example with your changes, thanks @Manishearth ! 

Separately, I'm still running into issues getting the Japanese example working, so I'll work that into a separate PR/discussion. More specifically, getting `icu_testdata` properly into the `Cargo.toml` and running in the doctest environment is running into compiler errors that I have not seen before:
```
thread 'rustc' panicked at 'assertion failed: !new_self_ty.has_escaping_bound_vars()', compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:1688:9
...
query stack during panic:
#0 [typeck] type-checking `main::_doctest_main_src_japanese_rs_7_0`
#1 [typeck_item_bodies] type-checking all item bodies
#2 [analysis] running analysis passes on this crate
end of query stack
error: internal compiler error: trimmed_def_paths constructed
```

**Comment by Manishearth** [comment]
Ah, hmm, we've been getting that error a couple times now, it's https://github.com/rust-lang/rust/issues/96223

Make sure that you're importing icu_provider with the `"serde"` feature as a dev-dependency, that ICE is confusing but it essentially points to a missing trait impl, _usually_ in our case a Deserialize one,

**Pull request merged**
