### PR TITLE
Move icu_uniset into collections component as codepointinvlist module

### PR DESCRIPTION
**Pull request by echeran**
Part 2/3 of https://github.com/unicode-org/icu4x/issues/1856

- Moving util crate `icu_uniset` into component crate `icu_collections` as module (re)named as `codepointtrieinvlist`

### CODE REVIEW

**Review by Manishearth — DISMISSED** [review]
CI is still broken (and there are conflicts)

**Review by Manishearth — APPROVED** [review]

**Review by Manishearth — APPROVED** [review]

**Comment by echeran** [comment]
> CI is still broken (and there are conflicts)

Fyi @QnnOkabayashi 

@Manishearth Yep.  There were some benchmarks and examples that needing more explicit configuration.  When they were under their own respective crates, they would still get auto-detected because they were in the `benches` and `examples` folder at the root of the create, which is the default location that Cargo checks.  The benchmark programs used by performance benchmarks and the example programs used by the memory benchmarks look for them.

Do you have an opinion on the current organization of code?  Should all the `benches` code be put together in the same folder at the root of the `icu_collections` crate, or should they be separate and alongside their respective data structure's module within the crate?

**Comment by Manishearth** [comment]
@echeran Rust strongly prefers benches at crate root.

For all intents and purposes this should just be a normal Rust crate with a couple datastructures in it.

**Review by sffc — COMMENTED** [review]
lgtm except that we should probably move the benches to the top level at some point

**Comment by echeran** [comment]
> lgtm except that we should probably move the benches to the top level at some point

Agreed. We have https://github.com/unicode-org/icu4x/issues/2342 to track.

**Pull request merged**
