### PR TITLE
Impl Bake for BTreeMap

### PR DESCRIPTION
**Pull request by adamchalmers**
Part of #4266

### CODE REVIEW

**Comment by sffc** [comment]
Is there a more efficient way to construct this than `From<&[(K, V)]>`?

**Comment by adamchalmers** [comment]
The implementation could use this instead:


```rust
    fn bake(&self, ctx: &CrateEnv) -> TokenStream {
        ctx.insert("alloc");
        let data = self.iter().map(|(k, v)| {
            let k = k.bake(ctx);
            let v = v.bake(ctx);
            quote!((#k, #v))
        });
        quote! {
            {
                let mut m = alloc::collections::BTreeMap::new();
                for (k, v) in [#(#data),*] {
                    m.insert(k, v);
                }
                m
            }
        }
    }
```

but I suspect that's actually less efficient.

**Review by sffc — APPROVED** [review]
Yeah, in theory there should be a way to get an O(N) construction of BTreeMap if we know that the elements are sorted and how many elements there are, but `From` is likely the most efficient construction mechanism that is currently stable, and we can improve it later if Rust gives us such an API in the future.

**Review by Manishearth — APPROVED** [review]
Ideally this PR would also contain a changelog entry

**Pull request merged**
