### PR TITLE
Add missing Serde/Yoke impls to ZeroVec crate

### PR DESCRIPTION
**Pull request by sffc**
DOES NOT BUILD!  ZeroVec and VarZeroVec behave, but not ZeroMap.

@Manishearth, can you clone this and take a look?

### CODE REVIEW

**Comment by sffc** [comment]
There are two errors as far as I can tell:

1. `#[derive(yoke::Yokeable)]` does not work when the struct contains a `ZeroMap[Borrowed]`
2. `#[derive(serde::Deserialize)]` does not work when the struct contains a `ZeroMap[Borrowed]`

I started fixing (2) by splitting `'a` and `'de` in the serde::Deserialize impl for `ZeroMap[Borrowed]`, which is how we fixed this problem for VarZeroVec.  This made the serde derive happy, but that impl does not build now with the split lifetimes.

**Comment by Manishearth** [comment]
Oh, this is the same kind of issue I fixed for Elango in CPT, looks like I made the same mistake in the ZeroVec code 😅 

Will take a look!

**Comment by Manishearth** [comment]
Ah, it's different: it's a variance issue which means that `ZeroMap<'de>` doesn't cast to `ZeroMap<'a>` automatically and instead we have to be very careful about which lifetimes we use whilst deserializing

**Comment by Manishearth** [comment]
Fixed!

**Review by Manishearth — APPROVED** [review]

**Comment by sffc** [comment]
I also approve @Manishearth's changes.  Merging.

**Pull request merged**
