### PR TITLE
Create directory for minutes and add 2024-03-14

### PR DESCRIPTION
**Pull request by sffc**
We can use this directory to record official minutes primarily from TC meetings.

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by robertbastian** [comment]
I think Google docs is a far superior medium for taking minutes, as it's collaborative.

**Comment by Manishearth** [comment]
@robertbastian we need to eventually publish minutes for TC meetings; this is where we plan to do that.

we should not have our set-in-stone minutes be a collaborative document

**Comment by robertbastian** [comment]
Why not?

**Comment by Manishearth** [comment]
@robertbastian to be clear, this is not for _taking_ minutes, this is for _publishing_ final, approved minutes.


We can take minutes in whatever format we want. Docs -> markdown is somewhat tricky but hopefully TC minutes are not too full of formatting. And Hackmd is decently collaborative (it even has comments!)

**Pull request merged**
