### PR TITLE
4 features jobs

### PR DESCRIPTION
**Pull request by robertbastian**

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
not super happy about it but sure

**Comment by Manishearth** [comment]
We should also investigate the features being tested and check if we're doing too much.

I know at one point we had the idea of making most crates do "all + none + every combination of two".

**Comment by robertbastian** [comment]
Doesn't work

**Comment by Manishearth** [comment]
Oh yeah experimental should probably get limited to at most two features at once, that's likely the source of this shift.


And we should look into what datetime needs.

We can also update CAF to precompute all tasks so it can chunk equally rather than by package as it does now.

But the fact that chunking isn't working is an indication that this is an issue with specific crates and we should first try and fix that.

**Pull request closed without merging**
