### PR TITLE
Rename Yoke::project functions to ::map_project

### PR DESCRIPTION
**Pull request by yzhang1994**
Fixes https://github.com/unicode-org/icu4x/issues/1486

### CODE REVIEW

**Comment by sffc** [comment]
Thank you!

It looks like the "Doc" CI job found a few more instances that need to be updated:

https://github.com/unicode-org/icu4x/runs/6619225808?check_suite_focus=true

Could you take another look and ensure that all places that need to be changed have been updated? Thanks!

**Review by sffc — COMMENTED** [review]
(setting review bit)

**Review by Manishearth — COMMENTED** [review]
seems good so far!

**Review by Manishearth — DISMISSED** [review]

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
Thanks!

**Pull request merged**
