### PR TITLE
Comparing t1ha, wyhash, xxhash-rust, and twox-hash

### PR DESCRIPTION
**Pull request by sffc**
@robertbastian @Manishearth

### CODE REVIEW

**Comment by sffc** [comment]
Sizes:

```
-rwxr-xr-x  2 sffc primarygroup 2047248 Sep 12 13:48 t1ha*
-rwxr-xr-x  2 sffc primarygroup 2033016 Sep 12 13:48 twox_hash*
-rwxr-xr-x  2 sffc primarygroup 2033024 Sep 12 13:48 twox_hash_32*
-rwxr-xr-x  2 sffc primarygroup 2033232 Sep 12 13:48 wyhash*
-rwxr-xr-x  2 sffc primarygroup 2032928 Sep 12 13:48 xxhash_rust*
-rwxr-xr-x  2 sffc primarygroup 2032280 Sep 12 13:48 xxhash_rust_32*
```

Speeds and Results:

```
$ time ../../target/release-opt-size/t1ha
unique hashes: 488442 / 488442 (32-bit: 488413)

real	0m0.222s
user	0m0.191s
sys	0m0.035s

$ time ../../target/release-opt-size/twox_hash
unique hashes: 488442 / 488442 (32-bit: 488415)

real	0m0.195s
user	0m0.182s
sys	0m0.014s

$ time ../../target/release-opt-size/twox_hash_32 
unique hashes: 488427 / 488442 (32-bit: 488427)

real	0m0.246s
user	0m0.223s
sys	0m0.011s

$ time ../../target/release-opt-size/wyhash 
unique hashes: 488442 / 488442 (32-bit: 488406)

real	0m0.158s
user	0m0.138s
sys	0m0.024s

$ time ../../target/release-opt-size/xxhash_rust
unique hashes: 488442 / 488442 (32-bit: 488415)

real	0m0.183s
user	0m0.172s
sys	0m0.014s

$ time ../../target/release-opt-size/xxhash_rust_32
unique hashes: 488427 / 488442 (32-bit: 488427)

real	0m0.165s
user	0m0.152s
sys	0m0.017s

```

**Comment by sffc** [comment]
Added xxh3:

```
$ time ../../target/release-opt-size/xxhash_rust_xxh3 
unique hashes: 488442 / 488442 (32-bit: 488415)

real	0m0.220s
user	0m0.191s
sys	0m0.033s

$ ll ../../target/release-opt-size/xxhash_rust_xxh3 
-rwxr-xr-x 2 sffc primarygroup 2045696 Sep 12 14:02 ../../target/release-opt-size/xxhash_rust_xxh3*
```

**Comment by sffc** [comment]
It looks like xxhash is likely the way to go. It is smaller than t1ha and wyhash, and slightly slower but basically the same speed as wyhash. The 32-bit version also produces the fewest 32-bit collisions.

Next question: there are two crates implementing this, xxhash-rust and twox-hash. It seems xxhash-rust is smaller and faster, but twox-hash is more widely used.

**Comment by robertbastian** [comment]
I think there are more dimensions to consider than code size and speed. We probably also want to consider quality (i.e. active maintenance) and popularity (how likely is the crate already vendored by clients).

For runtime use, speed and code size are most important. For a non-optional dependency of datagen, I think it's better to use a well-maintained popular crate, even if it's slow or requires std.

**Comment by sffc** [comment]
SipHash:

```
$ ll ../../target/release-opt-size/siphash
-rwxr-xr-x 2 sffc primarygroup 2033240 Sep 14 13:55 ../../target/release-opt-size/siphash*

$ time ../../target/release-opt-size/siphash
unique hashes: 488442 / 488442 (32-bit: 488420)

real	0m0.157s
user	0m0.152s
sys	0m0.008s
```

**Comment by Manishearth** [comment]
(we should _not_ use SipHash, it's deprecated and nobody on the libs team wants people to use it for stuff like this. Since it is deprecated it's really not something that I would consider "maintained", even if it is in the stdlib.)

**Comment by robertbastian** [comment]
> and nobody on the libs team wants people to use it for stuff like this

what are they gonna do? It's stable and we can use it

**Comment by sffc** [comment]
crc32fast:

```
$ ll ../../target/release-opt-size/crc32fast 
-rwxr-xr-x 2 sffc primarygroup 2059400 Sep 15 10:38 ../../target/release-opt-size/crc32fast*

$ time ../../target/release-opt-size/crc32fast 
unique hashes: 488413 / 488442 (32-bit: 488413)

real	0m0.158s
user	0m0.144s
sys	0m0.017s
```

**Comment by Manishearth** [comment]
> what are they gonna do? It's stable and we can use it

not accept any PRs to fix bugs or improve anything. deprecated code is effectively unmaintained.

**Comment by robertbastian** [comment]
It is still maintained through `std::collections::hash_map::DefaultHasher` though...

**Comment by Manishearth** [comment]
Which they are free to change any time, and they may only care about bugs that actually affect their hash map.

I think we need a _really_ good reason to choose to use already-deprecated APIs. It's extremely unidiomatic.

**Comment by zbraniecki** [comment]
I'm convinced by Manish position, I am shifting away from my previous position in result. We should not use SipHash.

**Comment by robertbastian** [comment]
Alright

**Comment by sffc** [comment]
Code is archived as https://github.com/sffc/omnicu/tree/archive/hash-cmp

**Pull request closed without merging**
