### PR TITLE
Update gn to proc-macro2 1.0.78

### PR DESCRIPTION
**Pull request by sffc**
Might fix the CI failure

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by sffc** [comment]
This makes CI green so I will force-merge.

**Comment by Manishearth** [comment]
r+

**Comment by robertbastian** [comment]
issue: our tutorials should build with latest dependencies, otherwise they become hard to reproduce

**Comment by sffc** [comment]
Well the problem with GN specifically is that cargo-gnaw needs pinned versions with hand written annotations in Cargo.toml which can't always be auto generated. Previously we had the lockfile in tree but we replaced that with the makefile that manually pins the versions.

**Pull request merged**
