### PR TITLE
Move licence-file back into individual Cargo.toml files

### PR DESCRIPTION
**Pull request by sffc**
See comment in https://github.com/unicode-org/icu4x/issues/4065

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by robertbastian** [comment]
I think the better solution for this would be to remove the individual license files in all the directories. IIUC the packaging step tries to copy the root license and only fails because there's already a (unreferenced) license in the directory.

**Comment by sffc** [comment]
We started copying LICENSE files to each crate due to https://github.com/unicode-org/icu4x/issues/771

**Comment by robertbastian** [comment]
I believe with workspace inheritance this actually happens now. #771 was before we were using that feature. Note the error message:


warning: license-file `../../LICENSE` appears to be a path outside of the package, but there is already a file named `LICENSE` in the root of the package. **The archived crate will contain the copy in the root of the package.**

**Comment by sffc** [comment]
It seems like a worthwhile but lower-priority (P3/P4) cleanup given that the LICENSE copying machinery from #771 is in place and working.

**Pull request merged**
