### PR TITLE
Stripping collation variant in fallback

### PR DESCRIPTION
**Pull request by robertbastian**
I *think* this is what we want to do (and tried to do in the collator itself before).

#3253

### CODE REVIEW

**Review by sffc — COMMENTED** [review]
It should already be done in the step function at

```
        // 1. Remove the extension fallback keyword
```

**Review by sffc — CHANGES_REQUESTED** [review]
We should write a test first, and just make sure the desired behavior matches the test. I'd rather not poke around with this type of change if we don't know whether or not it really fixes the problem in an observable way.

**Comment by sffc** [comment]
I think I don't agree with that. First, the default collation is subject to change, as happened with `sv` recently. The fallback should be data-driven. I definitely oppose a solution that involves hard-coding locales and default collations. Second, if you special case this in the normalize step, then you risk complicating the algorithm and performance of everyone not loading collation data.

**Review by sffc — COMMENTED** [review]
^

**Comment by sffc** [comment]
In general, it should always be the case that the default value of an extension keyword is represented in the data provider by the absence of that extension keyword. It's not just collation; it's also other subtags that show up in the data provider, like `-u-nu`:

- `zh-u-co-pinyin` => `zh`
- `de-u-co-standard` => `de`
- `it-u-nu-latn` => `it`
- `ar-EG-u-nu-arab` => `ar-EG`

So the question we should be asking ourselves is whether and how to detect and handle the general case in `normalize` instead of `step`.

**Comment by robertbastian** [comment]
> The fallback should be data-driven

Agreed. `icu_locid_transform` doesn't currently normalize extensions, but says it's planned: https://github.com/unicode-org/icu4x/blob/main/components/locid_transform/src/canonicalizer.rs#L269

**Comment by robertbastian** [comment]
Filed #3483

**Pull request closed without merging**
