### PR TITLE
Use correct glob pattern for branch PR CI (`*` excludes `/` characters)

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Comment by Manishearth** [comment]
autosubmit=on

**Comment by Manishearth** [comment]
Also potentially we should enable branch CI for `release/**`

**Comment by sffc** [comment]
> Also potentially we should enable branch CI for `release/**`

Yeah I think we should do this

**Comment by sffc** [comment]
Actually we don't need the filter at all; if you don't have it, it runs on all PRs, which is what we want I think. https://github.com/unicode-org/icu4x/pull/4618

**Pull request closed without merging**
