### PR TITLE
Fix sv_reformed warning

### LINKED ISSUE #2764: ICU 72 doesn't include sv_reformed_meta.toml
Running datagen against the new ICU 72 zip file prints out:

```
WARN  [icu_provider::error] ICU4X data error: Zip: specified file not found in archive
WARN  [icu_provider::error] ICU4X data error: Zip: collation/implicithan/sv_reformed_meta.toml
```

What does it mean? Does something need to be fixed?

CC @echeran @markusicu @hsivonen

### PR DESCRIPTION
**Pull request by robertbastian**
Fixes #2764 
Also ref #2183

### CODE REVIEW

**Review by sffc — DISMISSED** [review]
A bit larger of a change than strictly necessary, but good

**Comment by robertbastian** [comment]
I think this will make it easier for someone who is less familiar with the code to clean it up in the future.

**Review by sffc — APPROVED** [review]
I actually noticed that in my initial review but didn't flag it because I assumed Clippy would catch it if it needed to be fixed

**Comment by robertbastian** [comment]
This one as well :D?

**Review by sffc — APPROVED** [review]

**Pull request merged**
