### PR TITLE
Add NeoSkeleton default length

### PR DESCRIPTION
**Pull request by sffc**
Any objections?

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Review by robertbastian — COMMENTED** [review]
I don't see how `Long` is more qualified as a default than `Medium`. Why do we need a default? Does this simplify the usage of the API?

**Comment by sffc** [comment]
The length is not being used for times and time zones, so this makes call sites a little easier to read. https://github.com/unicode-org/icu4x/pull/5246

However, I'm now thinking I should just change the constructors to take an options bag where the length is one of the fields, like we do literally everywhere else, giving us more flexibility in the long run.

**Comment by sffc** [comment]
> However, I'm now thinking I should just change the constructors to take an options bag where the length is one of the fields, like we do literally everywhere else, giving us more flexibility in the long run.

Even if I make this change, I still need a default length, because I can't load data without the length. Alternatively, I can make the constructor return an error if the length is not set in the API.

**Comment by sffc** [comment]
Okay, I tried adding a type parameter for the options bag. The length ends up being used fairly deep in the stack, including during the formatting calls to select the correct pattern. (This avoids a `map_project` in the constructor.) So, internally, I would likely need to still store an actual `SkeletonLength` but make it an `Option<SkeletonLength>` and GIGO if I need to retrieve it.

**Comment by sffc** [comment]
https://github.com/unicode-org/icu4x/pull/5248

If #5248 is approved and merged, I will close this PR.

**Comment by sffc** [comment]
Made obsolete by https://github.com/unicode-org/icu4x/pull/5248

**Pull request closed without merging**
