### PR TITLE
#3793 follow-up

### PR DESCRIPTION
**Pull request by robertbastian**
* Prefixing `UmmAlQura` to `IslamicUmmAlQura`
* Sorting all calendar lists
* Tweaking calendar display names (`IslamicCivil` -> `Islamic (civil)`, `UmmAlQura` -> `Islamic (Umm al-Qura)`, etc.)
* Using hierarchical data keys for Islamic calendars

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
We're planning on merging datetime data but this is fine for now

**Comment by robertbastian** [comment]
> We're planning on merging datetime data but this is fine for now

What do you mean? I didn't see an open PR

**Comment by sffc** [comment]
> > We're planning on merging datetime data but this is fine for now
> 
> What do you mean? I didn't see an open PR

https://github.com/unicode-org/icu4x/issues/3854

**Comment by sffc** [comment]
Renaming the struct `UmmAlQura` to `IslamicUmmAlQura` seems fine. The data key strings want to be consolidated down to a single `islamic` key that all four calendars use.

**Comment by robertbastian** [comment]
Ah that kind of merging. As long as there's not code written I don't think this PR is an issue?

**Review by sffc — APPROVED** [review]
Yeah this is mergeable; was just pointing out that there's still more to be done in this area which will make a portion of this PR go away

**Pull request merged**
