### PR TITLE
Always implement AnyMarker provider for datagen transformers

### PR DESCRIPTION
**Pull request by sffc**

### CODE REVIEW

**Comment by sffc** [comment]
@Manishearth Any idea why this change would cause a linker error on Windows but not on Ubuntu/macOS?

**Comment by Manishearth** [comment]
It's a different linker. Smells like a linker/compiler bug, we don't do any fancy stuff here. A pure rust binary should not have any trouble here and I'd file a bug upstream.

**Comment by Manishearth** [comment]
Oh, though it might be a linker OOM. That does happen for larger projects and it seems like that particular error is not unlikely in that case.

**Comment by sffc** [comment]
The error message is:

```
[cargo-make] INFO - Running Task: testdata-hello-world-json
[cargo-make] INFO - Execute Command: "cargo" "run" "--bin=icu4x-datagen" "--features=experimental,bin" "--" "--hello-world-key" "--all-locales" "--out=provider/fs/tests/data/json" "--overwrite"
   Compiling icu_normalizer v0.6.0 (D:\a\icu4x\icu4x\components\normalizer)
   Compiling icu_collator v0.6.0 (D:\a\icu4x\icu4x\components\collator)
   Compiling icu_datagen v0.6.0 (D:\a\icu4x\icu4x\provider\datagen)
error: linking with `link.exe` failed: exit code: 1318
  |
  = note: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" 
...
  = note: LINK : fatal error LNK1318: Unexpected PDB error; FILE_SYSTEM (3) 'D:\a\icu4x\icu4x\target\debug\deps\icu4x_datagen.pdb'
```

**Comment by sffc** [comment]
Error LNK1318 is explained here:

https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1318?view=msvc-170

> The linker encountered an unexpected error when opening, reading, or writing to a PDB file.
>
> This error message is produced for uncommon issues in PDB files. The cause and details represent the information available to the linker when the failure occurred. This may not be very useful, as common errors when dealing with PDB files have separate, more informative error messages.
>
> Because the source of the error is uncommon, there is only generic advice available for resolving this issue:
>
> - Perform a clean operation in your build directories, and then do a full build of your solution.
> - Reboot your computer, or check for stray or unresponsive mspdbsrv.exe processes and kill them in TaskManager.
> - Turn off antivirus checks in your project directories.
> - Use the [/Zf](https://docs.microsoft.com/en-us/cpp/build/reference/zf?view=msvc-170) compiler option if using [/MP](https://docs.microsoft.com/en-us/cpp/build/reference/mp-build-with-multiple-processes?view=msvc-170) with MSBuild or another parallel build process.
> - Try building by using the 64-bit hosted toolset.
> - Serialize linking to mitigate parallel link issues if needed. This error can be caused if mspdbsrv.exe is launched by one instance of link, and is shut down before another instance of link is done using it. The downside to this fix is that your project builds may take considerably longer to complete.

**Comment by sffc** [comment]
I recall @robertbastian running into a problem recently involving the Windows VM running out of disk space. Maybe we need to increase the amount of disk space on the VM? I'll see if I can figure out how to do that in GHA...

**Comment by sffc** [comment]
I can't find an easy way to increase the disk size allocation on Windows GHA bots. I found [this](https://github.com/easimon/maximize-build-space), but it only works on Linux. We could try using a different service to run the Windows builds, but I don't know whether disk space is actually the problem or not.

**Comment by Manishearth** [comment]
> Error LNK1318 is explained here:
> 
> https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1318?view=msvc-170

Right, that's what the error is trying to detect, but it can also get erroneously triggered on linker ooms

**Comment by sffc** [comment]
Got it to work by pulling the compilation of `icu4x-datagen` and `icu4x-testdata-datagen` into their own CI jobs. So now we build all the tests and benches in the `test` job, and the datagen binaries in the `testdata` job. I'm keeping both parts running on the linux/mac/windows matrix.

**Comment by sffc** [comment]
CC @gnrunge @echeran for visibility on this. This issue is likely to come up again as the project continues to grow with new features. We may want to prepare for that world by choosing an alternative CI solution for the highest-resource jobs.

**Review by robertbastian — APPROVED** [review]

**Review by Manishearth — APPROVED** [review]

**Pull request merged**
