### PR TITLE
Make datagen faster by caching more things

### PR DESCRIPTION
**Pull request by sffc**
Toward #3620

### CODE REVIEW

**Review by robertbastian — APPROVED** [review]

**Comment by sffc** [comment]
Good stuff: the full-datagen job finishes in 10m 0s, of which 7m 47s is building datagen in release mode. Spot-checking, the slowest keys seem to be timezones and segmenter again, as they had been before. Displaynames finishes in less than 2 seconds.

**Comment by robertbastian** [comment]
I failed as a linter

**Review by robertbastian — COMMENTED** [review]
Please change the displaynames locale set to `Recommended` again

**Comment by sffc** [comment]
From running icu4x-datagen in release mode with rayon disabled and comparing timestamps, the slowest keys are, in order of slowness (slowest on top):

Key | Time (seconds)
---|---
segmenter/word@1	 | 	0.348
segmenter/dictionary/w_auto@1	 | 	0.343
segmenter/line@1	 | 	0.303
segmenter/dictionary/wl_ext@1	 | 	0.296
segmenter/sentence@1	 | 	0.255
datetime/japanext/datesymbols@1	 | 	0.247
datetime/japanese/datesymbols@1	 | 	0.212
list/unit@1	 | 	0.206
time_zone/specific_long@1	 | 	0.2
datetime/indian/datesymbols@1	 | 	0.198
segmenter/grapheme@1	 | 	0.182
datetime/gregory/datesymbols@1	 | 	0.176
props/bidiauxiliaryprops@1	 | 	0.172
decimal/symbols@1	 | 	0.172
datetime/coptic/datesymbols@1	 | 	0.163
datetime/buddhist/datesymbols@1	 | 	0.158
datetime/ethiopic/datesymbols@1	 | 	0.152
time_zone/generic_short@1	 | 	0.15
time_zone/generic_long@1	 | 	0.136
collator/data@1	 | 	0.122
datetime/japanese/datelengths@1	 | 	0.122
time_zone/exemplar_cities@1	 | 	0.122
props/exemplarchars/main@1	 | 	0.12
list/and@1	 | 	0.116
props/exemplarchars/index@1	 | 	0.109
list/or@1	 | 	0.108
props/exemplarchars/punctuation@1	 | 	0.107
props/exemplarchars/numbers@1	 | 	0.107
time_zone/specific_short@1	 | 	0.105
datetime/gregory/datelengths@1	 | 	0.102
datetime/timelengths@1	 | 	0.099
props/exemplarchars/auxiliary@1	 | 	0.099
datetime/timesymbols@1	 | 	0.098
datetime/buddhist/datelengths@1	 | 	0.088
datetime/japanext/datelengths@1	 | 	0.087
datetime/coptic/datelengths@1	 | 	0.084
datetime/ethiopic/datelengths@1	 | 	0.083
time_zone/formats@1	 | 	0.082
datetime/indian/datelengths@1	 | 	0.073

**Review by robertbastian — APPROVED** [review]

**Pull request merged**
