### PR TITLE
Add WordBreakIterator::iter_with_word_type

### LINKED ISSUE #3277: RuleBreakIterator status
@eggrobin discovered that accessing the rule break status during segmentation is rather tricky because [`RuleBreakIterator::rule_status()`](https://unicode-org.github.io/icu4x/docs/icu/segmenter/struct.RuleBreakIterator.html#method.rule_status) is a method on the iterator (which means it cannot be accessed within iterator adapters since you'd need to hold on to a borrow of the iterator whilst using mutable methods.

This is unfortunate; if you care about rule status it seems useful to be able to call things like `.filter()`. It's not the end of the world, manual iteration with a `while let Some(brk) = iter.nex()` will work fine, but it's not great.

A useful API would be to have a second `RuleBreakWithStatusIterator`, ideally obtainable via `RuleBreakIterator::with_status()` (this way we don't need a duplicated suite of iterator methods).

Filing for future consideration, I don't think we have to have this for 1.0, though it might be nice.

cc @sffc @aethanyc @makotokato

### PR DESCRIPTION
**Pull request by eggrobin**
Fix #3277.

Use it to make the example slightly more hinged.

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
I'm in favor of this but I'm not sure if @sffc wants this in this release.

**Comment by sffc** [comment]
We could also in the future add a `.segments()` function that returns `Iterator<Item = &str>` or similar.

I'm not sure if `with_status` / `with_type` is the best name. Maybe `iter_with_word_type`.

I lean toward holding off on these segmenter iterator adapters until after 1.2 so that we can have more time to bikeshed them.

**Review by sffc — DISMISSED** [review]
Setting review bit so it gets out of my queue (still need to discuss in an icu4x call)

**Comment by sffc** [comment]
Discussion: make the function named `iter_with_word_type`, and also add a getter to the WordType enum for `is_word_like`. None of this needs to be in FFI.

LGTM: @Manishearth @sffc @echeran

**Comment by sffc** [comment]
Ping @eggrobin, can you rename the function as suggested above?

**Comment by eggrobin** [comment]
Renamed and added `is_word_like` to the enumeration type.

**Review by Manishearth — DISMISSED** [review]

**Review by Manishearth — APPROVED** [review]

**Comment by sffc** [comment]
Changelog?

**Pull request merged**
