### PR TITLE
Switch DTF field symbols to use macros.

### PR DESCRIPTION
**Pull request by zbraniecki**
This PR unifies how we generate traits for `Field` to minimize the manual repetition. This change has no impact on performance.

Additionally, to aid with normalization, I'm switching `Minute` to be a full field. This seems to have a minor impact on the `postcard` file.
My reasoning is that the cost is acceptable tradeoff for maintenance improvement, but I'm open to other conclusions from the reviewers.

### CODE REVIEW

**Review by gregtatum — APPROVED** [review]
The changes seem reasonable to me. I agree it's nice to have a bit more of a consistent experience with the fields. Generally I'm a bit hesitant of macro definitions because they can make understanding how to use the thing harder, but here I think it's a definite improvement.

**Comment by zbraniecki** [comment]
hmm, reverted Minute changes for now

**Comment by nordzilla** [comment]
> hmm, reverted Minute changes for now

Why? Just finished looking at this. It always bothered me a bit, stylistically, that Minute didn't match all of the others. 

Otherwise, these changes look good to me. The macro really cleans things up.

**Comment by zbraniecki** [comment]
> Why? Just finished looking at this. It always bothered me a bit, stylistically, that Minute didn't match all of the others.

Because it inflated postcard file and bincode files.

**Comment by nordzilla** [comment]
> > Why? Just finished looking at this. It always bothered me a bit, stylistically, that Minute didn't match all of the others.
> 
> Because it inflated postcard file and bincode files.

Fair enough. These changes look good to me.

**Review by nordzilla — APPROVED** [review]

**Pull request merged**
