### PR TITLE
Updating test data to ICU 71

### PR DESCRIPTION
**Pull request by robertbastian**

### CODE REVIEW

**Review by sffc — COMMENTED** [review]
How/why did the size decrease so much for casemap and implicithan?

**Comment by robertbastian** [comment]
No idea, I just took the current files from `icuexportdata`

**Comment by robertbastian** [comment]
I think those files were manually added before, so they might have been the fast tries or some other version

**Review by sffc — COMMENTED** [review]
Requesting review from @hsivonen; can you take a look at the changes to the collation data files?

**Review by hsivonen — APPROVED** [review]
> How/why did the size decrease so much for casemap and implicithan?

Previously, I had the unihan root in testdata instead of the implicithan root. The weight allocation in the jamo table is known to depend on implicithan vs. unihan, though I haven't investigated why exactly.

implicithan makes sense as the default to the extent we want to default to the smaller option even when it's less correct.

I gather that the implicithan vs. unihan decision was taken while I was away and, therefore, it would be inappropriate to rediscuss it in this PR.

**Comment by robertbastian** [comment]
This is actually a separate discussion from which default we want to use for datagen, we could generate test data with the non-default as well. That said I think implicit is also the right decision for test data.

**Review by hsivonen — APPROVED** [review]

**Comment by robertbastian** [comment]
I can't force merge :(

**Pull request merged**
