### PR TITLE
Making more tinystr operations `const`

### PR DESCRIPTION
**Pull request by robertbastian**
`cargo benchcmp` gives me empty output, does that mean there's no difference?

### CODE REVIEW

**Comment by Manishearth** [comment]
> `cargo benchcmp` gives me empty output, does that mean there's no difference?

When a function becomes `const` Rust does not necessarily always use the `const` version where possible

**Review by Manishearth — APPROVED** [review]

**Comment by robertbastian** [comment]
There are some changes around how arrays get initialized though, as working with slices is tricky in `const`.

**Comment by Manishearth** [comment]
Yeah, I saw. I'm not sure i'm completely happy about that, `copy_from_slice` tends to be easier to guarantee the perf of but it probably doesn't matter

**Comment by sffc** [comment]
TinyAsciiStr is very performance-sensitive. Please check `cargo bench` output both for this crate and for the locid crate, which heavily relies on the performance of this crate.

CC @zbraniecki

**Pull request merged**
