### PR TITLE
Make the normalizer work with new Unicode 16 normalization behaviors

### LINKED ISSUE #4859: Make the normalizer work with new Unicode 16 normalization behaviors
See topic 5.1 in https://www.unicode.org/L2/L2024/24009r-utc178-properties-recs.pdf

### PR DESCRIPTION
**Pull request by hsivonen**
Closes #4859

ICU4C PR coming up.

### CODE REVIEW

**Comment by hsivonen** [comment]
ICU4C PR: https://github.com/unicode-org/icu/pull/2994

**Comment by hsivonen** [comment]
This reverts https://github.com/unicode-org/icu4x/pull/4538 , which turned out to be a bad idea.

**Comment by hsivonen** [comment]
I've tested this with Unicode 16 data, but this PR doesn't include the new data.

**Comment by sffc** [comment]
- @hsivonen - PR #4860 adds compatibility with Unicode 16, but it potentially regresses performance on C forms (not NFD or NFKD) due to additional branches, but this hasn't been benchmarked. PR #4878 should not have any performance impact.
- @echeran - I think we should keep Unicode 16 changes together.
- @sffc - What types of characters hit the branch?
- @hsivonen - It impacts the performance of the pass-through operation for NFC.
- @sffc - It seems not super urgent to lang these since Unicode 16 isn't out yet, but we should do the work to test and benchmark them.
- @hsivonen - We would want a long string of CJ text and want that to go fast.

Conclusion: spend the time to benchmark these changes, in conjunction with #4967. Do this before 2.0 because it might involve a data struct change.

**Review by Manishearth — APPROVED** [review]
Yes, this seems like a minor optimization at best. Let's land this, we should have 16 support for 2.0

**Pull request merged**
