### PR TITLE
impl Hash for ZeroVec/ZeroSlice

### PR DESCRIPTION
**Pull request by sffc**
Good or no good?

Should all of the impls be using bytes?

### CODE REVIEW

**Comment by sffc** [comment]
Problem: In order to deduplicate the packed patterns, I want to put them in a hashset or btreeset. They have a ZeroVec inside. Instead of adding these impls, I have numerous workarounds:

- impl Hash on a datetime-specific type via the bytes
- Store a different type in the HashMap such as a `reference::Pattern` instead of a `runtime::Pattern` so that there is no ZeroVec involved
- Given that the set is small, use a Vec-based set with O(1) insertion time

Now that I think of it, a HashSet isn't great anyway because of stability issues; I would need to sort it anyway. So maybe I'll stick with a BTreeSet or the Vec-based approach.

**Comment by Manishearth** [comment]
I'm fine with these impls.

**Comment by Manishearth** [comment]
But we don't have to add them now.

**Comment by sffc** [comment]
I think we should maybe actually switch all of the impls (PartialEq, Eq, PartialOrd, Ord, Hash) to all use the byte impls. Right now they use the upgraded type impls.

**Pull request closed without merging**
