### PR TITLE
Regenerate collation test data

### PR DESCRIPTION
**Pull request by hsivonen**
(Edited.) This is an update from [ICU4C 71 branch CI.](https://dev.azure.com/ms/icu/_build/results?buildId=323174&view=artifacts&pathAsName=false&type=publishedArtifacts)

### CODE REVIEW

**Comment by hsivonen** [comment]
I have checked that both the full versions of the conformance tests and the disabled-in-repo zh, lt, fi, and sv tests pass with this data update if enabled.

**Comment by sffc** [comment]
@echeran Note that this PR also effectively updates the property testdata to Unicode 15.

**Comment by echeran** [comment]
> @echeran Note that this PR also effectively updates the property testdata to Unicode 15.

Good observation.  The only property that is being updated is `Canonical_Combining_Class`, which should be [collator-specific](https://unicode.org/reports/tr44/#Canonical_Combining_Class).  If we merge this PR as-is, then we have one property in v1.0 on Unicode v15.0, and the rest of the properties on v14.0.

On the one hand, the change does seem isolated, but on the other hand, we would have a version inconsistency among the properties in ICU4X v1.0 (because updating properties to Unicode v15.0 is slated for after the ICU4X v1.0 release).

I have no other reservations about this data update PR except the aforementioned version consistency / release timing.

Any thoughts?  @hsivonen -- is this a PR that can wait until after the imminent ICU4X v1.0 release (even if you're away and need someone else to click the merge button)?

**Comment by hsivonen** [comment]
When I made this PR, I thought that ICU4X 1.0 was supposed to ship with Unicode 15 support.

To the extent #2058 is blocked on the ICU4C patch and to the extent we want the collator and normalizer as non-experimental in 1.0, if the ICU4C patch lands on ICU4C trunk only, the full data export from ICU4C CI will be from ICU4C trunk, i.e. Unicode 15. This PR is about test data only either way. If we want Unicode 14-consistent _non-test_ data to be available for the normalizer and the collator, the ICU4C patch needs to be backported to ICU4C from before ICU4C trunk upgraded to Unicode 15.

In that sense, I think leaving this test data patch unmerged doesn't address what non-test data is available as a zip file for non-test use. And on the flip side, to the extent the test data is really just test data, it seems OK to update it in a less synchronized way and the main thing is that the deployment zip file is either all-Unicode 14 or all-Unicode 15.

**Comment by hsivonen** [comment]
Somehow I had managed to be off by three months in my understanding of when Unicode 15 is expected to be released and how it relates to ICU4X 1.0. I have force-pushed a much smaller changeset that syncs the collation and normalization relevant files from an actual (draft PR) CI run from the ICU4C 71 branch.

The non-comment change relates to my tweaks to the root generation using the `genuca` tool.

**Pull request merged**
