### PR TITLE
Add copyright check in CI

### LINKED ISSUE #155: Add CI copyright headers check
This task is split off from #84 to represent just the requirement of doing checks on copyright headers on source files.

We want every file to have headers indicating that indicates that the file is a part of ICU4X and references a link to the license.

Anything else I'm missing? @hsivonen

### PR DESCRIPTION
**Pull request by echeran**
Testing in personal fork using this [testing PR](https://github.com/echeran/icu4x/pull/18) that uses a testing branch in the personal fork. The testing branch layered on commits that added some extra debugging and some mock files (some which conform to license headers, some which do not). To see how it is working, you can look at [the output from an invocation](https://github.com/echeran/icu4x/runs/1361374951?check_suite_focus=true) in the testing PR.

Closes #155

### CODE REVIEW

**Review by sffc — COMMENTED** [review]
Thanks!

Per #334, there is desire to make these checks runnable when not on CI.  In #376, I moved some logic from build-test.yml into Makefile.toml.  Can we structure the copyright check to be in a side script that hopefully runs cross-platform?

Duckscript, a Rust-based cross-platform scripting language, might help: https://github.com/sagiegurari/duckscript

**Review by sffc — CHANGES_REQUESTED** [review]
(setting review bit)

**Comment by sffc** [comment]
#376 is in now, so once you update your branch, you will be able to add this to Makefile.toml.

**Review by sffc — APPROVED** [review]
Thank you!

Did you verify that `trigger_error` in Duckscript causes the command to exit with a nonzero error code, such that it bubbles up to GitHub Actions?

**Comment by echeran** [comment]
I verified at the command line that it gives a nonzero exit code.  I originally used `exit` but the duckscript process still exited with a successful 0 code, so I switched to `trigger_error`.

**Comment by echeran** [comment]
I should have mentioned that `trigger_error` exits the entire process because of the line at the top of the script to enable that behavior: `exit_on_error true`.

As an aside, it seems like Duckscript has mostly a prefix notation syntax. It's almost like S-exprs, just without outer parenthases.

**Pull request merged**
