### PR TITLE
Bump toolchain to 1.73, MSRV to 1.67

### PR DESCRIPTION
**Pull request by robertbastian**

### CODE REVIEW

**Comment by sffc** [comment]
As usual please state what we plan to use from 1.67

**Comment by robertbastian** [comment]
1.67 includes `<unsinged>::checked_ilog10` which this PR uses.

**Review by sffc — COMMENTED** [review]
Seems good but I'd like an explicit statement for what features in 1.67 we plan to use

**Review by sffc — APPROVED** [review]
I see the statement now. Thanks

**Comment by sffc** [comment]
To be clear, after this lands we can't do any more 1.3.x releases because that is on MSRV 1.66

**Comment by robertbastian** [comment]
Even 1.3.2 was a cherry-pick release because other changes had already happened.

**Comment by sffc** [comment]
> Even 1.3.2 was a cherry-pick release because other changes had already happened.

What? That shouldn't be the case. We should always release from main or a branch. I did not know this or else I would not have said to go forward with the 1.3.2 tag.

**Comment by robertbastian** [comment]
Well we released from a branch that had cherry-picks on it. We've since deleted the branch because we don't do maintenance branches in ICU4X, and the tag immutably points to the release commit.

**Pull request merged**
