### PR TITLE
Add tinymath as standalone crate

### PR DESCRIPTION
**Pull request by sffc**
I pulled the interesting parts of the int math stuff I did in the LSTM into a new experimental crate.

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
Haven't checked the math but the crate looks fine

**Comment by sffc** [comment]
I changed it to tinymath because I want flexibility to add non-integer things to it in the future.

**Comment by robertbastian** [comment]
With #3195 not planned to be merged, does this need to be reviewed?

**Comment by sffc** [comment]
This PR contains standalone experimental code that may be valuable to have in version control and may be useful for future ML algorithms that have different constraints.

**Comment by sffc** [comment]
This has been released as https://github.com/sffc/tinymath

**Pull request closed without merging**
