### PR TITLE
Revert "CI goes vroom"

### PR DESCRIPTION
**Pull request by robertbastian**
Reverts unicode-org/icu4x#3070

### CODE REVIEW

**Comment by zbraniecki** [comment]
Can you document why you need to revert it?

**Comment by robertbastian** [comment]
Elango and Manish pushed commits to my PR while I slept and then approved and merged. The changes they made were not what I was trying to do and were incorrect so the post-merge CI is broken.

**Comment by zbraniecki** [comment]
Ah, thank you!

**Review by Manishearth — APPROVED** [review]

**Comment by robertbastian** [comment]
Not mergeable because the required CI renames have to be reverted too.

**Comment by Manishearth** [comment]
I think I undid some of those renames, but it's probably not exactly what it was like before.

**Pull request merged**
