### PR TITLE
Updating lock files

### PR DESCRIPTION
**Pull request by robertbastian**
#2966

### CODE REVIEW

**Comment by robertbastian** [comment]
@sffc `icu_capi` doesn't build with the pinned nightly and fresh dependencies. Can we update the nightly?

**Comment by robertbastian** [comment]
The issue is that the libc crate doesn't build with our old nightly anymore. It assumes that when it's built with a nightly it's a current one, so tries to use const traits or something.

This means that currently our example for LTO is not reproducible by clients unless they copy our outdated lock file, which I don't think is acceptable. We need to find a new nightly and upgrade to LLVM 15 (if I read https://github.com/unicode-org/icu4x/issues/2719#issuecomment-1268811204 correctly).

**Comment by Manishearth** [comment]
> The issue is that the libc crate doesn't build with our old nightly anymore. It assumes that when it's built with a nightly it's a current one, so tries to use const traits or something.

ugh, this is a pain, I wonder why it's doing that

**Comment by Manishearth** [comment]
In that case, yeah, I'm open to updating the nightly.

**Comment by Manishearth** [comment]
Perhaps we can use libc with that feature disabled?

**Comment by Manishearth** [comment]
Actually, I'm pretty sure this is a bug: libc's [build.rs](https://docs.rs/crate/libc/latest/source/build.rs) does version checking, it should not be prone to this problem. Perhaps its nightly selection code is off.

**Comment by robertbastian** [comment]
It's a transitive dependency of `dlmalloc`. We can hackily pin the version in the `Cargo.toml` though.

**Comment by Manishearth** [comment]
Yeah let's not do that, it makes life annoying for downstream clients.

Can you post a repro of this on the libc repo? If not I can do this later. The libc crate seems to have version checks for its features in build.rs, so it's strange that it's broken.

**Comment by robertbastian** [comment]
https://github.com/rust-lang/libc/issues/3066

**Comment by Manishearth** [comment]
> This is an example, we're not publishing that crate.

Ah! That's fine

**Comment by robertbastian** [comment]
The postcard diff is caused by the new version of `regex-syntax`. I've verified that old data new library and new library old data both work, so I guess it's fine. Shame that it's getting bigger.

**Comment by sffc** [comment]
> The postcard diff is caused by the new version of `regex-syntax`. I've verified that old data new library and new library old data both work, so I guess it's fine. Shame that it's getting bigger.

This is troubling on a few levels, but I'm inclined to ignore it as long as nothing actually breaks because of the diff

**Review by sffc — APPROVED** [review]

**Comment by robertbastian** [comment]
Filed https://github.com/BurntSushi/regex-automata/issues/27

**Pull request merged**
