### PR TITLE
Fix OptionVarULE in zerovec to also use C, packed

### PR DESCRIPTION
**Pull request by Manishearth**
We overlooked this

Backport in #5144

### CODE REVIEW

**Review by robertbastian — CHANGES_REQUESTED** [review]
On main there are 14 `#[repr(packed)]`s in `utils/zerovec`. This changes 3

**Comment by robertbastian** [comment]
17 `repr(packed)` actually

**Review by robertbastian — COMMENTED** [review]
That's 10

**Comment by Manishearth** [comment]
Ah, forgot to hit save on the design doc

**Review by robertbastian — APPROVED** [review]

**Pull request merged**
