### PR TITLE
Fix numbering systems fallback

### PR DESCRIPTION
**Pull request by robertbastian**
#3181

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by sffc** [comment]
Seems odd that this would break. What numbering system stopped working?

**Comment by robertbastian** [comment]
The new `hnj-Hmnp` locale doesn't have `decimalFormats-numberSystem-hmnp` in the data

**Comment by sffc** [comment]
But UTS 35 says

> Locales that specify a numbering system other than "latn" as the default should also specify number formatting symbols that are appropriate for use within the context of the given numbering system. For example, a locale that uses the Arabic-Indic digits as its default would likely use an Arabic comma for the grouping separator rather than the ASCII comma.

Where did you get the idea to fall back to latn?

**Comment by sffc** [comment]
I filed https://unicode-org.atlassian.net/browse/CLDR-16480 to fix this in CLDR. I think we should roll back this ICU4X change because there is no spec text I can find that says we should unconditionally fall back to Latn.

**Comment by robertbastian** [comment]
> Where did you get the idea to fall back to latn?

From @srl295

**Comment by srl295** [comment]
> > Where did you get the idea to fall back to latn?
> 
> 
> 
> From @srl295 

Probably a spec hole.

**Comment by srl295** [comment]
> I filed https://unicode-org.atlassian.net/browse/CLDR-16480 to fix this in CLDR. I think we should roll back this ICU4X change because there is no spec text I can find that says we should unconditionally fall back to Latn.

Briefly,

@sffc firstly  I think CLDR has a test that makes sure there's an Alias as such in root for all numbering systems. 

Secondly that test probably skipped hnj because it's not basic 

Thirdly you are probably experiencing this because it's a non basic locale. Should it have been filtered ?

So I think this should be kept not reverted and the spec fixed

**Comment by sffc** [comment]
1. If CLDR has such a test, the test clearly is not working
2. The spec makes no exception for less-than-basic locales
3. The new ICU4X configuration will filter less-than-basic locales but we should still work with all locales

**Comment by sffc** [comment]
1. If CLDR has such a test, the test clearly is not working
2. The spec makes no exception for less-than-basic locales
3. The new ICU4X configuration will filter less-than-basic locales but we should still work with all locales

**Comment by srl295** [comment]
> > I filed https://unicode-org.atlassian.net/browse/CLDR-16480 to fix this in CLDR. I think we should roll back this ICU4X change because there is no spec text I can find that says we should unconditionally fall back to Latn.
> 
> Briefly,
> 
> @sffc firstly  I think CLDR has a test that makes sure there's an Alias as such in root for all numbering systems. 
> 
> Secondly that test probably skipped hnj because it's not basic 
> 
> Thirdly you are probably experiencing this because it's a non basic locale. Should it have been filtered ?
> 
> So I think this should be kept not reverted and the spec fixed 

Meant to say:
- keep this UNTIL 
- spec fixed
- cldr test fixed 
- cldr data fixed

**Comment by srl295** [comment]
> 1. If CLDR has such a test, the test clearly is not working

It probably skips non basic (previously, non common/main). The intent is clear. 

> 2. The spec makes no exception for less-than-basic locales

Less than basic are already in violation. 

> 3. The new ICU4X configuration will filter less-than-basic locales but we should still work with all locales

Ok. 

I asked to take the ticket and plan to do so. Barring any objection expect the Alias

**Pull request merged**
