### PR TITLE
Check all lines of license header

### LINKED ISSUE #549: Enforce all three lines of copyright header
The copyright header check only looks at the first line.  We should check all three lines, including the third line where we should say "main" instead of "master".

### PR DESCRIPTION
**Pull request by echeran**
Closes #549

### CODE REVIEW

**Review by Manishearth — DISMISSED** [review]

**Review by sffc — APPROVED** [review]

**Comment by sffc** [comment]
Optional: I find it ugly when the license header is smushed up against other code.  Should we require an empty line after the header?

For example, instead of

```
// This file is part of ICU4X. For terms of use, please see the file
// called LICENSE at the top level of the ICU4X source tree
// (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).
use icu::locid::LanguageIdentifier;
```

should we require

```
// This file is part of ICU4X. For terms of use, please see the file
// called LICENSE at the top level of the ICU4X source tree
// (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

use icu::locid::LanguageIdentifier;
```

**Comment by Manishearth** [comment]
Makes sense to me

**Comment by gregtatum** [comment]
> Optional: I find it ugly when the license header is smushed up against other code. Should we require an empty line after the header?

I agree, this is especially hard to read when the following line is documentation.

**Review by sffc — APPROVED** [review]
🚀

**Pull request merged**
