### PR TITLE
Don't allocate to check canonicalization result

### PR DESCRIPTION
**Pull request by robertbastian**
#2748

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
I believe it used to return a Cow anyway, but this is more explicit.

**Comment by Manishearth** [comment]
Won't this canonicalize twice, though?

**Review by Manishearth — CHANGES_REQUESTED** [review]
Actually yeah, this canonicalizes twice. Are you sure the no alloc route in the previous one is actually allocating? It should be returning a Cow (just not one with the right lifetime)

**Review by sffc — CHANGES_REQUESTED** [review]
I have a better solution in #5738

**Comment by sffc** [comment]
> Actually yeah, this canonicalizes twice. Are you sure the no alloc route in the previous one is actually allocating? It should be returning a Cow (just not one with the right lifetime)

It allocates if there is more than one subtag. It borrows only if there is a single subtag it can borrow from.

**Comment by robertbastian** [comment]
> I think this PR is better than the status quo

And yet I get two request-changes.

**Comment by Manishearth** [comment]
> I think this PR is better than the status quo because I think generally allocation is more expensive than calling the Writeable impl twice.

I'm not convinced of this but I could easily be: this type of allocation is typically considered expensive because it's a memcopy, not because it's a malloc, and the Writeable impl also does a whole read of the string, except it's chunked across fields so it's a less efficient memcopy.

Temporary small allocations are annoying but also rather cheap. We should avoid them but I don't think we need to avoid them this way.

However I don't really feel strongly about this or think it warrants benchmarking, so ultimately I'm fine with this if folks wish to re-Write compared to allocating, and also happy with landing this as an improvement to the status quo.

**Comment by sffc** [comment]
> > I think this PR is better than the status quo
> 
> And yet I get two request-changes.

Only because I have an alternate approach in a different PR that would conflict with this one if merged.

**Comment by robertbastian** [comment]
> Only because I have an alternate approach in a different PR that would conflict with this one if merged.

And I don't agree with that process. I've written a perfectly mergeable PR which reduces allocations, one of our main goals. The next steps should have been to merge this PR, and discuss if all the work you have then done are worth our time right now.

**Comment by sffc** [comment]
> > Only because I have an alternate approach in a different PR that would conflict with this one if merged.
> 
> And I don't agree with that process. I've written a perfectly mergeable PR which reduces allocations, one of our main goals. The next steps should have been to merge this PR, and discuss if all the work you have then done are worth our time right now.

Our PRs were opened within hours of each other; as it happened, I started working on and opened my PR before I saw yours in my flood of notifications. I think the right process in this type of situation, two PRs directly in conflict with each other, is to decide which one is better and close the other, not merge one just for the sake of merging it.

**Comment by robertbastian** [comment]
It would be nice if you checked your notifications in the morning so you don't invalidate my work.

**Pull request closed without merging**
