### PR TITLE
Using `typedoc` instead of Diplomat-generated docs

### PR DESCRIPTION
**Pull request by robertbastian**
The JS Diplomat docs are quite bad, they use a module structure which is not present in JS, and don't have a lot of detail. Generating docs from the actual code is much more accurate, looks nicer, has more detail, and doesn't require us to maintain the Diplomat docs generator.

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Review by sffc — CHANGES_REQUESTED** [review]
Please also update .github/workflows/artifacts-build.yml and artifacts-info.yml and make sure they work.

Note that this command uses

```
        cd ffi/capi/js/package/docs
        make html
```

which I don't see updated in this PR.

**Comment by robertbastian** [comment]
https://github.com/unicode-org/icu4x/pull/4371/files#diff-d1bb081e6d04ced14e89691280b752ae6124cee2b13d0af35840b7bf3db32a07?!

**Comment by robertbastian** [comment]
@sffc I'm really confused by your comment. The code you're citing changed in the first commit, so I'm not sure what you're looking at.

**Comment by sffc** [comment]
Yeah you only needed to update info.yml. I guess there's nothing to update in build-test.yml; I was looking for changes in 3 yml files but I guess we need to touch only 2 of them

**Pull request merged**
