### PR TITLE
Stabilizing `icu_list`

### PR DESCRIPTION
**Pull request by robertbastian**

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
lgtm, would like to see shane's approval as well

**Comment by sffc** [comment]
We should make it non-default.

**Comment by robertbastian** [comment]
This is blocked on the `regex_automata` release: https://github.com/BurntSushi/regex-automata/issues/20#issuecomment-1021473237

**Comment by robertbastian** [comment]
I removed the re-export from `icu`

**Pull request closed without merging**
