### PR TITLE
Split docs into their own CI job

### PR DESCRIPTION
**Pull request by sffc**

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
lgtm, worth checking what kind of speedup we get before merging

(also, remember to update repo branch protection settings after merging)

**Comment by Manishearth** [comment]
Also, should we be merging this with the doc job? https://github.com/unicode-org/icu4x/pull/1538 I guess they do different things

**Comment by sffc** [comment]
This significantly speeds up `test (ubuntu-latest)`, although `test (mac-latest)` and `test (windows-latest)` are still slow for some reason.

**Comment by sffc** [comment]
The macos test is still taking 18 minutes. Not sure if this is a positive change. Asking @gnrunge to weigh in.

**Comment by gnrunge** [comment]
MacOS or sometimes Windows being the slowest of the thee bu8ild-and-test platforms is consistent in ICU4X CI runs. This PR does not have an impact on the MacOS run.
That MacOS is significantly slower than Ubuntu is also a consistent observation in ICU4C CI build and test.

**Review by gnrunge — APPROVED** [review]

**Comment by sffc** [comment]
I'm going to close and reopen to get one more speed sample.

**Comment by sffc** [comment]
The latest macos test on main: 24m 8s

In this PR: 12m 59s

Looks good to me. I would note that other CI jobs also were faster here than in the last test on main, but not by such a large margin. I'm going to merge!

**Pull request merged**
