### PR TITLE
FormattableMonth -> MonthInfo, and split standard from formatting month codes

### LINKED ISSUE #3821: Fix FormattableMonth for leap months and FormattableYear for shared eras
Currently FormattableMonth is

```rust
pub struct FormattableMonth {
    pub ordinal: u32,
    pub code: MonthCode,
}
```

This is problematic because

1. There is not a clear use case for having both `ordinal` and `code`. We can derive the month number from `code`.
2. `code` in this context is an identifier used for data lookup, but this is not the same as month identity. `M06` and `M06L` for example (Adar and Adar II) are the same month identity but have different display names.

I suggested that we could make `FormattableMonth` be opaque and add getters for the things we need.

---

`FormattableYear`, meanwhile, contains an era code. When we merge islamic down to a single key, we need to consider how this interoperates.

### PR DESCRIPTION
**Pull request by Manishearth**
Also some leftover cleanups in the FFI allowlist from #5509

Fixes #3821

### CODE REVIEW

**Review by sffc — DISMISSED** [review]
Maybe reconsider the name of `ordinal`

**Comment by Manishearth** [comment]
Yeah, I think I prefer `ordinal` over `extended_month`. `ordinal` is clear about what it actually does, `extended` has always been confusing for me and it makes some sense in the context of years (where it's also a term of art) but it's different here.

**Comment by sffc** [comment]
In the issue I said:

> The one people should generally be using though is `standard_code`, but it is really tempting to reach for `ordinal`. So I feel like we should prefix all three.

**Comment by Manishearth** [comment]
That doesn't quite make sense to me: `ordinal` is already the disambiguator, it doesn't say `code` because it's not a code. All three of them have weird names, just that two of them have two-part names because they're also codes. I could call it `ordinal_number` instead if that brings them more in line, though personally I'm not sold on the value of doing that (but happy to do it if you find it valuable).

**Review by sffc — APPROVED** [review]

**Pull request merged**
