### PR TITLE
Create website for ICU4X

### PR DESCRIPTION
**Pull request by echeran**
My personal fork currently has a demo: https://echeran.github.io/icu4x/

Initially not adapting any existing docs, etc. into the content. Maybe collaboration on this branch or iterative PRs can fill that in.

This is also initially not starting out complete because it lacks known required elements like links to API docs for FFI target languages.

### CODE REVIEW

**Comment by sffc** [comment]
Very cool! It makes me hungry for some oatmeal though! 😋

As far as the site content goes, we have 4 sets of docs, all of which are generated with their own docs frameworks (tailored for each programming language via Diplomat), which is fine I think. The landing page can just link down into the individual frontend docs pages. Same with the WASM demo and benchmarks.

Now, the content currently in the repo under the `/docs` directory might be interesting to pull out into the web site. Things like the tutorial, charter, and other user-facing documents. I know there's been discussion about putting the tutorials into a Rust Book layout; maybe we should do that as part of this facelift effort.

See also: #3424, #2929

https://unicode-org.github.io/icu4x/

**Comment by sffc** [comment]
Note: Although there are about 30 files added, almost all of them are sample content that we can delete or replace with our own content. There is not a lot of boilerplate here which is good.

**Comment by robertbastian** [comment]
I think we should host the website in https://github.com/unicode-org/icu4x-docs.

**Comment by echeran** [comment]
> I think we should host the website in https://github.com/unicode-org/icu4x-docs.

Oh, hmm. Is this something that we never discussed, or never came up with a clear agreed upon plan?

My vague recollection is that we want the canonical ICU4X homepage to live in `unicode-org/icu4x`, as in `icu4x.unicode.org` should point to its Github Pages deployment there. We have something very simple at the moment, but we want to have a proper landing site like the website in this PR to be a nice entry point for all types of new visitors. `unicode-org/icu4x-docs` can be where the latest dev snapshot of Rust docs live.

I think we agree that we don't need to host previous official release Rust docs because those already live on docs.rs.

That might be my recollection of what I was thinking. What were you thinking for `unicode-org/icu4x` and `unicode-org/icu4x-docs`, respectively? What do other think?

Of course, we can put whatever we want in either place (`icu4x`, `icu4x-docs`). Regardless of the repo in which we put things, I hope we can avoid the previous problems with Github Pages mapping a domain name to a repo, ensuring the `CNAME` works and is unaffected by CI jobs, etc. I wasn't aware of those issues when they happened before, but now I/we know a little more about that. Hopefully it all works this time around.

**Comment by sffc** [comment]
What are the pros and cons of hosting in the main repo versus icu4x-docs?

**Comment by echeran** [comment]
Maybe the question of pros and cons of a specific choice isn't yet applicable until we understand more the design thoughts behind Robert's idea.

Even though the `icu4x-docs` was created alongside `icu4x` to parallel the `icu` vs. `icu-docs` pairing, I'm open to entertaining different ideas of what those things mean. So long as we're on the same page of the design of how things should behave overall, it should be possible to make all that happen.

**Comment by robertbastian** [comment]
> unicode-org/icu4x-docs can be where the latest dev snapshot of Rust docs live.

I'd do it the exact other way around. It's much easier to have the dev artifacts live in unicode-org/icu4x, because then we don't have to do cross-repo pushes. unicode-org/icu4x-docs is already linked to icu4x.unicode.org, so I thought the website would live there. There you have the whole repo available for the website and don't have to fit into icu4x's repo structure.

**Comment by echeran** [comment]
Between the options listed above, my preference is for Option 2. The reason is that changes to website docs (tutorials/other docs) can be done in the same PR as the code change itself. Even if we get to a world where any tutorials that are in the website docs have been automatically tested via CI somehow, the enforcement of docs consistency would happen at the time of code PR checking if in Option 2.

**Comment by robertbastian** [comment]
> Tutorials/other docs disconnected from repo - requires manual effort to keep up-to-date (PR in the other repo)

This is a pro. We only want to update the website when we do releases, it's currently very annoying that we don't have a stable copy of the tutorials at the last release, as we have to wait with changes until we release and the new APIs are available to clients. If we host the website separately, we can update tutorials in ICU4X as we add/change APIs, and then when we release we copy them over to icu4x-docs. This way the tutorials on the website are always compatible with the release version.

**Comment by sffc** [comment]
I would add an Option 3.

### Option 3: `icu4x` for both static and generated content

Description:

- Dynamically generated content gets generated and pushed in GitHub Actions as they are now
- We put static content (including jekyll configurations) into the existing [website-skeleton](https://github.com/unicode-org/icu4x/tree/main/tools/website-skeleton) directory or something like it
- We archive the `icu4x-docs` repo and point icu4x.unicode.org to the `icu4x` repo's GitHub Pages

Pros:

- Single repo; fewer things to manage organizationally (permissions, CLAs, licenses, reviews, bots, webhooks, ...)
- CI testing against live code (intl. tutorials)
- Don't need to change how we currently generate artifacts except for also running the `jekyll` commands in the existing GitHub Action

Cons:

- Web site changes go through the full ICU4X review process when maybe it's desirable for them to have a lighter-weight process

**Comment by sffc** [comment]
> > Tutorials/other docs disconnected from repo - requires manual effort to keep up-to-date (PR in the other repo)
> 
> This is a pro. We only want to update the website when we do releases, it's currently very annoying that we don't have a stable copy of the tutorials at the last release, as we have to wait with changes until we release and the new APIs are available to clients. If we host the website separately, we can update tutorials in ICU4X as we add/change APIs, and then when we release we copy them over to icu4x-docs. This way the tutorials on the website are always compatible with the release version.

What you describe is the tutorials test working as intended. It helps ensure that we don't make library changes that suddenly break API calls against either the previous or the next release. It is working as intended that we only update tutorials to the latest shiny version of icu4x after it has been released. Having tutorials live and tested out-of-tree is a regression.

**Comment by echeran** [comment]
> This is a pro. We only want to update the website when we do releases, it's currently very annoying that we don't have a stable copy of the tutorials at the last release, as we have to wait with changes until we release and the new APIs are available to clients.

I see. That makes sense. I guess that means embracing the mindset that user-facing docs need to be associated with a specific version of code. That doesn't preclude approving spot fixes for typos, bug fixes, etc., but that should be considered manually on a case-by-case basis, rather than having all docs changes deploy automatically by default.

Before releasing a new version of docs, we would need to ensure that the tutorial code is consistent with the code release, and preferably in a somewhat automated way. Maybe we don't have to design that right now.

So Option 1 makes sense, and the newly added Option 3 also makes sense.

Option 3 also relies on humans applying judgement on which docs changes can be dynamic (dev-facing API docs) vs. which need to be static (user-facing website+other docs) when approving PRs. Having everything in one repo ought to be as workable as any other option, and not having to deal with multiple repos is appealing.

I'm looking at Option 3 > Option 1 > Option 2 now.

**Comment by sffc** [comment]
Some drawbacks with options 1 and 2 (similar to what @echeran wrote):

Option 1 Con: Tutorials and other docs may get stale or out-of-sync and there's no clear signalling process to keep them up-to-date since we mostly are only looking at CI on the main repo.

Option 2 Con: Requires changing how we currently run CI for dev artifacts, which is "finally" working after being broken for a long time. Cross-repo permissions in GitHub Actions are a bit of a pain.

**Comment by robertbastian** [comment]
> What you describe is the tutorials test working as intended. It helps ensure that we don't make library changes that suddenly break API calls against either the previous or the next release. It is working as intended that we only update tutorials to the latest shiny version of icu4x after it has been released. Having tutorials live and tested out-of-tree is a regression.

The status quo is not a good solution. All that test does is block us from updating tutorials in the same PR as code, which is what we want to do, and we have to keep the up-to-date copy of the tutorials in a PR that gets merged after releasing. This is horrible for refactorings and collaboration.

The tutorials-test *is not* a semver test that verifies "that we don't make library changes that suddenly break API calls against either the previous or the next release". It test that the tutorials can be followed with the currently released version.


The fundamental problem is that we need to *version our artifacts*. Tutorials are one type of artifacts for which we have a shoddy solution now (just don't change it except for at release time), FFI docs are another *for which we don't have a solution*: there is no way to get the FFI docs for the 1.4 release, only for head. 

The fact is that at any given point (except for the exact moment we do a release), we're going to have two versions of each artifact: the one corresponding to HEAD, and the one corresponding to the last release. Currently the last-release FFI docs don't exist, and the HEAD tutorials also don't exist, because the test won't let us merge them.

My propoosal is to keep all HEAD artifacts in our working repo, `icu4x`. Then, as part of the release process, we release (copy) them to the website in the `icu4x-docs` repo. The two repos allow us to keep both versions of each artifact. We can of course make changes to the website directly in the `icu4x-docs` repo, because the website itself is not tied to our release schedule, however *any artifacts that are versioned are only copied over during release*.

This lets us stop testing tutorials against both crates-io and HEAD: if HEAD passes at the release tag, and we freeze the tutorial by releasing it to the website, it doesn't need to be tested further. We can then flexibly make changes to the working copy of tutorials and they only have to work with the working copy of our code.


So, as we have two versions of each artifact, I oppose Option 3 because it will be messy to keep them both in the same repo. I oppose Option 2 because the working version should be in our working repo, and the released version in the other repo.

**Comment by echeran** [comment]
- @robertbastian The website should be a versioned thing. Tutorials, etc. depend on specific version of things.
- @sffc docs.rs allows you to go back in history. I'd like to have users go back in history
- @Manishearth I'm against allowing published docs to go back in history. I think it's a niche use case. What you don't want  is old versions cached in search indexes. The new code should be usable for older versions of code. Rust has bad experience in the past, and docs.rs defaulting to latest elps
- @robertbastian For FFI docs, we should have versions. We can use `noindex` markers for latest. But it should be possible to pull up the 1.3 version of the C++ index.
- @Manishearth We should have `noindex` for the latest version (the stable URL, ex: `/latest`) because the latest becomes an old version, too
- @robertbastian You can control `noindex` at the website level
- @Manishearth Please be very careful about `noindex`. It's something you don't want to mess up, you get results stuck in search indexes for years. If you change content under the URL `/latest`, then you might not be able to have permalinks, etc. I don't want to get into the technical details, bottom line is be very careful.
- @robertbastian Before other things, do we want to host the website at `HEAD` of `main`, or should 
- @Manishearth Non-code docs should be hosted at `HEAD`, everything else should be in a versioned in a separate folder. That includes API docs, FFI docs, and maybe tutorials.
- @robertbastian Do we need to host code docs in this repo?
- @Manishearth No. That means where the docs live, not about what is presented to users.
- @robertbastian Where the sources live is somewhat important for versioning. So if we have those code 
- @Manishearth That makes sense. Sounds like what I was envisioning.
- @sffc I'm not a huge fan of intermediate benchmark results in a GCP bucket. I'd like to think of GCP access as something that might disappear at any moment's notice and what we have in our git repo is versioned. I'd like benchmarks to be a part of the versioned artifacts. GCP can be a store of the latest artifacts, but I'd like artifacts to be versioned. `icu4x-docs` can contain those versioned artifacts, and we can discuss what does the website look like at `HEAD`
- @robertbastian You've been talking about `HEAD`, but I've talking about `latest` as in the latest release. When we add new docs to FFI, we don't want to update the website immediately
- @echeran We have 2 categories can 
- @sffc It would be good to start thinking about our `HEAD` artifacts usable as the source of truth. One way is to mark the version that APIs are added. Ex: "since 1.4", "nightly", etc. It would be nice to have the latest docs that people read are not 4-6 months ago. Besides freshness, the other benefit can see what's coming. It can also help so that people know which version of ICU4X to put in their `Cargo.toml`.
- @robertbastian What you're proposing is ICU4X nightly, which sounds like a lot of work. The released docs are only 4-6 months old if the latest release itself is 4-6 months old.
- @Manishearth There are 2 ways of looking at the benchmarks. They are both a released artifact and an internal artifact. The released artifact should not be on GCP. GCP should be able to go away. What we need for external users is versioned benchmark data. GCP works for internal users because it has artifacts for every commit
- @robertbastian Everything from the GCP bucket can be regenerated from the repo except the benchmarks, because there is state.
- @Manishearth Then the benchmarks could be stored in another git repo. 
- @robertbastian Ideally the benchmarks should be versioned with the code. But that's expensive. They're 2 MB right now. Versioning them in another repo doesn't gain us much since it's not connected if it's in a different repo.
- @sffc If we want to have multiple versions of the website available, then we can store the older versions each in their separate folder.
- @Manishearth It would be nice to store per-release benchmarks
- @robertbastian I'm not sure what value benchmarks provided to end users
- @Manishearth With releases, they provide value. But per commit, yes it's a mess
- @sffc In terms of what makes benchmarks most useful to users, after a release, we should archive the benchmark data at the time of the release.
- @robertbastian For the public facing benchmarks, yes. But for the dev snapshots, we sometimes have to fix what happened to benchmarks when they go missing or get renamed
- @sffc Back to location of which sources / artifacts are stored where. If we want want stored versioned artifacts, then it shouldn't be on `icu4x` `HEAD`, because that should be the latest. And it shouldn't be on GCP. So maybe it should be on `icu4x-docs`, which is Option 1.
- @robertbastian What's the value of versioned tutorials?
- @sffc Having versioned FFI docs is important. We can bikeshed about which things get versioned, but the fact is that some stuff is versioned, and we can figure out what exactly later
- @Manishearth `icu4x-docs` can have folders per version. We can decide what goes where later. We have consensus on wanted to store versioned FFI docs, at least
- @robertbastian I don't want to store versioned Rust docs
- @sffc I like CI enforcing things. If you checkout `icu4x` at a particular tag, then you can copy the results of the CI build job into `icu4x-docs`.
- @robertbastian Yes, and we can create scripts to do that. Also, we have 2 tutorials tests: 1) test against main 2) test against the latest API. If we change our processes to update the tutorials at release time, can one of those tests go away?
- @sffc We introduces the crates.io test for tutorials to fix a problem. These things were getting out of sync
- @Manishearth Yes, we don't want to get rid of the test
- @robertbastian The release task should not be to rewrite the tutorials test
- @Manishearth We shouldn't have to do that at release time. We should have tutorials in 2 places: the versioned version in one folder, and the latest version in another folder. We can have all the benefits of checking that things are in sync by having a nightly CI on `icu4x-docs` to check against the latest release version in docs.rs. I don't want to have the old tutorial in the `icu4x` repo.
- @sffc My position is still is that the thing that we're testing is that we write code that compiles against different ICU4X versions. Our crates.io tutorial test is the only one that tests against semver. They run against the old ICU4X version and the latest ICU4X veresion.
- @robertbastian The test has the property of testing a very narrow slice of the API surface against different semvers.
- @Manishearth It has the side effect of a semver test, it's a proxy, testing against semver is a side effect, and I don't think it works that well. We should have a proper semver test. I don't want the tail wagging the dog, where you add tutorials in order to improve semver test coverage.
- @robertbastian 99% of changes, ex: in segmenter, are not going to be caught from the tutorial semver test. We can write a CI job for this, that diffs the entire API surface, between latest and the release version.
- @sffc What it does as a semver test is it tests the Cargo features and something else. It's all macro generated. It's not a comprehensive semver test. It tests only the high level APIs and linkages.
- @Manishearth Then we should have a separate test. It's not a desire shared by the team. I would rather have a test for this so that we can write good tutorials, but not to have to change this during every change during development.
- @sffc I think we're in agreement. All I'm saying is that the crates.io serves a purpose for semver testing, and we can replace it with a separate proper semver test. But it serves a purpose, so we should not get rid of the test without continuing to serve that purpose.
- @Manishearth We can also move the semver test, and then we can run it nightly (say in the `icu4x-docs` repo) rather than running it on every PR on the main repo `icu4x`.
- @robertbastian Before the tutorials test, we didn't have a semver test. We had investigated it, but we didn't. We were careful to not break semver. Since adding the semver test, we only had 1 issue with semver, but otherwise have avoided semver problems.
- @Manishearth I would like to find a path forward that preserves semver testing without adding much extra effort.
- @sffc There are a couple of wrinkles in @Manishearth 's plan, but it sounds doable. Another issue is that I don't like having multiple different places, but maybe that's an internal issue. We now are talking about adding CI to `icu4x-docs`
- @Manishearth We don't need a cron CI on `icu4x-docs`. It can just be PR check. It's not that important, but I would like it.
- @sffc I would like a CI job that runs when we release version 1.4.

**Comment by echeran** [comment]
Conclusion:

* The website will live in the `icu4x-docs` repo
* `icu4x-docs` contains all the pretty website stuff and can be updated at any time
* it already has the icu4x.unicode.org domain
* `icu4x-docs` will contain versioned subfolders for each release, plus a "main website".
    * What is versioned may be determined later, we know we want FFI docs to be versioned. Tutorials TBD. We will not host rustdoc at all.
    * We will be very careful about `noindex` for versioned subfolders.
      * Old releases should not get indexed 
      * The latest release should get indexed under `/latest`, or should get indexed under `/1.<latest>` in a way that is not "sticky" in search engines
      * Ideally we do not have to duplicate a `/latest` and a `/1.<latest>`.
        * This would need a redirect, we may wish to do research on how often `noindex` gets reconsumed by crawlers when it comes to redirects.
        * Or we do what docs.rs does; which is that `/latest` is indexed, and it has a permalink button to `1.<latest>`
* We may rename the repo to `icu4x-website` or something
* Benchmark data files will be copied in every release. TBD how and whether to display them as HTML files; there may be some worth in having a "releases only" benchmark page for the external website (rather than "one data point per commit", which is more internally useful)
* the repo's dual tutorial test (against head, crates.io) will be changed as follows
    * switch the tutorials-local test to be the only CI tutorials CI test in the `icu4x` repo (deleting the tutorials-cratesio test)
    * The existing tutorials code gets versioned like the artifacts; for example, at `/1.4/crates` in the `icu4x-docs` repo
    * `icu4x-docs` gets a CI job that performs the equivalent coverage as the two existing CI jobs: one that tests tutorials against crates.io, and one that tests against icu4x component crates at the `main` tag. The job runs as a cron nightly CI.
    * We should consider a better semver test on the main repo but that is a totally separate discussion.
* keep unicode-org.github.io/icu4x but set it noindex to avoid duplicate google search results; don't expose links to GCP to anyone other than core ICU4X contributors

Agreed: @sffc @robertbastian @echeran @Manishearth

**Comment by robertbastian** [comment]
@echeran can we close this PR?

**Pull request closed without merging**
