### PR TITLE
Adding `rayon` feature to `icu_datagen`

### PR DESCRIPTION
**Pull request by robertbastian**

### CODE REVIEW

**Review by skius — APPROVED** [review]

**Review by sffc — COMMENTED** [review]
Is there a bug number?

Wait for LGTM from @Manishearth

**Comment by robertbastian** [comment]
No, this is just something I'd like for benchmarking, and @Manishearth will probably appreciate as well.

**Review by Manishearth — APPROVED** [review]
Not opposed to this. Personally I don't have a major client need for this but it does sometimes simplify debugging.

**Review by Manishearth — APPROVED** [review]
Not opposed to this. Personally I don't have a major client need for this but it does sometimes simplify debugging.

**Review by Manishearth — APPROVED** [review]
Not opposed to this. Personally I don't have a major client need for this but it does sometimes simplify debugging.

**Comment by robertbastian** [comment]
Whoo triple approval

**Pull request merged**
