### PR TITLE
Update data_pipeline.md to discuss caching

### LINKED ISSUE #332: DataProvider cache invalidation on locale and data changes
At the moment `DataProvider` is a two step state machine which is initialized and loads data. With the current bindings to APIs such as `DateTime` or `PluralRules` it allows for construction of them with a certain dataset loaded from `DataProvider`.

When that happens, the model is set and there's no way to update it in response to certain events during apps life cycle such as:

1. App locale change
2. New data

I think it would be good to discuss early on whether support for those two is in scope and if so, how will we thread through DataProvider.

For example, app locale change may require invalidation of all Formatters, and the user may do it themselves with some form of wrappers that would work like this:

```rust
struct AppCardinalPluralRules {
    get_locales: fn() -> Vec<LanguageIdentifier>,
    pr: PluralRules
}

impl AppCardinalPluralRules {
    pub fn new(get_locales: fn() -> Vec<LanguageIdentifier>) -> Self {
        let current_app_locales = App:get_locales();
        let provider = App::get_provider();
        let locale = negotiate_locales(PluralRules::available_locales(), current_app_locales);
        Self {
            get_locales,
            pr: PluralRules::try_new(locale, &provider, PluralRuleType::Cadinal)
        }
    }

    pub fn select(&self, operands: PluralOperands) -> PluralCategory {
        self.pr.select(operands)
    }

    pub fn on_locales_change(&mut self) {
        let current_app_locales = App:get_locales();
        let provider = App::get_provider();
        let locale = negotiate_locales(PluralRules::available_locales(), current_app_locales);
        self.pr = PluralRules::try_new(locale, &provider, PluralRuleType::Cardinal);
    }
}
```

This allows the app user to call `appCardinalPluralRules.select(5)` and expect it to localize using the current app locales and the result will be different after locales change.

This model is also a bit explicit asking users to wrap every instance they want to use in such wrapper (granted, the wrapper can be generalized), or never cache an instance of a formatter and recreate it on every call just because locales may sometimes change.

If we don't support it, we'll end up with "You changed your apps locales. Please restart the app to take an effect." which I think is a dirty hack.

It also doesn't resolve `new data` scenario. While we can argue that since `locale` is a manadatory constructor argument to pluralrules, it should be regenerated when the argument is different, the change to data doesn't affect the arguments passed to the constructor.

We could handle this by having `DataProvider` have some optional event listener that reacts to data changes, or have a separate crate that monitors and have methods on DataProvider to trigger an update, or have this crate regenerate DataProvider when that happens.

Then, this API will have to call all instances of such wrappers as above to regenerate them in response to new data and new data provider instance.

This solution would be modular and provide good separation of concerns, but make it more complex to handle those scenarios and require some planning of such wrappers and event triggers.

Alternatively, we could try to bake such event triggers into our existing crates effectively ending up with some form of:

```rust
// LocaleService created a DateTimeFormat using current apps locales and
// data provider.
let dtf = LocaleService::DateTimeFormat(&options).unwrap();

// Date is formatted using the current app's locale and data
dtf.format(date);

// User changed their locale fallback chain to `es, en`
LocaleService::set_requested_locales(&[langid!("es"), langid!("en")]);

// This time the date will be formatted to Spanish
dtf.format(date);

// At this point event listener reacts to `new_cldr_data` event and refreshes DataProvider and DateTimeFormats

// This time the date will be formatted to Spanish but with new cldr data
dtd.format(date);
```

I believe the users would like the ergonomics of the last example.

How do we want to design for such scenario? We need to decide what do we want the cache invalidation in those two to look like and enable API calls for that.

### PR DESCRIPTION
**Pull request by sffc**
Fixes #332

I discussed best practices for locale data invalidation, and I also updated the doc to reflect the latest recommendations on data struct design, among other things.

### CODE REVIEW

**Comment by sffc** [comment]
I discussed best practices for locale data invalidation, and I also updated the doc to reflect the latest recommendations on data struct design, among other things.

**Review by zbraniecki — APPROVED** [review]
lgtm!

One optional adjustment I'd consider is that your wording around "there should be no need for memoization of formatters" is very strong. I am really happy that you see a way to that and I consider it one of the core aspects of my work on ICU4X to maximize performance of the system.
But we have not yet validated that claim. My plan is to get there soon after 0.2 with our plan to hook icu4x 0.2 into SpiderMonkey and run against test262 and benchmarks, but we have not yet done it.

In result, I'm wondering if there's a value in strengthening the indication that this is an aspirational goal at this point.

If you think that there's no need for such change because the document itself is a design doc with claims about the final value proposition, I'm comfortable with it landing as-is.

**Comment by sffc** [comment]
I assume you're talking about this paragraph:

> Note that it is a *design goal* of ICU4X that clients should not need to create any other caches. There should be no reason to store a formatter object for longer than the time it takes to render the component.

I have that stated as a "design goal".  Design goals are not always 100% achievable; they are something we should strive for.  ICU4X mostly likely does not yet meet this design goal, but it's a direction I want us to go.  I go on to lay out concretely steps we can take to achieve this design goal.

**Review by mihnita — APPROVED** [review]
LGTM
Not even a nitpick, although OI've tried :-)

**Pull request merged**
