### PR TITLE
Wasm demo improved

### PR DESCRIPTION
**Pull request by QnnOkabayashi**
Improve the WASM demo website significantly with a nicer UI and demos for fixed decimal formatting, gregorian date time formatting, and segmentation (kinda working).

Also I think I did the rebase poorly so there are a bunch of random commits. Start review at [Demo preview in artifacts-info](https://github.com/unicode-org/icu4x/commit/f3edda10718d5b69d3330971f1ffca06a835c601)

### CODE REVIEW

**Comment by Manishearth** [comment]
FFI test fails

**Review by Manishearth — DISMISSED** [review]

**Comment by Manishearth** [comment]
Ah, it just needs diplomat-gen

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
more failures

**Comment by Manishearth** [comment]
Pushed a fix (be sure to git pull if doing more fixes)

**Comment by sffc** [comment]
Please fix the conflict. (I merged a PR of mine that created it)

**Comment by sffc** [comment]
Actually I'll fix it for you

**Comment by Manishearth** [comment]
@QnnOkabayashi 

```
@ ./src/ts/app.ts 3:0-35 11:0-9

ERROR in /home/runner/work/icu4x/icu4x/ffi/diplomat/wasm/wasm-demo/src/ts/date-time.ts
./src/ts/date-time.ts 1:102-126
[tsl] ERROR in /home/runner/work/icu4x/icu4x/ffi/diplomat/wasm/wasm-demo/src/ts/date-time.ts(1,103)
      TS2305: Module '"icu4x"' has no exported member 'ICU4XHourCyclePreference'.
ts-loader-default_e3b0c44298fc1c14
 @ ./src/ts/app.ts 3:0-35 11:0-9

ERROR in /home/runner/work/icu4x/icu4x/ffi/diplomat/wasm/wasm-demo/src/ts/date-time.ts
./src/ts/date-time.ts 61:12-41
[tsl] ERROR in /home/runner/work/icu4x/icu4x/ffi/diplomat/wasm/wasm-demo/src/ts/date-time.ts(61,13)
      TS2554: Expected 4 arguments, but got 5.
ts-loader-default_e3b0c44298fc1c14
 @ ./src/ts/app.ts 3:0-35 11:0-9
```

**Review by Manishearth — APPROVED** [review]

**Pull request merged**
