### PR TITLE
Change benches to use static data provider

### LINKED ISSUE #346: Automate bincode and/or static data generation for benchmarks
Loading JSON files from the file system using `std::io` is straightforward and good for testing, but it isn't as useful for performance benchmarks or code size benchmarks.

We should wire up the testdata project to generate data in other formats.  I suggest that we use `build.rs` to generate the other data formats on the fly, based on the content of the JSON files.  This way we keep only the JSON files in source control, and the other files are dynamically generated.

### PR DESCRIPTION
**Pull request by sffc**
Fixes #346
Depends on #947

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by sffc** [comment]
Compile error:

```
error[E0425]: cannot find function `get_static_provider` in crate `icu_testdata`
  --> components/datetime/benches/datetime.rs:18:34
   |
18 |     let provider = icu_testdata::get_static_provider();
   |                                  ^^^^^^^^^^^^^^^^^^^ not found in `icu_testdata`

error: aborting due to previous error
```

Looks like I need to enable a feature.

**Review by zbraniecki — DISMISSED** [review]

**Comment by sffc** [comment]
Depends on #947

**Review by Manishearth — APPROVED** [review]

**Review by gregtatum — APPROVED** [review]
praise: Yay, this is exciting.

**Comment by gregtatum** [comment]
Also, dminor won't be available to review until next week, so I wouldn't wait on his feedback here before merging.

**Comment by gregtatum** [comment]
Locally when I run this I'm getting this error:

```
~/dev/icu4x/components/datetime on icu4x/pr/892 at 15:39:54
➤ cargo bench
    Finished bench [optimized + debuginfo] target(s) in 0.11s
     Running unittests (/Users/greg/dev/icu4x/target/release/deps/datetime-01c60f4cf42e05fd)
WARNING: HTML report generation will become a non-default optional feature in Criterion.rs 0.4.0.
This feature is being moved to cargo-criterion (https://github.com/bheisler/cargo-criterion) and will be optional in a future version of Criterion.rs. To silence this warning, either switch to cargo-criterion or enable the 'html_reports' feature in your Cargo.toml.

Benchmarking datetime/datetime_overview: Warming up for 3.0000 sthread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DataProvider(Resource("Serde Deserialization Error"))', components/datetime/benches/datetime.rs:33:84
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: bench failed
```

**Review by nordzilla — APPROVED** [review]

**Comment by sffc** [comment]
> issue: Locally when I run this I'm getting this error:

That issue is solved by #947, which is why I closed and re-opened the PR, to trigger a fresh merge.

**Comment by gregtatum** [comment]
I can confirm it's fixed on my end on `main`.

**Pull request merged**
