### PR TITLE
Add coptic calendar to cldr

### LINKED ISSUE #1119: Implement the Coptic calendar
Part of https://github.com/unicode-org/icu4x/issues/534

This will require implementing a Julian calendar to wrap around

### PR DESCRIPTION
**Pull request by pandusonu2**
Fixes #1119

### CODE REVIEW

**Comment by pandusonu2** [comment]
@Manishearth lemme know if any other files need to be changed

**Review by Manishearth — APPROVED** [review]
This mostly looks right!

One thing: could you add a couple tests to datetime/tests/fixtures? Perhaps in components.json and components-width.json, see what we've done for Buddhist. CLDR data for Coptic/en is not that great so I'd suggest using coptic/fr instead, and just run the test to see what the expected string is.

**Comment by pandusonu2** [comment]
> This mostly looks right!
> 
> One thing: could you add a couple tests to datetime/tests/fixtures? Perhaps in components.json and components-width.json, see what we've done for Buddhist; but no need to add _as many_ tests for Coptic. CLDR data for Coptic/en is not that great so I'd suggest using coptic/fr instead, and just run the test to see what the expected string is.

Done

**Review by Manishearth — DISMISSED** [review]

**Comment by Manishearth** [comment]
ready to go after you fix merge conflicts (testdata needs to be regenned)

**Review by Manishearth — APPROVED** [review]

**Pull request merged**
