### PR TITLE
Marking deduplication in fingerprints

### PR DESCRIPTION
**Pull request by robertbastian**
Also deleting testdata fingerprints, as baked data fingerprints are more exhaustive.

Also removing non-singleton `und`s from stub data, as they're not needed for building, and with marker attributes can become quite big as well.

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Review by sffc — COMMENTED** [review]
Issue: Why are all the non-singleton keys losing their data in `datagen/tests/data/baked`?

**Comment by sffc** [comment]
IIRC, one of the advantages of including at least a little bit of data in all the keys was that we have a formatted output source of the fallback logic. Otherwise we rely solely on the non-formatted full baked data.

**Comment by robertbastian** [comment]
In #5009 I'm generating hello-world baked data, similarly to how we test blob and fs with hello-world.

**Comment by robertbastian** [comment]
https://github.com/unicode-org/icu4x/pull/5009/files#diff-a330dbcf41d51842ec06f11445c3b6fb2f8ae18310e6430ba9ff6e9d7d65dcba

**Pull request merged**
