### PR TITLE
Document license header requirements in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by hsivonen**
Per email and meeting, document the license header comments requirements.

### CODE REVIEW

**Comment by srl295** [comment]
- cc to @alolita who is working on unicode-wide docs for this
- xref: https://github.com/unicode-org/cldr/pull/657 / https://github.com/unicode-org/cldr/pull/661 (CLDR's)

**Review by srl295 — APPROVED** [review]
LGTM

**Review by echeran — APPROVED** [review]
LGTM.

**Comment by sffc** [comment]
Ping @alolita - can you take a look and confirm?

**Review by alolita — APPROVED** [review]
Lgtm. From my discussions with legal not having an explicit date in the copyright works. This assumes that the orginal date of copyright can be traced from the commit history or a readme file in the top-level repo folder.

**Pull request merged**
