### PR TITLE
Returning `ExtraneousLocale` in `BlobDataProvider`

### LINKED ISSUE #3505: `BlobDataProvider` should return `DataErrorKind::ExtraneousLocale` for singleton structs
Currently it returns `MissingLocale`, which is not correct, as it will make fallback continue. For example requesting `de-DE` for a singleton with fallback will try `de-DE`, `de`, `und` and actually succeed, where it should be an error because trying `de-DE` for such a key is a bad request.

### PR DESCRIPTION
**Pull request by robertbastian**
And not in datagen

Fixes #3505

### CODE REVIEW

**Review by sffc — COMMENTED** [review]
Technically speaking, _both_ BlobDataProvider _and_ DatagenProvider should be returning the ExtraneousLocale error. We're not doing it consistently everywhere in DatagenProvider. But I also understand that it's hard to enforce consistently across all the various impls of DatagenProvider.

**Comment by Manishearth** [comment]
In favor of the blob changes, feel iffy about the datagen ones; I don't mind having those around.

**Comment by robertbastian** [comment]
I removed the datagen ones because only a handful out of dozens of singleton implementations correctly return `ExtraneousLocale`. Currently the datagen provider's error cases aren't great across the board, for example if you call a non-singleton load with a locale that's not in `supported_locales`, you'll often get an IO error instead of a `MissingLocale` error. I'm happy to fix that separately if we feel like that's an issue.

**Review by Manishearth — APPROVED** [review]
seems fair. would like the defence in depth of having these errors in more places, but not particularly insistent

**Pull request merged**
