### PR TITLE
Expose astronomy in calendrical_calculations

### PR DESCRIPTION
**Pull request by westy92**
Expose the astronomy module in `calendrical_calculations`.

### CODE REVIEW

**Review by Manishearth — CHANGES_REQUESTED** [review]
This is definitely not intended to be public any time soon. Maybe in the long run. But the current API is not designed for general use.

**Comment by robertbastian** [comment]
This is a pre-1.0 crate, if we want to change the API we can just do it and bump to 0.2. The code is there, let's just let people use it?

**Comment by Manishearth** [comment]
Making it public means we are expecting people to use it, which means people will want to ask us for things. My reluctance is not a reluctance to _stabilize_, it's a reluctance to _maintain_. I don't want to have to polish the API surface here.

**Comment by robertbastian** [comment]
Make it `#[doc(hidden)]` to set clear expectations?

**Comment by Manishearth** [comment]
https://www.hyrumslaw.com/

**Comment by Manishearth** [comment]
Fundamentally, the ask here is "I want to use this". My position here is "I don't want you to use this".

**Comment by Manishearth** [comment]
@westy92 at the very least I would need to know what you need this for and why one of the other astronomy crates is unsuitable. I'm not fundamentally opposed to opening this up but in general I try to limit the number of things that I am maintaining when possible. It's not a huge deal for _one crate_ but I work on enough things that it adds up quickly.

Closing for now, could reopen if convinced.

**Comment by Manishearth** [comment]
(I'm likely to do this anyway since I'm beginning to need more astronomy functions in the core calendars crate)

**Pull request closed without merging**
