### PR TITLE
Add WASM build task for examples

### PR DESCRIPTION
**Pull request by sffc**
With this PR, you can run the following from the root of the repository:

```bash
$ cargo make wasm
```

And you get:

```
wasmpkg
├── elevator_floors.d
├── elevator_floors.wasm
├── elevator_floors.wasm.opt
├── elevator_floors.wasm.txt
├── elevator_floors.wasm.wat
├── filter_langids.d
├── filter_langids.wasm
├── filter_langids.wasm.opt
├── filter_langids.wasm.txt
├── filter_langids.wasm.wat
├── permyriad.d
├── permyriad.wasm
├── permyriad.wasm.opt
├── permyriad.wasm.txt
├── permyriad.wasm.wat
├── tui.d
├── tui.wasm
├── tui.wasm.opt
├── tui.wasm.txt
├── tui.wasm.wat
├── unicode_bmp_blocks_selector.d
├── unicode_bmp_blocks_selector.wasm
├── unicode_bmp_blocks_selector.wasm.opt
├── unicode_bmp_blocks_selector.wasm.txt
├── unicode_bmp_blocks_selector.wasm.wat
├── unread_emails.d
├── unread_emails.wasm
├── unread_emails.wasm.opt
├── unread_emails.wasm.txt
├── unread_emails.wasm.wat
├── work_log.d
├── work_log.wasm
├── work_log.wasm.opt
├── work_log.wasm.txt
└── work_log.wasm.wat
```

Depends on #376

### CODE REVIEW

**Comment by sffc** [comment]
This is ready for review.

I added `#![feature(start)]` to the examples because it removes quite a bit of machinery from the WASM file.  However, the stable channel doesn't like that.  I could use `#![no_main]` instead, and export a C function, but that's not as ergonomic as `#[start]`.

**Review by zbraniecki — DISMISSED** [review]

**Comment by sffc** [comment]
Depends on #376.  I will rebase on top of that PR once it is merged, and I'll be able to change the configurations to build the examples in nightly mode.

**Comment by sffc** [comment]
Suggestions on how to resolve the need for nightly mode in the examples?

There hasn't been a lot of movement on the feature request upstream:

https://github.com/rust-lang/rust/issues/29633

Options:

1. Use `#![no_main]` instead of `#[start]` and suffer the more complicated code
2. Change CI to build examples in nightly mode
3. Revert to using the Rust default main, even though it adds noise to the WASM files

**Comment by zbraniecki** [comment]
> Suggestions on how to resolve the need for nightly mode in the examples?

I'd recommend sticking with nightly for the exploration phase.

**Comment by sffc** [comment]
2020-11-12: Shane to try implementing option 1 or 6, update PR, and discuss next week if needed.

**Comment by sffc** [comment]
This no_main+no_mangle trick seems to get the job done, and is stable: https://github.com/rust-lang/rust/issues/29633#issuecomment-370549234

However, it's noted that this is an imperfect solution that might not work on all other platforms: https://github.com/rust-lang/rust/issues/29633#issuecomment-569545768

I propose that we use the no_main+no_mangle solution for now, since it works on Linux, Mac, and Windows, and migrate to `#[start]` once it stabilizes.

**Review by echeran — APPROVED** [review]
LGTM

**Review by zbraniecki — APPROVED** [review]

**Pull request merged**
