### PR TITLE
Temporarily add testdata to repo

### PR DESCRIPTION
**Pull request by robertbastian**

### CODE REVIEW

**Review by sffc — APPROVED** [review]

**Comment by robertbastian** [comment]
We don't necessarily need to merge this, I'm happy with approval to publish from this branch.

**Comment by robertbastian** [comment]
Published, closing.

**Comment by sffc** [comment]
Can you push the exact commit you published to a tag on this repo? Probably `ind/icu_testdata@1.3.0`

**Comment by robertbastian** [comment]
It's the commit in this PR. I don't think I can create tags.

**Comment by sffc** [comment]
I don't think there's a restriction for pushing tags but I went ahead and did it: https://github.com/unicode-org/icu4x/releases/tag/ind%2Ficu_testdata%401.3.0

**Pull request closed without merging**
