### PR TITLE
Replace `try_from_str` by `FromStr::from_str`

### PR DESCRIPTION
**Pull request by robertbastian**
#4931

### CODE REVIEW

**Review by zbraniecki — APPROVED** [review]
lgtm.

**Review by sffc — CHANGES_REQUESTED** [review]
I don't think I agree. See issue

**Comment by robertbastian** [comment]
This was your initial suggestion

**Comment by robertbastian** [comment]
Even if you disagree, I would still like to merge this PR for consistency. We're currently using `FromStr::from_str` for fallible string parsing everywhere, `Pattern::try_from_str` would be the only place where we have `try_from_str`. As it's not yet released, I'd rather release it consistent with the rest of ICU4X and make any other changes in 2.0. This is why I marked this PR as 1.5 blocking.

**Review by sffc — APPROVED** [review]
okay, not happy with the changes long-term, and making this change now just means more work to undo them in 2.0, but I'll buy the consistency-with-1.5 argument if you want to merge this as release manager

**Pull request merged**
