### PR TITLE
Refactor properties to separate crate

### PR DESCRIPTION
**Pull request by echeran**
Renaming the `UnicodePropertyV1` data struct, which represents `UnicodeSet` data for binary properties and for enumerated properties (per key=val pair). It would allow the corresponding data provider struct for `CodePointTrie` data, which would only exist for enumerated properties, to have a consistent name, once created.

### CODE REVIEW

**Comment by iainireland** [comment]
The "Data" in "UnicodeSetData" doesn't seem necessary. (Compare, say icu_decimal::provider, where we have `AffixesV1`, `GroupingSizesV1`, and so on.) Alternative suggestions: `UnicodeSetV1`, `UnicodePropertyV1`, `UnicodePropertySetV1`?

What do you intend to call the CodePointTrie equivalent?

**Comment by echeran** [comment]
> The "Data" in "UnicodeSetData" doesn't seem necessary. (Compare, say icu_decimal::provider, where we have `AffixesV1`, `GroupingSizesV1`, and so on.) Alternative suggestions: `UnicodeSetV1`, `UnicodePropertyV1`, `UnicodePropertySetV1`?
> 
> What do you intend to call the CodePointTrie equivalent?


I looked at other data provider structs, and it seems like they all have a plural noun name, not a singular word name -- just an observation. 

As far as how to re-/name the data struct for UnicodeSet data in a way that will be consistent with the data struct for CPT data, I'm open to suggestions for improve my naming ideas.  We currently have UnicodePropertyV1 and UnicodePropertyMapV1, but ythen ou could imagine changing  UnicodePropertyV1 -> UnicodePropertySetV1 for consistency. But then at that point, why not drop the "Property" -- b/c I think the distinguishing factor between these data structs is the shape of the data (the data structure) that they contain -- and then you get UnicodeSetV1 and UnicodeMapV1.

I thought UnicodeSetV1 sounded too much like UnicodeSet itself (which is why I originally said UnicodeSetDataV1), but that's enough naming bikeshedding for me, and I usually defer to others for short better names.

**Comment by echeran** [comment]
The conversation above is relevant to PR #1167, and I incorporated those ideas into that PR since it seemed necessary to avoid confusing code and naming.

However, in order for that PR to proceed, it needs to solve a confusing and misleading circular dependency that is currently caused by having property enums / newtype structs defined in `icu_uniset`, but the `TrieValue` trait in `icu_codepointtrie`. We intend to implement `TrieValue` for the property enums/newtypes.

At the least, we should refactor the property enums/newtypes to a separate crate. This PR is being renamed and re-purposed to represent that new scope of work which will unblock #1167.

(And if Rust only allows impls of traits on enums/newtypes in the same module/crate in which they are defined, then perhaps the `TrieValue` trait should be moved to this new crate, too?)

**Comment by iainireland** [comment]
Regarding names: I don't have strong feelings, but it occurs to me that if we were doing this from scratch, without basing anything on ICU4C, I think it's likely that we'd omit "Unicode" and call these something more like "CharacterSet" and "CharacterMap". Most of our data is from Unicode; what's interesting about this data is that it represents character properties.

**Pull request merged**
