### PR TITLE
Migrate icu_datetime, icu_decimal, and icu_plurals to DataLocale

### PR DESCRIPTION
**Pull request by sffc**
Part of #2136 

I haven't updated docs tests yet. I want to give everyone one more chance to comment on this change before I spend the time updating docs tests.

### CODE REVIEW

**Review by Manishearth — DISMISSED** [review]
This seems good. I'd like to see this set of changes landed soon to avoid massive churn from the creation of icu_timezones.

**Comment by sffc** [comment]
I'm ideally looking for someone to give stronger support than "this seems good".

**Comment by Manishearth** [comment]
Right. I'm in favor of the direction we decided in https://github.com/unicode-org/icu4x/issues/2136 for constructor signatures , but I do not have strong opinions on `DataLocale` itself, and I would probably prefer if someone who has stronger opinions there gave the final review.

**Comment by Manishearth** [comment]
I am also in favor of moving off of `T: Into<Locale>` into a concrete type. `Into` is nice from a quality-of-life perspective since the function is more flexible in what it accepts, however it pre-enforces some cloning and conversions to the user which can be unfortunate if the user already has an object in the right format that they are able to lend to us.


(Plus, fewer generics in end user APIs are better for us from a codesize pov)

**Review by Manishearth — APPROVED** [review]

**Pull request merged**
