### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by robertbastian**
This should generate weekly updates to `Cargo.lock` files. 

#2966

### CODE REVIEW

**Comment by Manishearth** [comment]
Are we sure we want this? I kinda like being conservative here.

I do want the minimal/maximal tests from #2966 though

**Comment by striezel** [comment]
Two remarks:

1. In my experience the semi-automated dependency updates _can_ be a problem, if a Rust project has a MSRV guarantee, because Dependabot does not care about MSRV. It cannot detect a MSRV and will open pull requests even for updates that break the MSRV. However, icu4x does not seem to make any MSRV guarantees, so this should not be a problem.
2. If you add a `dependabot.yml`, you should consider to limit the amout of pull requests via the [`open-pull-requests-limit`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit) option. Otherwise you might initially get swarmed with PRs, especially when Dependabot is configured to handle updates for more than one project / crate in the repository.

**Comment by Manishearth** [comment]
In https://github.com/unicode-org/icu4x/issues/2966 we are already planning CI for minimal-versions and maximal versions so that won't be a problem.

**Comment by robertbastian** [comment]
It was just an idea, I came across how to do this and remembered that @sffc suggested it in #2966

**Comment by sffc** [comment]
This is cool, but the decision in #2966 was to do it as a CI test instead. I like the bot idea but it just becomes a chore of someone hitting merge on these PRs, which are likely to get gnarled in merge conflicts, etc.

**Pull request closed without merging**
