### PR TITLE
Fix beta rustfmt breakage

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Review by robertbastian — COMMENTED** [review]
How about we remove the comments or move them to their own line?

**Comment by Manishearth** [comment]
Done!

**Review by robertbastian — APPROVED** [review]

**Comment by Manishearth** [comment]
https://github.com/unicode-org/icu4x/pull/5007 got released in the meantime, so it's zerovec 0.10.4 now

**Comment by robertbastian** [comment]
Wrong PR?

**Comment by Manishearth** [comment]
Yep, and the issue got resovled anyway

**Pull request merged**
