### PR TITLE
Don't use `ZeroMap2d` for metazones

### PR DESCRIPTION
**Pull request by robertbastian**
This could be even smaller if we had one map for standard names, and one for daylight names. #5745

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
Do we know why this increases loc even though it decreases postcard? I imagine there's some reduplication happening in baked?

**Comment by robertbastian** [comment]
Baked data LOC is the same, and the actually in-binary size decreases, as can be seen in `fingerprints.csv`. JSON gets more verbose because of tuples.

**Comment by Manishearth** [comment]
oh, it's _json_ size, okay. nice.

**Review by sffc — COMMENTED** [review]
Lgtm

**Pull request merged**
