### PR TITLE
Neo datagen: Refactor code from closure to function

### PR DESCRIPTION
**Pull request by sffc**
Slightly nicer to read and format. No logic changes; there were going to be but I backed them out.

### CODE REVIEW

**Review by robertbastian — COMMENTED** [review]
I don't agree that this is nicer to read, because now the logic for loading the two markers is not in the impl for those markers anymore. I'd prefer nesting these functions in the `load` methods, but at that point they can just be anonymous functions (I'm not saying closures because they don't capture anything).

**Comment by Manishearth** [comment]
I'm in favor of splitting this so that individual functions are not so many loc. I'm okay with the logic being moved out of the impl, especially if the functions are nicely documented.

**Comment by sffc** [comment]
Code in macros should be avoided, and this moves code from being in a macro to being in a helper function. It wasn't my intent that this would be a controversial change.

**Comment by Manishearth** [comment]
Oh, _especially_ in favor of code in macros to be removed from macros.

**Review by Manishearth — APPROVED** [review]

**Comment by sffc** [comment]
Well to be more precise, `gen_date_components` was in a macro.

**Pull request merged**
