### PR TITLE
DTF options::length::Bag constructor from two options

### PR DESCRIPTION
**Pull request by zbraniecki**
The current `options::length::Bag::from_date_time_style` currently requires both date and time lengths to be `Some`.

This is because we use `Option<Length>` rather than having `Length::None` variant. I chose the former because it allows the user to leverage all of the features that Rust provides for `Option` which otherwise would be lost or had to be reimplemented on `Length`.

But the downside is that it makes the APIs that accept `Length` a bit quirky. You can pass any length to it, except of `None`. If the value of your date/time length is `None` then you have to use different API.

I believe that instead, the API should accept `Option<Length>` therefore allowing for the value of `bag.date` and `bag.time` to be passed to a new bag as needed.

My argument is that most scenarios where the value is not provided by hand, it is provided as a variable and the type of that variable will be `Option<Length>` not `Length`.

### CODE REVIEW

**Comment by zbraniecki** [comment]
This change has negative impact on doc examples, but I believe it improves the developer experience of using the APIs.

Alternative way to improve the DX without impacting the doc examples readability would be to introduce `Length::None`. The cost then is that operating on that `enum` would not leverage any of the ergonomics of `Option`.

**Review by sffc — CHANGES_REQUESTED** [review]
I'm not sold on changing the existing functions. We could possibly add a `from_optional_date_time_style` with this behavior.

**Comment by zbraniecki** [comment]
> I'm not sold on changing the existing functions

This is a statement of preference - can you provide justification too?

> We could possibly add a from_optional_date_time_style with this behavior.

I think it would pollute API surface unnecessarily. I'd prefer to avoid that and if this change is not adopted would prefer people to jump over the hurdle than to have two very similar APIs.

To add to my reasoning, I expect this API to have two use case scenarios: 1) value inlined, 2) value from some store.

In the former, current behavior is better because developer makes conscious decision which API to use (`from_date_time_style`, `from_date_style`, or `from_time_style`) based on which value they want to provide, and which is set to `None`. The only challenge comes when that decision changes.

But when taking value from somewhere else, the code that the developer has to write now is something like this:

```rust
let new_bag = if let Some(d) = bag.date_length {
  Bag::from_date_time_style(d, time_length)
} else {
  Bag::from_time_style(time_length)
};
```

which is a DX papercut and it scales in complexity if both are variables.

**Comment by zbraniecki** [comment]
Following your suggestion, I just replaced:

```rust
let options = length::Bag::from_date_time_styles(
  convert_date_length(date_length),
  convert_time_length(time_length),
);
```

```rust
let mut options = length::Bag::default();
if let Some(v) = convert_date_length(date_length) {
    options.date = Some(v);
}
if let Some(v) = convert_time_length(time_length) {
    options.time = Some(v);
}
```

I see it as a DX regression.

**Comment by zbraniecki** [comment]
Ah, not just that, my code above is actually faulty - I need to reset `date` and/or `time` to None because by default they're set to `Medium`. That makes the papercut more painful.

**Comment by sffc** [comment]
Good point about them being `Medium`. We should have `::new()` or `::empty()` to help with that.

But, can't you write

```rust
let mut options = length::Bag::default();
options.date = convert_date_length(date_length);
options.time = convert_time_length(time_length);
```

**Comment by zbraniecki** [comment]
> But, can't you write

That's what I meant by "solution is simpler, but papercut more severe". I generally feel that for types that are enums with `None` variant that we handle via `Option<Enum>` we should always produce and accept the full `Option<Enum>` and I'd like to encode it in our style guide.

**Comment by sffc** [comment]
Okay, I see where you're coming from more now.

Two things I think I'm still not aligned on:

1. I don't see the papercut in what I proposed. That's the standard way to construct ICU4X options bags until non-exhaustive struct initialization is stabilitized. Any constructors on options bags are there for convenience only.
2. The three constructors in question are specifically designed for the "hard coded from developer" use case. They result in clean, readable call sites: `Bag::from_date_style(DateLength::Long)`, or `Bag::from_date_time_style(DateLength::Long, TimeLength::Short)`. The options are simply not optional; the very name of the function indicates that.
3. While I am sympathetic to the idea that "we should always produce and accept the full Option", I don't think this applies to convenience constructors. The convenience constructors say, "hey, this is what I know I have, and I want the rest to be defaulted."

**Comment by zbraniecki** [comment]
I think the question is ontological.

> "hey, this is what I know I have"

Is what I have possibly a `Length::None`? Or do I have to, as a user of the lib, to *know* if I have `Length::Short`, `Length::Medium` or `Length::None` and in the last case branch off?

My argument is that the difference between enum with variant `None` and `Option<Enum>` without it, is basically a matter of convenience of using `Option` APIs. I like this convenience, so that's how I implemented it.

But the consequence is that now we start basically handling something that in TypeScript would be `arg: Omit<Length, ["None"]>` - you can pass any `Length` except of `Length::None`. I struggle with that.

I see the other point of view tho - on the same ontological level, you shouldn't need to pass `None` and if we can have a constructor that takes the options, then I subscribe to Shane's point that those methods are for inline setting only.

But currently, we don't have a good solution for a scenario where the developer has two variables of types `Option<length::Date>` and `Option<length::Time>` and I want to construct a bag from them.

We could wait for:

```rust
let bag = length::Bag {
    time: time_var,
    date: date_var
    ..Default::default()
};
```

but it's not super pretty and it is not available.

Maybe we could do `impl From<(Option<length::Date>, Option<length::Time>)> for length::Bag` ? That would handle my use case gracefully and extend well.

**Comment by sffc** [comment]
> I think the question is ontological.
> 
> > "hey, this is what I know I have"
> 
> Is what I have possibly a `Length::None`? Or do I have to, as a user of the lib, to _know_ if I have `Length::Short`, `Length::Medium` or `Length::None` and in the last case branch off?

But `Length::None` means you don't have a length! It's in a completely different class than the others: it enables or disables the entire date or time component of the format, which is a huge deal. It's not like "skip ignorables in collation" or "grouping strategy in decimal format" which are reasonably set to their default value and are truly optional.

> My argument is that the difference between enum with variant `None` and `Option<Enum>` without it, is basically a matter of convenience of using `Option` APIs. I like this convenience, so that's how I implemented it.

I'm not opposed to using `Option` in options bags.

> But the consequence is that now we start basically handling something that in TypeScript would be `arg: Omit<Length, ["None"]>` - you can pass any `Length` except of `Length::None`. I struggle with that.

I don't get it. In TypeScript the convenience constructors should require all arguments to be present.

> But currently, we don't have a good solution for a scenario where the developer has two variables of types `Option<length::Date>` and `Option<length::Time>` and I want to construct a bag from them.

But we do! It's `let mut options = Default::default()`. I still don't understand what's wrong with that. It's literally how ICU4X options bags have worked nearly since conception.

> We could wait for:
> 
> ```rust
> let bag = length::Bag {
>     time: time_var,
>     date: date_var
>     ..Default::default()
> };
> ```
> 
> but it's not super pretty and it is not available.

I'm very much looking forward to the time when this works. I understand that there is progress being made; I was hoping to have it for ICU4X 1.0 but alas, it's not in yet.

I don't know what you mean by "it's not super pretty". This is fully semantically correct and it looks a lot like named args in Python and JavaScript.

> Maybe we could do `impl From<(Option<length::Date>, Option<length::Time>)> for length::Bag` ? That would handle my use case gracefully and extend well.

If you added such an impl I would not block it.

**Comment by zbraniecki** [comment]
Replaced by #2660.

**Pull request closed without merging**
