### PR TITLE
Using workspace inheritance for metadata and local dependencies

### PR DESCRIPTION
**Pull request by robertbastian**
Should make releases easier

### CODE REVIEW

**Comment by robertbastian** [comment]
Broken because `cargo-readmes` cannot handle the `Cargo.toml`s. That crate has been unmaintained since 2019 and it's not the first issue we're having with it. We should migrate off it or fork.

**Comment by Manishearth** [comment]
I think at some point I'd noticed a newer tool that did the same thing

**Review by sffc — COMMENTED** [review]
Seems good but we can't merge it unless there's a cargo-readmes fix.

This just saves us like 10 minutes and some opportunity for human error at release time, right?

**Comment by Manishearth** [comment]
> This just saves us like 10 minutes and some opportunity for human error at release time, right?

Less opportunity for human error in general, too, we can homogenize how we do deps better

**Review by Manishearth — APPROVED** [review]

**Pull request merged**
