### PR TITLE
Update Rust edition to 2021

### PR DESCRIPTION
**Pull request by zbraniecki**
Rust 1.67 clippy introduces a lint that checks for inlined format args - https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args

This lint is imperfect and fails for `static_debug!` and `panic! macros which cannot inline format args until edition 2021.

Instead of excepting those cases, I think it is easier to bump our editions to 2021 as a hygiene step.

### CODE REVIEW

**Comment by robertbastian** [comment]
Did you run [`cargo fix --edition`](https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html)? I'd expect there to be some changes around array iterators. 

I'm all for this change, but the lint you mention is allow-by-default. Does it actually trigger on 1.67?

**Comment by Manishearth** [comment]
Yes, clippy downgraded it to allow by default because rust-analyzer doesn't like the inline format args syntax.

But it's still warn on stable

**Comment by robertbastian** [comment]
> But it's still warn on stable

We could allow it in our clippy invocation until allow-by-default lands on stable.

**Review by robertbastian — APPROVED** [review]

**Comment by Manishearth** [comment]
.... and just today we got approved to uplift it into a patch release that's going to be happening anyway, neat

**Review by Manishearth — APPROVED** [review]

**Pull request merged**
