### PR TITLE
Little `#[doc(hidden)]` restructure

### PR DESCRIPTION
**Pull request by robertbastian**

### CODE REVIEW

**Review by sffc — COMMENTED** [review]
I'm not sure this is an improvement, but I'm fine with it if @Manishearth agrees

**Comment by Manishearth** [comment]
What's the motivation here? I kind of liked _internal

**Comment by robertbastian** [comment]
All of these things are internal for different reasons: fallback because its canonical location is in `icu_locale`, `icu_locale_core` because nobody has put it in the prelude yet, and `log` idk why, I think it should be non-hidden. Having an `_internal` module lumps them all together and I find that confusing.

**Review by Manishearth — APPROVED** [review]
Yeah that seems reasonable

**Pull request merged**
