### PR TITLE
Fill the binary prefixes of the units essential data

### PR DESCRIPTION
**Pull request by younies**
Fill the binary prefixes of the units essential data

fix the merge

---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/unicode-org/icu4x/pull/5155).
* __->__ #5155
* #5154

### CODE REVIEW

**Review by robertbastian — CHANGES_REQUESTED** [review]
Please hook up baked data so we can see fingerprint diffs

**Comment by younies** [comment]
> Please hook up baked data so we can see fingerprint diffs

I would like to hook the bakeddata after filling all the prefixes in this PR: #5157

**Comment by robertbastian** [comment]
Is there a blocker for doing it now? I'd like to see fingerprints diffs.

**Review by sffc — COMMENTED** [review]
Seems right; defer to @robertbastian on detailed review. Do not re-request review from @sffc unless the architecture changes.

**Comment by younies** [comment]
Move all the logic to this PR: https://github.com/unicode-org/icu4x/pull/5157

**Pull request closed without merging**
