### PR TITLE
Add unicode_ext_value! macro, enabled by new helper ShortVec

### PR DESCRIPTION
**Pull request by sffc**
This PR introduces `ShortVec`, an internal class to `icu_locid`, which looks like this:

```rust
/// Internal: A vector that supports no-allocation, constant values if length 0 or 1.
pub(crate) enum ShortVec<T> {
    Empty,
    Single(T),
    Multi(Vec<T>),
}
```

With this type, I can swap out the internals of `Value` to use `ShortVec`, and then, with a little bit of gymnastics due to https://github.com/rust-lang/rust/issues/73255, I can get `unicode_ext_value!` to work:

```rust
const CALENDAR_KEY: Key = unicode_ext_key!("ca");
const CALENDAR_VALUE: Value = unicode_ext_value!("buddhist");
```

If you like this direction, we could:

1. Keep it to just `Value` in Unicode and Transform
2. Change all `Vec` to `ShortVec`

If we did (2), then, with some gymnastics, we could actually make the following compile, which seems cool:

```rust
// Potential future if ShortVec is used everywhere
const LOCALE: Locale = locale!("en-Latn-US-macos-u-ca-buddhist-t-hi-h0-hybrid");
```

However, this is a little further off, because it would require replacing `LiteMap` again, or changing `LiteMap` itself to use `ShortVec`. I lean against this generalization for the time being since it is generally expected that there are multiple Unicode extension keywords, whereas with the values, they are often only one subtag long.

We actually could already do `locale!("en-t-hi")` without changing anything in the data model.

### CODE REVIEW

**Comment by sffc** [comment]
Note: Code size changes from `32072` to `32088`. Seems like a worthwhile tradeoff.

**Comment by zbraniecki** [comment]
How generic you want this new type to be? If it is intended for subtags only, maybe `SubtagList` for a name?

**Review by zbraniecki — APPROVED** [review]
lgtm

**Comment by sffc** [comment]
> How generic you want this new type to be? If it is intended for subtags only, maybe `SubtagList` for a name?

I don't want to take on the responsibility of exporting this type to be super generic, but I want it to be a bit more general than just `SubtagList`. I'm not far from making it be the LiteMap backend, for example.

**Comment by sffc** [comment]
Oops, I hit the merge button before @robertbastian reviewed :disappointed: Let me know if you have any feedback and I'll open a new PR for you.

**Comment by robertbastian** [comment]
lgtm

**Pull request merged**
