### PR TITLE
Fix cargo clippy warnings in data provider code

### PR DESCRIPTION
**Pull request by sffc**
Wait until #160 is ready before merging this one.

### CODE REVIEW

**Comment by zbraniecki** [comment]
In callers, instead of including `FromStr`, you can just do `x.parse()`

**Comment by sffc** [comment]
Thanks. The problem with .parse is that the computer often doesn't have enough information to infer the type. I find FromStr clearer when the primary goal is constructing an object.

```rust
let a: A = "foo".parse();
let a = A::from_str("foo");
```

What level is your comment? If your comment is optional, I'd rather leave it as-is. If your comment is suggestion or required, I'll take your advice and change it.

**Comment by zbraniecki** [comment]
>  The problem with .parse is that the compiler often doesn't have enough information to infer the type. I find FromStr clearer when the primary goal is constructing an object.

In my experience that's actually a good thing. It basically means that if the context is strong enough (for example, you're passing the `foo.parse()` to a function that accepts the target, then you can skip the annotation.
Otherwise, you need to annotate either via `Target::from_str` or via `let x: Target = foo.parse()`. Both are totally ok.

In result, I'm quite flexibly using both in my experience but found myself using `parse` more often :)

> What level is your comment? If your comment is optional, I'd rather leave it as-is. If your comment is suggestion or required, I'll take your advice and change it.

Suggestion, optional. Feel free to use `from_str`. It's correct, understood by users and there's no problem with it.
My guess is that as we polish the APIs more, we'll end up using `parse` more, but not exclusively.

**Comment by sffc** [comment]
I fixed the additional warnings uncovered by `cargo clippy --all-targets --all-features`

**Comment by echeran** [comment]
Don't forget the `-- -D warnings` part of the command.  And the `cargo clean && ` part ensures that the error code is non-zero on warnings (matters more for CI than for local testing).  With `cargo clean && cargo clippy --all-targets --all-features -- -D warnings`, which is currently what #161 is set up with, I still get one last little thing:

```
error: this import is redundant
 --> components/data-provider-json/tests/test_file_io.rs:1:1
  |
1 | use icu_data_provider_json;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove it entirely
  |
  = note: `-D clippy::single-component-path-imports` implied by `-D warnings`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#single_component_path_imports

error: aborting due to previous error

error: could not compile `icu-data-provider-json`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by sffc** [comment]
Odd, because I don't get that warning on my computer.

```
omnicu$ cargo clean && cargo clippy --all-targets --all-features -- -D warnings
   Compiling autocfg v1.0.0
   Compiling proc-macro2 v1.0.18
...
    Finished dev [unoptimized + debuginfo] target(s) in 29.54s
omnicu$ cargo clippy --all-targets --all-features -- -D warnings
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
omnicu$ cargo --version
cargo 1.42.0 (86334295e 2020-01-31)
omnicu$
```

**Comment by sffc** [comment]
OK, I ran `rustup update` and now I'm able to reproduce the warning.  Pushed a fix.

**Comment by sffc** [comment]
@zbraniecki @nciric I need at least one approval from a code owner

**Pull request merged**
