### PR TITLE
Fix ci-job-testdata

### PR DESCRIPTION
**Pull request by sffc**
Conflict between https://github.com/unicode-org/icu4x/pull/3669 and #3714

### CODE REVIEW

**Comment by sffc** [comment]
Gonna force-merge this since it is a 0-line change and CI is passing.

**Review by robertbastian — COMMENTED** [review]
Weird, how did that even merge

Edit: ah

**Comment by sffc** [comment]
> Weird, how did that even merge
> 
> Edit: ah

Yeah you can consider this a red TBR (to-be-reviewed) submission in need of a post-submit LGTM. Fixing main CI is one of the few things I think we can agree rises to the level of a TBR.

**Comment by robertbastian** [comment]
I meant my PR, I understand why you force-merged this :)

**Pull request merged**
