### PR TITLE
Add CI job to add docs to Github pages

### LINKED ISSUE #111: Add docs to GitHub pages

### PR DESCRIPTION
**Pull request by echeran**
Closes #111

### CODE REVIEW

**Comment by sffc** [comment]
Cool!

Are the docs posted yet for preview?

Why does it say "this check was skipped"?

**Comment by echeran** [comment]
I forgot to mention that.  The URL is: https://unicode-org.github.io/icu4x-docs/

It says the check was skipped b/c it only runs on `master`, not PRs,.  I mentioned over in the issue that PRs (which are WIP) shouldn't be allowed to clobber the latest version of our docs based on our code from master, which has passed review.

**Comment by sffc** [comment]
Why does https://unicode-org.github.io/icu4x-docs/icu4x/ show all of our dependencies as crates?  Is there a way to fix that?

**Comment by filmil** [comment]
> Why does https://unicode-org.github.io/icu4x-docs/icu4x/ show all of our dependencies as crates? Is there a way to fix that?

Looks like cargo is able to omit dependencies if specifically asked to do so: 
https://stackoverflow.com/questions/34215411/how-do-i-prevent-rust-doc-from-adding-dependencies-to-documentation

**Comment by echeran** [comment]
Yep, thanks for the link.  The new commit adds the `--no-deps` arg.  A [test on my personal fork](https://github.com/echeran/icu4x/runs/876252737?check_suite_focus=true) shows the cleaned up docs in the docs repo at https://echeran.github.io/icu4x-docs/.

**Comment by echeran** [comment]
I initially considered a separate workflow, but then I confirmed the fact that workflows cannot depend on each other.  Only jobs within a workflow can depend on each other.  And I don't want the docs to be generated if the code doesn't build / tests don't pass.

And since formatting is quicker thing to check than doc generation but is required for all commits, I also made that a dependency of docs too so that we don't generate docs needlessly when formatting needs cleanup.  (I guess docs are generated from parts of code that adhere to a certain format, so that docs generation job dep on formatting should make sense for that reason, too.)

**Pull request merged**
