### PR TITLE
Use cargo-all-features for all feature sets (incl. no features)

### LINKED ISSUE #63: Running tests with different feature sets / architectures
We should think about how we test different feature sets and architectures.  By default, `cargo test` only tests your default architecture and the crate's default features.

Examples of things we want to test:

- `std` vs. `no_std` environment (by enabling or disabling the `std` feature)
- Building for the wasm32_unknown_unknown architecture
- Building on non-Linux, non-x86 architectures like Windows, macOS, ARM

Note: https://github.com/rust-lang/cargo/issues/2911 is a feature request to allow integration tests to choose different feature sets.

### PR DESCRIPTION
**Pull request by echeran**
Summary:
* Using `cargo-all-features` appears to build and test against all subsets of features (including no features) as expected
* The build step (`cargo build-all-features`) ends early with an error
* The test step (`cargo test-all-features`), when run locally, shows some of the combinations in its output
* The reported errors may not be the exhaustive list, since the process exits early on error
* [example workflow run](https://github.com/echeran/icu4x/runs/848285822?check_suite_focus=true)

Fixes #63 

Selected lines from build run:
```
    Building crate=icu-data-provider features=[]

error[E0432]: unresolved import `std::error`
  --> components/data-provider/src/lib.rs:16:10
   |
16 | use std::error::Error;
   |          ^^^^^ help: a similar path exists: `downcast_rs::std::error`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `icu-data-provider`.
```

Selected lines from test run:
```
     Testing crate=icu4x features=[]

     Testing crate=icu-data-provider-json features=[]

     Testing crate=icu-data-provider-json features=[std]

     Testing crate=icu features=[]

     Testing crate=icu-data-provider features=[]

error[E0432]: unresolved import `std::error`
  --> components/data-provider/src/lib.rs:16:10
   |
16 | use std::error::Error;
   |          ^^^^^ help: a similar path exists: `downcast_rs::std::error`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `icu-data-provider`.
```

### CODE REVIEW

**Review by zbraniecki — DISMISSED** [review]

**Comment by sffc** [comment]
I know what I need to do to fix that error.  I'll reproduce it locally and then open a PR.

**Comment by sffc** [comment]
I think this CI should start working once #198 is checked in.

**Comment by sffc** [comment]
@echeran Can you rebase this PR and see if it passes now?

**Comment by echeran** [comment]
The previous error is gone, but we have a [different error](https://github.com/unicode-org/icu4x/pull/172/checks?check_run_id=1067514383#step:7:111) now:

```
    Building crate=icu-pluralrules features=[serde]
...
error[E0433]: failed to resolve: use of undeclared type or module `tuple_vec_map`
  --> components\pluralrules\src\data\cldr_resource.rs:43:38
   |
43 | #[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
   |                                      ^^^^^^^^^ use of undeclared type or module `tuple_vec_map`

error[E0433]: failed to resolve: use of undeclared type or module `tuple_vec_map`
```

**Comment by sffc** [comment]
@echeran Is there a way to make the builds a little faster?  The builds took 20m, 16m, and 24m.  For example, can we do like before and make two different build jobs, one that finishes fast with the default feature set, and the other that takes longer with the comprehensive feature set?

**Comment by echeran** [comment]
I filed https://github.com/frewsxcv/cargo-all-features/issues/7 in the cargo plugin repo to ask:

- does the cargo plugin work well with parallelism of cargo jobs?
- is there something that the plugin could do ("dry run mode") to give us the commands for the jobs that it runs serially so that we can run those jobs concurrently?

**Comment by sffc** [comment]
Idea: Do the all-features thing only for building, not testing.  I think most problems will arise during building, e.g., by not having the right symbols available.  If code builds with a subset of features and passes tests with all features, I think there is a very good chance it passes with the subset of features.

Please wait for my PR fixing #334 and then rebase.  Thanks!

**Comment by sffc** [comment]
I went ahead and integrated this PR into #376.

Also see https://github.com/frewsxcv/cargo-all-features/pull/8

**Pull request closed without merging**
