### PR TITLE
1.3.2 branch

### PR DESCRIPTION
**Pull request by robertbastian**

### CODE REVIEW

**Comment by Manishearth** [comment]
The parent commit here is https://github.com/unicode-org/icu4x/commit/713c90eeab59279c90c6f74df3096ef7bb9e6e67

**Comment by Manishearth** [comment]
Wait, no, not r=me, we should include the doc patches

**Comment by robertbastian** [comment]
cherry-picked

**Comment by Manishearth** [comment]
ty. r=me, will start publishing.

crates to publish:
 - tinystr
 - all components/provider/experimental components
 - datagen/capi

**Comment by robertbastian** [comment]
You should just do `cargo ws publish --from-git`. I've bumped the global version, so we should release all crates that use that.

Also testdata

**Comment by Manishearth** [comment]
I still don't trust magical tools that publish everything for you, especially if we need to wait with a manual step.

Also I wanted to parallelize, which I've been succeeding at.

**Comment by Manishearth** [comment]
Everything except datagen and testdata is released and tagged. @robertbastian what should I do for testdata?

**Comment by Manishearth** [comment]
I guess I just run `testdata-legacy` and then publish testdata

**Comment by Manishearth** [comment]
Let's leave this PR open and unmerged and merge a separate PR that contains your 132 commit onto main so that main reflects the correct versions

**Comment by robertbastian** [comment]
The 132 commit conflicts with main

**Comment by Manishearth** [comment]
All published

**Comment by Manishearth** [comment]
4108

**Pull request closed without merging**
