### PR TITLE
Move collator and normalizer from experimental to components

### PR DESCRIPTION
**Pull request by hsivonen**

### CODE REVIEW

**Comment by hsivonen** [comment]
Depends on #2087 to have all the TOML files is the zip exported from ICU4C.

**Comment by hsivonen** [comment]
[Unicode 15 zip file from ICU4C CI.](https://dev.azure.com/ms/icu/_build/results?buildId=323153&view=artifacts&pathAsName=false&type=publishedArtifacts)

**Comment by hsivonen** [comment]
[Unicode 14 zip from ICU4C CI](https://dev.azure.com/ms/icu/_build/results?buildId=323174&view=artifacts&pathAsName=false&type=publishedArtifacts)

**Comment by sffc** [comment]
Going to refresh the CI

**Review by sffc — APPROVED** [review]
Looks good!

**Comment by hsivonen** [comment]
Thanks.

**Pull request merged**
