### PR TITLE
Add Finnish to testdata

### PR DESCRIPTION
**Pull request by sffc**
In https://github.com/unicode-org/icu4x/pull/5357 I was looking for locales that have differences between the "format" and "standalone" datetime names, and none of the test locales did. So, I would like to add Finnish, which, in addition to having this data, also has overrides for segmentation and collation rules.

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Review by robertbastian — CHANGES_REQUESTED** [review]
This has a significant cost of adding 35k loc to the repo and bloating our test locales even further (they were originally meant to be 10 locales, we're already above that). What are you achieving here? There doesn't seem to be a unit test that uses this data in `icu_provider_core`, and `icu_datetime` uses baked data for testing. So this is only in order to see a JSON diff?

**Comment by sffc** [comment]
I routinely use testdata to check invariants of things I'm working on, and there are no testdata locales that would trigger a special case that might come up in https://github.com/unicode-org/icu4x/pull/5357 when standalone and format names differ.

I was considering removing a locale when I added this one.

**Comment by robertbastian** [comment]
> I routinely use testdata to check datagen invariants of things I'm working on

You can write tests for these invariants. Tests can use source data for any locale.

**Comment by Manishearth** [comment]
Should we potentially work on laser-focusing more of these locales towards keys that we actually care about the invariants for?

**Comment by sffc** [comment]
Thought: we could make a hybrid crate compatible API-wise with `ICU4X_DATA_DIR` that uses the JSON files during testing, and then try to make most or all ICU4X docs tests run with that test data, as they did in the past.

I'd be in favor of focusing the testdata locales to be for specific components. It would reduce the number of JSON files which is nice.

**Comment by robertbastian** [comment]
Thought: If you just need this for local iteration, I'm happy to add the locale but gitignore the files.

**Comment by sffc** [comment]
I don't need this any more in the short term. I filed #5420 for a follow-up.

**Pull request closed without merging**
