### PR TITLE
Isolating `icu_datagen::DatagenProvider` from the rest of the crate

### PR DESCRIPTION
**Pull request by robertbastian**
The current module structure of `transform::{cldr, icuexport, segementer}` doesn't make sense, things in CLDR use ICU data, segmenter uses ICU data, etc. I've flattened these into a `provider` module which does not depend on anything anywhere else in the crate. This can be split out in the future #4721

### CODE REVIEW

**Review by sffc — COMMENTED** [review]
I agree that this is a better organization, although I thought we were done moving files around and I would have liked to discuss this first.

Not sure about renaming `transform` because the term `provider` is used in so many other places and it's nice that `transform` uniquely refers to code in the DatagenProvider.

It will be nice for DatagenDriver to be a new low-external-dependency crate that could pull from a blob.

I'm okay landing this but would like another LGTM on the direction.

**Comment by Manishearth** [comment]
I am in favor, and slightly in favor of @sffc's `transform` suggestion

**Review by sffc — CHANGES_REQUESTED** [review]
Actually, I really want to minimize rename disruptions. Merging this PR is going to cause merge conflicts in a time when we have a lot of first-time contributors due to GSoC and are getting ready for the 2.0 release. Furthermore, these new names are only temporary, since we will probably be moving these files again later. Please do the refactoring without doing big file renames. We can do the renames, _to their final destinations_, when we actually split the crate.

**Comment by robertbastian** [comment]
I feel like this restriction is at odds with the plan to do all work in a semver compatible way for 1.5, and do no actual work for 2.0

**Pull request closed without merging**
