### PR TITLE
Adding all baked data crates

### PR DESCRIPTION
**Pull request by robertbastian**
I will have separate PRs for each component's baked API, but the data part is not very interesting, and doing it in the component PRs will give merge conflicts in `data.toml` all the time.

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
They probably need to be in the workspace for things to work.

Also, once these exist do we even need to keep the baked testdata around? We can have it be a shim over the rest of these crates.

(Unless we want "test" data to ever not just be a subset of "global" data)

**Comment by robertbastian** [comment]
Locally no, but we don't want the published testdata to pull in all the baked crates...if testdata even has a future.

There are also some tests that expect a certain locale *not* to be in testdata.

**Comment by robertbastian** [comment]
Also surprisingly they don't need to be in the workspace...

**Comment by robertbastian** [comment]
Open question whether we want the full-data CI to become required now. It's 30+ minutes, so would be annoying.

What we could also do is reduce the set of locales and only bump it up for releases. Or we could use the environment variable to point at baked testdata and only update baked data for releases.

**Comment by Manishearth** [comment]
I'm fine with not requiring it and running it on cronjob CI, perhaps. I don't think data changes that often for _existing_ crates, and a lot of the kinds of changes one may make to data would lead to some other test failure anyway.

**Pull request merged**
