### PR TITLE
Use SmallString for the data provider struct.

### LINKED ISSUE #113: What string type should we use for short UTF-8 strings?
We commonly need to handle short UTF-8 strings that are longer than one code point.  For example, a lot of CLDR data may be one grapheme cluster long, or may be one code point plus a bidi control character.

@zbraniecki compiled a great list of some options:

https://github.com/zbraniecki/tinystr/wiki/Performance

Here are the options in that doc, along with my initial thoughts on their pros and cons.

- [SmolStr](https://github.com/rust-analyzer/smol_str)
  - 29 stars on GitHub
  - Pro: `size_of::<SmolStr>() == size_of::<String>()`
  - Pro: Serde integration
  - Pro: No dependencies except for the Serde traits
  - Con: Doesn't support `#![no_std]`
  - Con: No mutable functions
- [smallstr](https://github.com/murarth/smallstr)
  - 6 stars on GitHub
  - Pro: FFI integration
  - Pro: Serde integration
  - Pro: Good documentation
  - Pro: `#![no_std]` (uses `alloc`)
  - Con: Only 6 stars; owner's affiliation unclear
- [ArrayString](https://github.com/bluss/arrayvec)
  - 255 stars on GitHub
  - Pro: Serde integration
  - Pro: Good documentation
  - Pro: `#![no_std]` (no dependence on `alloc`)
  - Pro: Lots of stars and contributors
  - Pro: Comes with other non-String stack vectors that we could leverage
  - Pro: No dependencies except for the Serde traits
  - Con: Does not support overflow onto heap, which may be necessary since grapheme clusters are not bounded by length
- [istring](https://gitlab.com/sebk/istring)
  - No stars on GitLab
  - Pro: `#![no_std]` (uses `alloc`)
  - Con: Only one contributor, and no activity since 2018
  - Con: Not much documentation

Thoughts? @Manishearth @hsivonen 

The doc also lists "istring", but I can't find it on GitHub.  Pointers?

### PR DESCRIPTION
**Pull request by sffc**
Fixes #113

### CODE REVIEW

**Comment by zbraniecki** [comment]
Should we consider `Cow` over `SmallString`?

`Cow` allows us to elegantly handle owned vs. borrowed data, `SmallString` if I'm not mistaken is always owned, just on a heap or stack.

if I'm not mistaken, with this patch we're losing ability to have `SymbolsV1` be borrowed from some pre-allocated String, or static.

Should we try to get some form of `Cow<&SmallString>`?

**Comment by sffc** [comment]
My thinking was that since the string is short, we could use straight-up SmallString. When there's just one or two characters, it seems like a lot of layers of redirection to use Cow. We have to copy a few bytes to initialize the SmallString, but then from that point forward, we own the data and things are simpler.

**Comment by zbraniecki** [comment]
I see. It would be worth benchmarking, but generally, right I don't expect it to be worth for a couple two-char strings.

Where I think it will start mattering is if we'll have 500 two-char strings or when we'll have 2 500 char strings. Is that something you don't expect to see in the provider?
I imagine some PluralRules may be long etc.

**Comment by sffc** [comment]
I updated the recommendation to suggest SmallString when 99% of strings are 20 chars or shorter, and Cow when strings are longer.

**Comment by sffc** [comment]
One more tweak.  PTAL

**Pull request merged**
