### PR TITLE
Implementing Writeable across ICU4X components

### LINKED ISSUE #440: Plug Writeable trait into other components

### LINKED ISSUE #449: Writeable: how to parameterize fmt::Write?
The definition of Writeable is currently

```rust
// Option 1 (status quo)
pub trait Writeable {
    fn write_to(&self, sink: &mut dyn fmt::Write) -> fmt::Result;
    fn write_len(&self) -> usize;
}
```

This impl forces the `fmt::Write` to be a trait object.  I've learned since writing this definition that it is [slightly](https://github.com/unicode-org/icu4x/pull/431#issuecomment-750780808) faster if the compiler can skip the dynamic dispatch and call the method directly.

Here are some other options:

```rust
// Option 2
pub trait Writeable {
    fn write_to<W: fmt::Write + ?Sized>(&self, sink: &mut W) -> fmt::Result;
    fn write_len(&self) -> usize;
}

// Option 3
pub trait Writeable<W: fmt::Write + ?Sized> {
    fn write_to(&self, sink: &mut W) -> fmt::Result;
    fn write_len(&self) -> usize;
}

// Option 4
pub trait Writeable {
    type W: fmt::Write + ?Sized;
    fn write_to(&self, sink: &mut W) -> fmt::Result;
    fn write_len(&self) -> usize;
}

// Option 5
pub trait Writeable {
    fn write_to(&self, sink: &mut dyn fmt::Write) -> fmt::Result;
    fn write_to_object<W: fmt::Write + ?Sized>(&self, sink: &mut W) -> fmt::Result where Self: Sized;
    fn write_len(&self) -> usize;
}
```

Option 2 seems to make sense, but it prevents the Writeable from being itself used as a trait object.  Option 3 may work, and the trait object version would be `Writeable<dyn fmt::Write>`.  I don't really understand when to use associated types, so I don't know if Option 4 is appropriate or not.

Thoughts?  @Manishearth @zbraniecki

### PR DESCRIPTION
**Pull request by sffc**
Fixes #440
Fixes #449

### CODE REVIEW

**Comment by sffc** [comment]
Benchmarks in the locid crate:

```
langid/to_string/langid time:   [1.3481 us 1.3653 us 1.3881 us]                                     
                        change: [-10.664% -6.3290% -1.0991%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
  2 (2.00%) high mild
  7 (7.00%) high severe

langid/to_string/locale time:   [1.2272 us 1.2319 us 1.2375 us]                                     
                        change: [+2.4398% +4.0988% +5.9002%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 13 outliers among 100 measurements (13.00%)
  6 (6.00%) high mild
  7 (7.00%) high severe

locale/to_string/locale time:   [1.2658 us 1.2751 us 1.2862 us]                                     
                        change: [-32.643% -31.212% -29.211%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 7 outliers among 100 measurements (7.00%)
  3 (3.00%) high mild
  4 (4.00%) high severe
```

**Comment by sffc** [comment]
FixedDecimal benches:

```
to_string/to_string/22.50                                                                            
                        time:   [62.159 ns 62.447 ns 62.754 ns]
                        change: [-2.0332% -1.1761% +0.2054%] (p = 0.02 < 0.05)
                        Change within noise threshold.
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) high mild
  2 (2.00%) high severe
to_string/to_string/908070605040302010                                                                            
                        time:   [236.99 ns 240.34 ns 245.01 ns]
                        change: [+15.063% +18.050% +20.835%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 9 outliers among 100 measurements (9.00%)
  2 (2.00%) low mild
  1 (1.00%) high mild
  6 (6.00%) high severe

to_string/write_to/22.50                                                                             
                        time:   [38.443 ns 38.587 ns 38.728 ns]
                        change: [-7.9571% -7.5258% -7.1114%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) high mild
to_string/write_to/908070605040302010                                                                            
                        time:   [114.69 ns 115.02 ns 115.40 ns]
                        change: [-19.708% -19.331% -18.951%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 10 outliers among 100 measurements (10.00%)
  7 (7.00%) high mild
  3 (3.00%) high severe
```

**Comment by sffc** [comment]
Okay, this is ready for review.  I migrated all of the implementations of std::fmt::Display over to Writeable.  The largest chunk of changes is in the locid crate, but as you can see above, this still resulted in a performance improvement overall.  I added some helper macros in that crate to reduce the boilerplate.

**Review by zbraniecki — DISMISSED** [review]
I don't have any comments for the PR, but I am struggling a bit with the `Writable` now that I see it in use.

The `dyn Write` is handled in #449, so I assume that we'll get this resolved when #449 is decided.
But I'm also struggling with the use of `write_len` - it seems like almost nothing in this PR uses that, while there's a lot of code to painfully try to calculate that function.
I know you want to handle that in #370, but I'm wondering if it's worth doing the reverse of what you're doing here:

```rust
trait Writeable {
    fn write_len(&self) -> LengthHint {
        LengthHint::Unknown
    }
}
```

and then we could land this without that at all, and only add it for cases where the hint is actually useful for performance.

**Comment by sffc** [comment]
> I don't have any comments for the PR, but I am struggling a bit with the `Writable` now that I see it in use.
> 
> The `dyn Write` is handled in #449, so I assume that we'll get this resolved when #449 is decided.
> But I'm also struggling with the use of `write_len` - it seems like almost nothing in this PR uses that, while there's a lot of code to painfully try to calculate that function.

The `writeable_to_string` function uses it.  It is auto-implemented on all types implementing Writeable.

> I know you want to handle that in #370, but I'm wondering if it's worth doing the reverse of what you're doing here:
> 
> ```rust
> trait Writeable {
>     fn write_len(&self) -> LengthHint {
>         LengthHint::Unknown
>     }
> }
> ```
> 
> and then we could land this without that at all, and only add it for cases where the hint is actually useful for performance.

Understood, but this is part of how Writeable gets its performance improvement.

To demonstrate, I added a new bench function that calls `.writeable_to_string()` in order to compare it with `.to_string()`.  The performance improvement is in line with what I've previously found:

```
langid/to_string/langid
                        time:   [1.2069 us 1.2185 us 1.2315 us]                                     
                        change: [-9.7746% -8.5799% -7.4543%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) high mild
  2 (2.00%) high severe

langid/to_string/langid/writeable
                        time:   [774.57 ns 778.44 ns 783.40 ns]
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) high mild
  2 (2.00%) high severe

langid/to_string/locale
                        time:   [1.2813 us 1.2859 us 1.2914 us]                                     
                        change: [+0.0307% +0.6343% +1.3071%] (p = 0.05 < 0.05)
                        Change within noise threshold.
Found 7 outliers among 100 measurements (7.00%)
  4 (4.00%) high mild
  3 (3.00%) high severe

langid/to_string/locale/writeable
                        time:   [847.85 ns 854.14 ns 861.24 ns]
Found 4 outliers among 100 measurements (4.00%)
  3 (3.00%) high mild
  1 (1.00%) high severe

locale/to_string/locale
                        time:   [1.1793 us 1.1943 us 1.2071 us]              
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high severe

locale/to_string/locale/writeable
                        time:   [906.74 ns 913.53 ns 921.45 ns]
Found 8 outliers among 100 measurements (8.00%)
  4 (4.00%) high mild
  4 (4.00%) high severe
```

Now, of course, the performance improvement is only partly because of write_len; the rest of the improvement is thanks to using the faster fmt::Write instead of the slower fmt::Formatter.  I've previously demonstrated that write_len improves performance, but to verify, I did a little experiment here.  I replaced the write_len implementation in Locale with a function that returns `0`, effectively nullifying the benefit from calling that function to pre-allocate the string.  Here are the results I get from four runs of the benchmark:

- write_len returns correct value: 1.1635 us, 942.82 ns, 926.56 ns, 889.75 ns,
- write_len returns zero: 1.0704 us, 1.0249 us, 989.20 ns, 1.0920 us

I wish Criterion would give me a more precise metric, since you can see how much the values jump around just from running `cargo bench` several times in a row.  But, the trend does appear to be that write_len returning the correct value yields a performance improvement overall; an average of 980 ns versus 1044 ns.

**Comment by sffc** [comment]
I did the same experiment on LanguageIdentifier:

- Correct write_len: 773.61 ns (4-run average)
- Zeroed write_len: 833.88 ns (4-run average)

Do you need any more evidence that write_len leads to performance improvements? :)

**Comment by zbraniecki** [comment]
> Do you need any more evidence that write_len leads to performance improvements? :)

I never questioned the assumption. I question whether the performance improvements are critical enough to justify forcing every user of `Writeable` to have to write elaborate code to get the length estimation.

What I suggested is intended to allow lower engineering cost of implementing `Writable` for all structs, and makes `write_len` and optional performance optimization that we can write for hot code where it actually matters.

In your mode you make it mandatory for any use, and I think it raises developer friction. Unless your claim is that we should *only* use `Writeable` for cases where we care about performance enough to justify squeezing every nanosecond. But I'd be surprised if you claimed that because `Writeable` has two goals, perf and cheaper code.
I can see many uses where we'll switch to `Writeable` to keep the WASM file smaller, not because we need every last ns of performance. If that's correct, then having `write_len` be optional seems like a project maintenance win for me.

**Comment by sffc** [comment]
I want to resolve this question in #370. Since I've already written the implementation for write_len, can we check this in? Or do you feel that we should hold off on this PR until #370 is designed? (I would prefer checking this in and considering ways to simplify when we discuss #370)

**Comment by sffc** [comment]
Here's what it looks like when I make write_len return a LengthHint.

**Comment by sffc** [comment]
OK, I implemented std::ops::Add and related traits, deleting `default_capacity()`.  How's this?

**Review by zbraniecki — DISMISSED** [review]
lgtm!

**Review by zbraniecki — APPROVED** [review]

**Pull request merged**
