### PR TITLE
inline(always) trie accessors that are macros in ICU4C

### PR DESCRIPTION
**Pull request by hsivonen**
This improves particularly Greek normalization perf. The amount of code inlined is pretty small.

### CODE REVIEW

**Comment by Manishearth** [comment]
Do we get the same perf wins with just `inline` on all four functions? In general the advice is that `inline(always)` should be strongly avoided in Rust since it makes compile times worse and does not actually have as many benefits over `inline` (and almost never is faster).

**Comment by hsivonen** [comment]
> Do we get the same perf wins with just `inline` on all four functions?

No. The performance is worse that way.

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
worth explicitly mentioning that in a comment, r=me though

**Comment by hsivonen** [comment]
> worth explicitly mentioning that in a comment

Thanks. I'll open a new PR for the comment, since either way, GitHub would want re-review.

**Review by sffc — COMMENTED** [review]
How big are the improvements?

I'm not super excited about potential code size impact, since `#inline(always)` cannot be avoided even in `-Os` mode

**Comment by hsivonen** [comment]
Up to more than 6% but less than 7%.

**Pull request merged**
