### PR TITLE
Revert "Store only symbols on DateTimeFormat"

### PR DESCRIPTION
**Pull request by sffc**
Reverts unicode-org/icu4x#518

I want to see if this fixes the CI error noted in #542

### CODE REVIEW

**Comment by sffc** [comment]
@zbraniecki It appears that your PR #518 may not have caused the CI to start failing, because it still fails even if I try rolling it back.  So maybe some update to grcov or whatever caused it.

**Comment by zbraniecki** [comment]
this is sad. I have never had so many CI issues as we are having with ICU4X (but then, I never worked on such a large multi-person rust project).
I was hoping that grcov with source coverage will be the "final solution", and it's frustrating if this is the cause.

Alternatively it may be that it's some caching issue due to our github actions logic we use in which case I wish github actions supported the very basic feature that travis did - delete cache.

**Comment by sffc** [comment]
> Alternatively it may be that it's some caching issue due to our github actions logic we use in which case I wish github actions supported the very basic feature that travis did - delete cache.

I don't think it's a caching issue, because we removed all the (explicit) caching in the workflow files.

> this is sad. I have never had so many CI issues as we are having with ICU4X (but then, I never worked on such a large multi-person rust project).

You've been lucky.  I've had a much different experience with CI always being flaky, so this kind of thing isn't new to me... but I was hoping we could avoid it in a new project.

**Comment by sffc** [comment]
Superseded by #554

**Comment by gregtatum** [comment]
> this is sad. I have never had so many CI issues as we are having with ICU4X (but then, I never worked on such a large multi-person rust project).

> You've been lucky. I've had a much different experience with CI always being flaky, so this kind of thing isn't new to me... but I was hoping we could avoid it in a new project.

I've had both experiences on different projects. I found the fix was to apply concerted effort to fix areas of flakiness where they crop up, and have a culture of fast and reliable CI. I suspect pinning the Nightly version will fix most of these I've been seeing. Relying on unstable software like Nightly is really risky. I suspect pinning the release version will make us much more solid as well.

**Comment by sffc** [comment]
Yep, that's my hope as well!

**Pull request closed without merging**
