### PR TITLE
Batteries-included baked provider

### PR DESCRIPTION
**Pull request by robertbastian**
~Blocked on #3487~

Part of #3487

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
We should probably spend more time organizing the baked_exporter code, but this is also on par for syn code anyway :/

Actual changes look good. Would be kinda cool if we could speed up the repeated binary search by using the failed binary search index as a quick check first. It's a bit complicated to get right, though, so not worth doing here.

(also: _so_ glad that the baked code is formatted again; this was so much easier to review)

**Review by sffc — COMMENTED** [review]
My concerns about the batteries-included bake provider are still the same as they were on the other PR.

Given that this PR is merged, let's incorporate this into the summit discussions on the rest of the fallbacking provider infrastructure

**Comment by robertbastian** [comment]
Note that we did agree on this:

> The three runtime providers we support (blob, fs, and unstable) should all add the correct type of fallbacking on their own. It should be driven by metadata in the blob/fs or in the generated code for databake. Could include no_fallback constructors on those three types.

https://github.com/unicode-org/icu4x/issues/2683#issuecomment-1516741934

**Comment by sffc** [comment]
> Note that we did agree on this:
> 
> > The three runtime providers we support (blob, fs, and unstable) should all add the correct type of fallbacking on their own. It should be driven by metadata in the blob/fs or in the generated code for databake. Could include no_fallback constructors on those three types.
> 
> [#2683 (comment)](https://github.com/unicode-org/icu4x/issues/2683#issuecomment-1516741934)

Huh. I wish that discussion included more notes about how we arrived at that conclusion.

**Pull request merged**
