### PR TITLE
Fix fallback algorithm to ignore aux keys when looking up parents

### PR DESCRIPTION
**Pull request by sffc**
This isn't mergeable since it adds an allocation in a hot path, but it demonstrates the source of the data diff found in #4981. CC @robertbastian

### CODE REVIEW

**Comment by robertbastian** [comment]
Can you merge this so I can merge without a diff? The allocation will be there until my PR only.

**Comment by robertbastian** [comment]
Alternatively, can you confirm that you're getting this failure:
```
thread 'main' panicked at provider/blob/benches/auxkey_bench.rs:97:5:
assertion `left == right` failed
  left: 450725
 right: 684197
```

**Comment by robertbastian** [comment]
I checked out your branch and get those exact numbers here as well. In that case I'll just update my PR.

**Comment by sffc** [comment]
I'm okay merging this first. I agree it is cleaner that way.

**Comment by sffc** [comment]
(I'm also okay just rolling these changes into your PR.)

**Comment by sffc** [comment]
684197 to 450725 is quite a size reduction, wow.

**Pull request closed without merging**
