### PR TITLE
Use rayon to add parallelism to datagen

### LINKED ISSUE #1245: Use parallelism in icu4x-datagen
@zbraniecki said in https://github.com/unicode-org/icu4x/pull/1244#pullrequestreview-793524661:

> this may also be a great candidate for one of the first uses of rayon and overall concurrency. If you can get to the point where you have any form of `tasks.for_each(|task| task::convert())` then it'll be trivial to switch to `tasks.for_par_each()`!

This is a great suggestion.  The architecture of icu4x-datagen should suit itself well for parallel processing of data keys.

### PR DESCRIPTION
**Pull request by mildgravitas**
This change adds per-export type (e.g. cldr, map_props...) and per key parallelism. Both changes improve speed as shown by measuring 100 runs of `cargo make testdata` (using 405b9fd316b87d2eaafa86d62d8ea02639472dec as baseline so script_extensions_props from 88f3e2ff55861a5e957d0aa04a68e76ac61b99f1 are not included):

testdata

Fixes #1245.

### CODE REVIEW

**Review by robertbastian — COMMENTED** [review]
Very cool!

**Review by sffc — COMMENTED** [review]
Thanks for doing this!

I'll rely on @robertbastian to give final approval since he's touching this part of the code.

**Comment by robertbastian** [comment]
I merged the datagen changes, which also adds parallelization per key option. Could you rerun the benches?

**Review by sffc — APPROVED** [review]

**Comment by sffc** [comment]
I would prefer to merge this now so that it doesn't bitrot. @mildgravitas can re-run the benches post-submit

**Comment by mildgravitas** [comment]
Running against a baseline of b34c72b370fddc504e1ca207099c523cbaed072a
image

**Pull request merged**
