### PR TITLE
Making list data zero-copy deserialisable for known regexes

### PR DESCRIPTION
**Pull request by robertbastian**

### CODE REVIEW

**Review by Manishearth — COMMENTED** [review]
neat idea; we should make the hashes resilient tho

**Comment by robertbastian** [comment]
Which hash function should we use?

**Comment by Manishearth** [comment]
Unsure, @sffc ? I'd rather not add dependencies for this; but this _is_ a safety requirement.

Tbh a better model may be to hardcode those data strings, an equality operation will not be too bad since it'll be fast-rejected for other strings.

**Comment by robertbastian** [comment]
The three current DFA are 664, 957, and 745 bytes. Is avoiding the dependency worth 2.3KB code size?

**Comment by Manishearth** [comment]
I'm not sure! I think hashing is certainly clever and better if we can use it. I really like keeping our default (icu + serde) crate footprint relatively small when it comes to third party stuff though.

(It's worth asking upstream: is there a middle ground possible where we have a way to validate the regex-automata DFA for _just_ safety invariants and not correctness invariants)

**Comment by robertbastian** [comment]
> (It's worth asking upstream: is there a middle ground possible where we have a way to validate the regex-automata DFA for just safety invariants and not correctness invariants)

We already got an out-of-cycle release to get the invariants check, and the version we're using is not being developed anymore.

**Comment by sffc** [comment]
Discuss with:

- @sffc 
- @Manishearth 
- @robertbastian

**Comment by sffc** [comment]
Conclusion:

- Best long-term solution is to work with upstream to validate safety invariants without alloc
- We could introduce a workaround like what is being proposed in this PR if ICU4X gets a no-alloc mode
- There is cost and complexity with this change that doesn't seem clearly justified at the moment

LGTM: @Manishearth @sffc @robertbastian

**Pull request closed without merging**
