### PR TITLE
Retrieve localized metazone info from timeZoneNames.json

### PR DESCRIPTION
**Pull request by samchen61661**
Retrieve localized metazone info from timeZoneNames.json

The idea is to create an extra field called `overrides` to get localized metazone name from timezone id.

### CODE REVIEW

**Comment by samchen61661** [comment]
Hey Eric, this PR is still in the very early phase. I think I need more clarification to move it forward.

Based on our last discussion, we want to create an `overwrites` field in the existing V1 types. So in this PR, I added a new field called `overwrites` in `MetaZoneGenericNamesLongV1`, `MetaZoneGenericNamesShortV1`, `MetaZoneSpecificNamesLongV1` and `MetaZoneSpecificNamesShortV1`.

If I understand correctly, the key in the `default`'s `LiteMap` in `MetaZone...LongV1` is location while the value is metazone name. Then the key in the `overwrites` 's `LiteMap` in `MetaZone...LongV1` is location while the value is metazone name? 

Another question I have is how to get the correct localized metazone for different V1 types, for example, we have `MetaZoneSpecificNamesShortV1` and `MetaZoneGenericNamesShortV1`. I assume that there is a key called `generic` in the zone format, so I wrote `sub_region_location.short.as_ref().and_then(|zf| zf.0.get("generic").or_else(|| type_fallback(zf)))` for `MetaZoneGenericNamesShortV1`. But how about `MetaZoneSpecificNamesShortV1`? Is it mapped to key `standard` or `daylight`?

**Comment by nordzilla** [comment]
> Based on our last discussion, we want to create an `overwrites` field in the existing V1 types.

Yes, this is the correct approach, though I think we want to call them `overrides` instead of `overwrites` (they sound similar when spoken).

> If I understand correctly, the key in the default's LiteMap in MetaZone...LongV1 is location while the value is metazone name. Then the key in the overwrites 's LiteMap in MetaZone...LongV1 is location while the value is metazone name?

They `key` for the `defaults` is a metazone identifier (MZID), mapping to a localized metazone name.
The `key` for the `overrides` is time-zone identifier (TZID), mapping to a localized metazone name.

>  so I wrote sub_region_location.short.as_ref().and_then(|zf| zf.0.get("generic").or_else(|| type_fallback(zf))) for MetaZoneGenericNamesShortV1. 

Yes, that looks right for the generic names.

> But how about MetaZoneSpecificNamesShortV1? Is it mapped to key standard or daylight?

Yes, see how the [generic names v1](https://github.com/unicode-org/icu4x/blob/bffe5bad6d78ee37fed4c7f5b44ed730600b6c17/components/datetime/src/provider/time_zones.rs#L101-L102) are just a one-layer map: `Map("id" => "localized content")`

But the [specific names v1](https://github.com/unicode-org/icu4x/blob/bffe5bad6d78ee37fed4c7f5b44ed730600b6c17/components/datetime/src/provider/time_zones.rs#L129-L145) are two-layer map: `Map("id" => Map("generic|specific" => "localized content"))`

**Comment by samchen61661** [comment]
> @samchen61661 looking good so far!
> 
> > Based on our last discussion, we want to create an `overwrites` field in the existing V1 types.
> 
> Yes, this is the correct approach, though I think we want to call them `overrides` instead of `overwrites` (they sound similar when spoken).
> 
> > If I understand correctly, the key in the default's LiteMap in MetaZone...LongV1 is location while the value is metazone name. Then the key in the overwrites 's LiteMap in MetaZone...LongV1 is location while the value is metazone name?
> 
> They `key` for the `defaults` is a metazone identifier (MZID), mapping to a localized metazone name. The `key` for the `overrides` is time-zone identifier (TZID), mapping to a localized metazone name.
> 
> > so I wrote sub_region_location.short.as_ref().and_then(|zf| zf.0.get("generic").or_else(|| type_fallback(zf))) for MetaZoneGenericNamesShortV1.
> 
> Yes, that looks right for the generic names.
> 
> > But how about MetaZoneSpecificNamesShortV1? Is it mapped to key standard or daylight?
> 
> Yes, see how the [generic names v1](https://github.com/unicode-org/icu4x/blob/bffe5bad6d78ee37fed4c7f5b44ed730600b6c17/components/datetime/src/provider/time_zones.rs#L101-L102) are just a one-layer map: `Map("id" => "localized content")`
> 
> But the [specific names v1](https://github.com/unicode-org/icu4x/blob/bffe5bad6d78ee37fed4c7f5b44ed730600b6c17/components/datetime/src/provider/time_zones.rs#L129-L145) are two-layer map: `Map("id" => Map("generic|specific" => "localized content"))`

Thanks Eric!

re: `The key for the overrides is time-zone identifier (TZID), mapping to a localized metazone name.`: 
There are a couple of maps inside the `Zones` structure. I wonder which key is mapped to `TZID`. Is it the key for `Zones`, or `Region` or `SubRegion`?

Also, is it 1 to 1 mapping for  `TZID` and  `localized metazone name`? The reason why I ask is that I feel like I need to collapse the results while filtering `SubRegion` if it is a 1 to 1 mapping.

**Comment by nordzilla** [comment]
> Also, is it 1 to 1 mapping for `TZID` and `localized metazone name`?

The mapping is injective (1-to-1), but not surjective (onto). That is, there will only be one localized metazone name for a given TZID, but not every TZID has this information. Only IDs like `Europe/London` and `Pacific/Honolulu` have this information.

Currently, the only mapping we have where TZID is the key is for `ExemplarCitiesV1`.

**Review by nordzilla — CHANGES_REQUESTED** [review]
Just marking this as "Request changes" to get it out of my queue. 

Please re-request review when you want me to take a look at it again.

**Review by nordzilla — CHANGES_REQUESTED** [review]
@samchen61661 this looks great overall. 

Great job digging into the complicated iterator chains in the transform code. 

I want to make sure that we wait to rebase on top of #1405 when it lands, because it looks like some of the newly generated data in this PR should already be present, and I want to make sure this PR reflects only the new data that is added by this functionality, and not by fixing that bug.

**Review by sffc — APPROVED** [review]
Praise: Nice job!

I reviewed the runtime part of the code and it looks great.  I trust @nordzilla's review on the transformer code.

**Review by nordzilla — APPROVED** [review]

**Pull request merged**
