### PR TITLE
Move numbering systems field over to DecimalSymbolsStrs

### PR DESCRIPTION
**Pull request by Manishearth**
Depends on https://github.com/unicode-org/icu4x/pull/5822

Minor win:

```
Before: decimal/symbols@2, <total>, 2740B, 1368B, 49 unique payloads
After:  decimal/symbols@2, <total>, 2657B, 1285B, 49 unique payloads
```

And an 8 byte win on FDF stack size.

### CODE REVIEW

**Review by sffc — DISMISSED** [review]
The stack size win is my main motivation

**Comment by Manishearth** [comment]
@sffc Thought: do you think we can get away with Index8 for DecimalSymbolStrs? Each one of its entries is at worst  3 characters (when it contains bidi format characters), and then there's the ascii numbering system, at worst 8 bytes. 

`(8 numsys bytes) + (3 chars) * (2-4 bytes per char) * (6 fields)` is  44-80, which is still well in range for a u8.

**Comment by sffc** [comment]
Yes we should definitely use Index8

**Comment by Manishearth** [comment]
```
Before: decimal/symbols@2, <total>, 2657B, 1285B, 49 unique payloads
After:  decimal/symbols@2, <total>, 2363B, 991B, 49 unique payloads
```

For Index8.

**Review by sffc — APPROVED** [review]

**Pull request merged**
