### PR TITLE
Update diplomat

### PR DESCRIPTION
**Pull request by Manishearth**
Lots of changes to JS enums, borrowing, and Option support.

I plan to make use of Option support in a separate PR.

### CODE REVIEW

**Comment by Manishearth** [comment]
autosubmit = on

**Comment by sffc** [comment]
```
error: package `pulldown-cmark v0.11.2` cannot be built because it requires rustc 1.71.1 or newer, while the currently active rustc version is 1.70.0
Either upgrade to rustc 1.71.1 or newer, or use
cargo update -p pulldown-cmark@0.11.2 --precise ver
where `ver` is the latest version of `pulldown-cmark` supporting rustc 1.70.0
```

https://github.com/rust-diplomat/diplomat/pull/666

**Comment by sffc** [comment]
Two choices:

1. Downgrade the pulldown_cmark to 0.10.0 which is MSRV-compatible
2. Bump our MSRV version in the icu4x repo

**Comment by sffc** [comment]
https://github.com/rust-diplomat/diplomat/issues/672

**Comment by Manishearth** [comment]
I'm going to rustup us. We'll probably want to do more version updates, but 1.71.1 seems fine for now.

**Comment by Manishearth** [comment]
https://github.com/unicode-org/icu4x/pull/5484

**Review by sffc — APPROVED** [review]

**Pull request merged**
