### PR TITLE
Add impl From<&CompactDecimal> for PluralOperands

### PR DESCRIPTION
**Pull request by sffc**
CC @sven-oly

### CODE REVIEW

**Comment by sffc** [comment]
Oof, the resolver was being too _smart_ before, and now it's biting us. This is in `tutorials-local` CI:

```rust
error[E0283]: type annotations needed
  --> src/main.rs:16:24
   |
16 |     let result = rules.category_for(&3.into());
   |                        ^^^^^^^^^^^^    ---- type must be known at this point
   |                        |
   |                        cannot infer type of the type parameter `I` declared on the method `category_for`
   |
   = note: cannot satisfy `_: From<i32>`
   = note: required for `i32` to implement `Into<_>`
```

I thought adding impls was supposed to always be semver safe.

**Comment by sffc** [comment]
Adding @Manishearth as reviewer because of the resolver issue

**Comment by Manishearth** [comment]
> I thought adding impls was supposed to always be semver safe.

No, it's actually expected: In general Rust does not consider "you will need to disambiguate" as a breaking change because otherwise you would never be able to add _anything_ to your API. Adding `From` impls can have that effect.

**Comment by sffc** [comment]
> > I thought adding impls was supposed to always be semver safe.
> 
> No, it's actually expected: In general Rust does not consider "you will need to disambiguate" as a breaking change because otherwise you would never be able to add _anything_ to your API. Adding `From` impls can have that effect.

ok so does this mean we can land this without a semver bump?

**Comment by Manishearth** [comment]
However we should use our judgement on how commonly we expect this breakage to cause actual problems.

**Review by echeran — DISMISSED** [review]
LGTM

**Comment by sffc** [comment]
Yet Another Reason™ to not use `Into` bounds on function parameters.

(CC @zbraniecki @robertbastian who like to do this sometimes)

**Comment by Manishearth** [comment]
It's specifically the chaining of two Intos that's the problem here, I think. Ideally an API should never require that: there should be Into impls for integers as well.

**Comment by sffc** [comment]
Looking at the code, I'm surprised that the resolver looks at `&3.into() as Into<PluralOperands>` and decides to infer a `FixedDecimal` as the intermediate type when there is nothing suggesting that. Does it check _every_ implementer of `Into<PluralOperands>` that's in scope and use it so long as it is unique? That seems really really brittle.

**Comment by Manishearth** [comment]
Yes, sometimes, it doesn't always work, I usually don't rely on it except in specific contexts.

**Comment by sffc** [comment]
We all agree that clients shouldn't do this. My separate position is that functions should prefer accepting concrete types over things like `Into` or `IntoIterator` but we don't need to rehash that now. We should also consider adding the "bridging impls", but we can open a separate issue for that.

I guess the question for us at the moment is, given that we have had this docs example for quite some time, do we care that it breaks in 1.5?

**Comment by Manishearth** [comment]
IMO no, but I think we should invest in adding bridging impls.

**Comment by sffc** [comment]
Discussion: the call site is fragile and should be re-written anyway; it is only in a tutorial, not a docs test, which lowers the risk. This should be a Clippy lint. So this PR can proceed.

LGTM: @Manishearth @robertbastian @sffc

**Comment by sffc** [comment]
We already have `impl From<{int}> for PluralOperands` so I changed the tutorials to just pass the number straight in.

**Review by Manishearth — APPROVED** [review]

**Comment by sffc** [comment]
@robertbastian If you LGTM this PR, including the tutorial change, I will merge it.

**Review by robertbastian — APPROVED** [review]

**Comment by sffc** [comment]
Waiting on review from @eggrobin

**Review by eggrobin — APPROVED** [review]

**Pull request merged**
