### PR TITLE
Optimize performance of LocaleCanonicalizer::maximize.

### PR DESCRIPTION
**Pull request by zbraniecki**
This is the result of my exploration into perf difference between `unic-locale` and ICU4X LocaleCanonicalizer.

I was able to match and even slightly outmatch the `unic-locale` and make the performance ~50% faster:

```
likelysubtags/maximize  time:   [1.1568 us 1.1609 us 1.1647 us]
                        change: [-47.564% -47.344% -47.154%] (p = 0.00 < 0.05)
                        Performance has improved.
```

The remaining difference (another 50%) is due to `Locale` vs `LanguageIdentifier` and I hope that @dminor's work on having LID be a field on Locale will erase that.

Now, this PR does one thing that I'd like to discuss, which is that it uses u64/u32 in the resource file, rather than strings making the CLDR version less readable.
In theory, I think subtags should be comparably fast (binary search/partialeq on `X(TinyStr8(u64))` and `u64` should be similar), but it's not, so I wanted to put the PR here for discussion.

### CODE REVIEW

**Comment by sffc** [comment]
I'm onboard with the new approach (essentially matching on ints rather than strings).

I want to learn more about:

> In theory, I think subtags should be comparably fast (binary search/partialeq on X(TinyStr8(u64)) and u64 should be similar), but it's not, so I wanted to put the PR here for discussion.

Does the performance degredation of using subtags result from:

1. Slower parsing from the data file?
2. Extra layer of abstraction over the u32/u64 in PartialEq that the compiler can't optimize away?

**Comment by zbraniecki** [comment]
> Does the performance degredation of using subtags result from:

I don't know yet. I'll investigate.

**Comment by dminor** [comment]
I played around with TinyStr4 on godbolt.org a bit this morning, and it looks like there is overhead for using NonZeroU32 rather than u32.

For instance with "-C opt-level=2", for a TinyStr4 using NonZeroU32, I get the following for cmp:
```
<example::TinyStr4 as core::cmp::Ord>::cmp:
        mov     eax, dword ptr [rdi]
        mov     ecx, dword ptr [rsi]
        xor     edx, edx
        cmp     eax, ecx
        bswap   ecx
        bswap   eax
        setne   dl
        cmp     eax, ecx
        mov     eax, 255
        cmovae  eax, edx
        ret
```
If I switch TinyStr4 to use a raw u32, I get this instead:
```
<example::TinyStr4 as core::cmp::Ord>::cmp:
        mov     eax, dword ptr [rdi]
        xor     ecx, ecx
        cmp     eax, dword ptr [rsi]
        setne   cl
        mov     eax, 255
        cmovae  eax, ecx
        ret
```
It might be worthwhile benchmarking with a u32 based TinyStr to see if this explains some of the performance difference we're seeing.

**Comment by dminor** [comment]
Hmm, if we're using NonZeroU32 and friends to avoid overhead when storing them in an Option<>, then maybe benchmarking with raw u32 would end up being inconclusive.

**Comment by sffc** [comment]
Would it help to implement `Ord` and friends in TinyStr manually, to remove the NonZeroU32 layer?

**Comment by sffc** [comment]
I'm converting this to draft because:

1. The tests are not passing
2. We agreed today to perform a bit more investigation into the source of the performance bottleneck

**Comment by zbraniecki** [comment]
I rebased this on top of `main`, and I'm getting same range of performance improvements:

```
   Compiling icu_locale_canonicalizer v0.1.0 (/projects/icu4x/components/locale_canonicalizer)
    Finished bench [optimized + debuginfo] target(s) in 3.62s
Gnuplot not found, using plotters backend
Benchmarking likelysubtags/maximize: Collecting 100 samples in estimated 5.0050 s (4.2M iterati                                                                                               likelysubtags/maximize  time:   [1.1898 us 1.1930 us 1.1965 us]
                        change: [-46.605% -46.416% -46.240%] (p = 0.00 < 0.05)
                        Performance has improved.
```

@dminor ran some perf analysis that may be actionable in form of tinystr issue (@dminor - would you consider it worth filing one to switch away from `NonZero32` or introducing custom `Ord` for perf wins on comparisons?), and I think that this PR can be considered for 0.2.

I'm also ok not taking it although that would make our comparator significantly slower than `unic_langid` which we use in Firefox now.

**Comment by dminor** [comment]
The benefit of NonZeroU32 is that we can store it in an Option without requiring additional space, and we have a lot of Option<TinyStr> in our code, so it seems like that would end up being a performance/space tradeoff. Depending on how Option<u32> is stored, it might not even be great for performance if we end up with an extra level of indirection.

I do think it is worth opening an issue on TinyStr to investigate the performance difference. I wrote a small benchmark, but I haven't had time to go back and profile. I'm not sure if the difference in the code generation for Ord actually makes that much of a difference.

I think it is too bad to lose the readability of the json here. I think with Greg's work, we now have a precedent to keep json readable and bincode efficient. Would it be much additional work to change the serde code to keep the json human readable?

**Comment by zbraniecki** [comment]
> I do think it is worth opening an issue on TinyStr to investigate the performance difference. I wrote a small benchmark, but I haven't had time to go back and profile. I'm not sure if the difference in the code generation for Ord actually makes that much of a difference.

Can you document your findings in an issue on tinystr?

> I think it is too bad to lose the readability of the json here. I think with Greg's work, we now have a precedent to keep json readable and bincode efficient. Would it be much additional work to change the serde code to keep the json human readable?

I'm reluctant to take more work on 0.2 and this would require us to introduce a new type that serializes either to `u32` or String depending on if it's human readable.

I'm also not sure if I agree that keeping the JSON readable is of such high value, and since I feel overloaded it boils down to - are we blocking this perf win on this feature?

**Review by sffc — CHANGES_REQUESTED** [review]
When you first wrote this PR, it was before TinyStr implemented Serde.  Now that TinyStr implements Serde, can you try using that, instead of u32?

> I'm reluctant to take more work on 0.2 and this would require us to introduce a new type that serializes either to u32 or String depending on if it's human readable.

This is exactly what TinyStr serialization is doing.

I agree with @dminor that we have new precedent on keeping JSON human-readable.  If we want to back off from that precedent, we should discuss it with the group and make clear guidelines.

**Comment by sffc** [comment]
> I feel overloaded it boils down to - are we blocking this perf win on this feature?

On the one hand, this PR could be seen as a premature optimization that incurs technical debt.  We should not accept such PRs into ICU4X.

On the other hand, this PR could be seen as a long-term solution that improves performance in response to a clear and measurable reference point.  If this is the case, then it makes me a bit sad that we must resort to a readability tax in order to achieve the performance gain.

My preference would be if you can achieve the performance you want without sacrificing readability.

**Comment by zbraniecki** [comment]
> When you first wrote this PR, it was before TinyStr implemented Serde. Now that TinyStr implements Serde, can you try using that, instead of u32?

|          | maximize | % vs main | % vs u32 |
|----------|----------|-----------|----------|
| main     | 2.6us    |           |          |
| u32      | 1.19us   | -54%      |          |
| TinyStr4 | 1.62us   | -38%      | 36%      |

This is using `cargo criterion` on `locale_canonicalizer` crate. It is possible that this is benchmarking `json` and maybe we should be benchmarking `bincode` instead?

> On the one hand, this PR could be seen as a premature optimization that incurs technical debt.

I disagree on both accounts.

1) This does not fit my definition of "premature optimization".

This optimization is closing the performance gap between the way this logic works in production in Gecko right now, and this library that we hope to use to replace it. Without optimizations, we're going to face performance regressions if we were to replace `unic_langid` with `icu_locid` which is measurable and has impact on Firefox startup.

2) This does not fit my definition of "technical debt".

There's no accruing code that is more costly to refactor, maintain, or fix bugs in because of this change. It purely affects a resource format we store the data in.
If readability of the JSON artifact is more important than library performance in case where I'm showing 50% performance improvement, then I am miscalculating the value we put on either or both of those concepts in ICU4X.

> My preference would be if you can achieve the performance you want without sacrificing readability.

I'd prefer that as well, but I have not found a way to achieve that as of yet.
What we're facing as a group is the question whether 50% performance improvement is valuable enough to reduce readability of the JSON artifact.

I am really curious to learn what we'll decide the answer to be as a group because even if in this particular one we can craft a plan for 0.3 to achieve both, we will face more choice of that nature that may not be resolvable with a win-win and we'll have to decide on tradeoffs and this decision will set a precedence for future scenarios like this.

**Comment by sffc** [comment]
The performance improvement of using TinyStr4 by itself is quite nice!  My preferred path forward would be to approve a PR with that change, and then work on zbraniecki/tinystr#39 to close the gap between TinyStr4 and u32.

> It is possible that this is benchmarking json and maybe we should be benchmarking bincode instead?

The benchmark is only running the `maximize` function.  The data should have already been unpacked by that time.  So JSON/Bincode shouldn't make a difference.

> If readability of the JSON artifact is more important than library performance in case where I'm showing 50% performance improvement, then I am miscalculating the value we put on either or both of those concepts in ICU4X.

Now that we have the TinyStr4 numbers, we should consider that to be our new reference point.  u32 is 27% faster than TinyStr4 [`(1.19-1.62)/1.62`].  That may be compelling for an end-to-end test, but we are testing the `.maximize()` function in a tight loop of 39 locales.  It's not clear to me that a win of ~11 nanoseconds per locale is really going to make any difference at all in a larger application.

> I am really curious to learn what we'll decide the answer to be as a group because even if in this particular one we can craft a plan for 0.3 to achieve both, we will face more choice of that nature that may not be resolvable with a win-win and we'll have to decide on tradeoffs and this decision will set a precedence for future scenarios like this.

Yes, I agree.  I would maybe be more inclined to accept this PR if it were an isolated incident.  But, the fact that this sets precedent for future such changes makes me reluctant.  I do *not* think we should optimize for performance at all costs.  We should optimize for performance so long as the change is within other design constraints.  And readable JSON is, for better or for worse, a design constraint that we agreed to when we discussed #523.

**Comment by dminor** [comment]
It's clear this is a big win on a micro-benchmark, but I agree that it would make sense to see if this makes a significant difference in a real application. I suggest we land this as TinyStr4, do the work to switch Firefox over to using this code, and measure performance there. If it turns out this causes performance regressions in Firefox, then that is a good argument to sacrifice readability and use u32 directly here, and in parallel to prioritize the investigation of https://github.com/zbraniecki/tinystr/issues/39.

**Comment by zbraniecki** [comment]
ready for re-review.

```
likelysubtags/maximize  time:   [1.6175 us 1.6299 us 1.6511 us]
                        change: [-22.046% -21.398% -20.420%] (p = 0.00 < 0.05)
                        Performance has improved.
```

**Comment by zbraniecki** [comment]
Seems like we can have a cake and eat it too! This PR gives us the expected perf win, and https://github.com/zbraniecki/tinystr/pull/40 brings the rest.

**Review by dminor — APPROVED** [review]
Thanks for sorting out the TinyStr performance issue! That ends up being a much better solution than potentially having to replicate the u32 optimization in other places in the code.

**Review by sffc — APPROVED** [review]
Praise: Thanks for your work on this and being receptive to feedback!

**Review by nciric — APPROVED** [review]

**Pull request merged**
