### PR TITLE
CI fix experimentation

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Comment by sffc** [comment]
All 5 jobs are still failing. The error is new though:

```
error: the option `Z` is only accepted on the nightly compiler
```

**Comment by Manishearth** [comment]
Yep, that's because it selected a stable compiler.

**Comment by Manishearth** [comment]
"Unfortunately" the reverted rustup has been pushed up, so I don't think we can test this way anymore. We can instead test using docker or something.

**Comment by Manishearth** [comment]
I _think_ this fix worked though, except for the memory task.

**Pull request closed without merging**
