### PR TITLE
Update nightly to 2021-12-09

### PR DESCRIPTION
**Pull request by sffc**

### CODE REVIEW

**Comment by sffc** [comment]
CI is failing:

```
[cargo-make] INFO - Execute Command: "rustup" "run" "nightly-2021-12-09" "cargo" "build" "--package" "icu" "--target" "thumbv7m-none-eabi"

...

thread 'rustc' panicked at 'assertion failed: sentinel == STR_SENTINEL', /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/compiler/rustc_serialize/src/opaque.rs:669:9
stack backtrace:
   0:     0x7f394da8ae5c - std::backtrace_rs::backtrace::libunwind::trace::hf7449935ead7573e
                               at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f394da8ae5c - std::backtrace_rs::backtrace::trace_unsynchronized::h221aa2d88d72372a
                               at /rustc/e6b883c74f49f32cb5d1cbad3457f2b8805a4a38/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f394da8ae5c - std::sys_common::backtrace::_print_fmt::h1c77e8983e1df895

...

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (e6b883c74 2021-12-08) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `icu_locid`
```

**Comment by Manishearth** [comment]
Looks like a metadata bug in the compiler. huh.

**Review by gregtatum — APPROVED** [review]
Code changes look fine, I'm not sure about the CI failure other than to find a version that's not failing.

**Comment by Manishearth** [comment]
Note: https://github.com/rust-lang/rust/pull/91737 landed and should be in the latest nightly, worth updating to that to include additional code size wins.

**Pull request closed without merging**
