### PR TITLE
Split FFI CI job

### PR DESCRIPTION
**Pull request by robertbastian**
The CI job is running a lot of things and is timing out. I've split this into:
* `test-c`: runs all the C/CPP tests, needs clang and gcc
* `test-js`: runs all JS tests, needs node and lld
* `nostd`: checks that `icu` builds on no-std targets, and that `icu_freertos/wearos` builds. Only needs Cargo
* renamed `verify-ffi` -> `diplomat`, as it checks that Diplomat-generated files are up to date, similar to how the `gn` job checks GN files
* Removed the `wasm` job. To my knowledge this has never exposed an issue, and it's just repeating the C++ tests in emscripten, so it's effectively testing emscripten.

(I've only noticed #4141 after I did this, but I think this is a better solution)

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
wasn't immediately clear that `ci-job-diplomat` runs both verify-diplomat and verify-diplomat-coverage but lgtm

**Comment by robertbastian** [comment]
can't merge because of required checks

**Comment by sffc** [comment]
> can't merge because of required checks

I force-merged. What should the new set of required checks be?

**Comment by robertbastian** [comment]
I think everything can be required again, test mac and test-c take the longest and we definitely want to require those

**Comment by sffc** [comment]
I want to be clear with a specific list. For the CI required list, I should ADD:

test-c
test-js
nostd
diplomat

And I should REMOVE:

ffi
verify-ffi
wasm

Is that correct?

**Comment by robertbastian** [comment]
Partially correct, also add:
- test (macos-latest)
- testdata (macos-latest)
- testdata-legacy

**Comment by robertbastian** [comment]
I cannot see the current required list, basically it should match this https://github.com/unicode-org/icu4x/blob/c12b66ef7ed9cdabc0fa704cfafb9180edae56ba/.github/workflows/build-test.yml#L832

**Comment by robertbastian** [comment]
@sffc it doesn't look like you added the jobs:
image

**Comment by sffc** [comment]
ok I updated the list again. Maybe it didn't save the first time.

**Pull request merged**
