### PR TITLE
Update likely subtags algorithm to have correct error case behavior

### LINKED ISSUE #4409: Add error case to TransformResult
UTS 35 specifies an error case in the likely subtags algorithm. It says that the error case can be returned in a way conventional in the programming language. I propose adding it to the TransformResult enum:

```
#[allow(clippy::exhaustive_enums)]
pub enum TransformResult {
    /// The canonicalization operation modified the locale.
    Modified,
    /// The canonicalization operation did not modify the locale.
    Unmodified,
    // NEW ENTRY:
    /// The canonicalization operation failed to run to completion.
    /// The locale was not modified.
    Failed,
}
```

Unfortunately the enum is marked as `exhaustive`, so we need to wait until 2.0 to do this.

OK?

- [ ] @zbraniecki

### PR DESCRIPTION
**Pull request by sffc**
See https://github.com/unicode-org/cldr/pull/3176

Closes #4409

CC @macchiati @FrankYFTang

### CODE REVIEW

**Comment by sffc** [comment]
I'd like to wait until CLDR 44 Alpha is landed so that I can run the latest tests and not worry about version skew.

**Comment by sffc** [comment]
I think it passes the conformance test now.

I filed a follow-up with some inconsistent spec wording: https://unicode-org.atlassian.net/browse/CLDR-17269

**Comment by zbraniecki** [comment]
I'm concerned about this proposal.
It doesn't seem necessary from the spec perspective and I don't think it results in the expected behavior.

# Not necessary per spec.

Quoting [spec](https://unicode.org/reports/tr35/#Likely_Subtags):

> Signalling an error can be done in various ways, depending on the most consistent approach for APIs in the module. For example:
>
> 1.  raise an exception
> 2.  return an error value (such as null)
> 3.  return the input (with missing fields)
> 4.  return the input, but "Zzzz", and/or "ZZ" substituted for empty fields.
> 5.  "und"

It seems like this API changes *expected behavior* (3) to (4). 

# Counterintuitive

My expectation is that if I pass an unknown language, say `er-Latn` and we have no data to maximize it, I'll receive `er-Latn`, not `und-Zzzz-zz`.

**Comment by sffc** [comment]
The currently implemented behavior is to substitute und=en-Latn-US in for missing subtags on an unknown language, so er-Latn becomes er-Latn-US which is very wrong. This PR makes it er-Latn-ZZ (behavior 4). I'm also satisfied to implement behavior 3.

**Comment by zbraniecki** [comment]
Oh, ok. I see the bug you're describing. Yeah, I'd vastly prefer (3), and I'm comfortable adding (4) as an option ("fill blanks with ZZ" style) if you need it somewhere.

**Comment by sffc** [comment]
I implemented behavior 3 and made a follow-up to consider behavior 2. https://github.com/unicode-org/icu4x/issues/4409

**Review by zbraniecki — APPROVED** [review]
lgtm! thank you!

**Review by zbraniecki — APPROVED** [review]

**Pull request merged**
