### PR TITLE
Run CI bench command per component

### LINKED ISSUE #320: Fix up benchmark dashboard output
In the continuous integration workflow that performs benchmarks and creates the dashboards, the [command to create the benchmark output](https://github.com/unicode-org/icu4x/blob/master/.github/workflows/build-test.yml#L108) per component is not properly descending into each component to run the component-specific benchmarks.  Instead, it is running the same global-level benchmarks.

This is probably because the command descends into the wrong directory structure.  It is descending into the directories for storing output, when it should instead descending into the source code directories.  The output should still be directed into the other directory structure that it goes to currently.

### PR DESCRIPTION
**Pull request by echeran**
Fixes #320 

The PR does the following:

- run benchmark individually on each component
- update list of components of components with benchmarks

The PR was tested using my personal fork and a [testing PR in the fork](https://github.com/echeran/icu4x/pull/13).

### Notes

This PR is changing code that is the related to issue #327, so until that is also fixed, this PR might fail some of the checks.

In order to test this PR, I reset `master` on my personal fork to a commit that comes before the change that introduced #327.  That is the only way for the testing PR in the personal fork to pass the checks, anyways.

### CODE REVIEW

**Review by zbraniecki — APPROVED** [review]

**Comment by echeran** [comment]
Note to self: later on, we will need to clean up the dashboard HTML pages and/or historical data JSON file in order to remove the graphs of the globally-run benchmark tests, in order to only show the component-specific benchmark tests in each component-specific dashboard page.

**Comment by echeran** [comment]
Now that this PR is rebased against master after merging in PR #330 (for issue #327), 2 of the 3 benchmark actions now succeed -- for `components/locale` and `components/uniset`.  The action for `utils/fixed-decimal` fails with an error message [saying that it can't find the output of the benchmark command](https://github.com/unicode-org/icu4x/pull/328/checks?check_run_id=1243814276#step:5:17).  Before this recent rebase against master, this error message was present in all 3 benchmark actions.

**Review by zbraniecki — APPROVED** [review]
I'll take partial wins.

**Comment by echeran** [comment]
Ok, partial wins sounds good, I'll merge this PR.  GH will auto-close the parent issue, but I'll re-open it so that it stays open until we fully fix that last outstanding benchmark action.  I'll keep working on the issue.

**Pull request merged**
