### PR TITLE
Change SymbolsV1 to use VarZeroVec instead of Cow Array

### PR DESCRIPTION
**Pull request by sffc**
DO NOT MERGE

See #3413

This is an example of the scale of savings we can get by changing DateTimeFormatter data structs to use more compact structures instead of arrays of cows.

In this PR, I changed the weekday symbols from a `[Cow<str>; 7]` to a `VarZeroVec<str>`. I didn't change the month names and other symbols which are also low-hanging fruit.

Top line number is that DateFormatter went from 5784 to 4248. (Almost a 27% improvement!)

Of course, I cannot merge this PR because it breaks serialization. It also breaks bake data and AnyProvider, which is not desirable. If we were to go down this path, we should make a SymbolsV2.

Also, postcard gets a bit bigger, which is annoying.

CC @Manishearth

### CODE REVIEW

**Comment by robertbastian** [comment]
Replacing `Cow<'d, str>` by `&'d str` reduces `DateFormatter` to 3400 bytes (almost 50%) without breaking the serialization format (we do lose JSON support, but could put this behind a flag).

I have not seen a use case where mutability of the data struct is actually used, in any component. Datagen will need some work to be able to generate fully borrowed structs, but I don't think the `Cow`s we sprinkle in everywhere are good value for money.

Databake breakages are allowed as we don't guarantee the Rust stability of data structs. We already made a change to `StringMatcher`'s constructor after 1.0.

**Comment by Manishearth** [comment]
A feature for mutability is definitely an interesting idea. We could use something like `icu_provider::Cow` that's a cfg'd newtype, and only enable it by default if the json provider is enabled.

Though for Shane's [internal Google] work he's already patching data to do pattern stuff. It's useful functionality.

**Comment by sffc** [comment]
I made https://github.com/unicode-org/icu4x/pull/3443 to document why we need mutable locale data.

I think it's fine to make certain tradeoffs that reduce the performance of the mutation path if they benefit the non-mutation path, but we should still support it as a first-class feature.

**Comment by sffc** [comment]
Closing this PR but keeping the code archived at https://github.com/sffc/omnicu/tree/archive/dtf-vzv-size-example

**Pull request closed without merging**
