### PR TITLE
Add permutation to ZVL containers

### PR DESCRIPTION
**Pull request by robertbastian**

### CODE REVIEW

**Review by pdogr — APPROVED** [review]

**Review by hsivonen — APPROVED** [review]
I'm neither familiar with this component nor what use case this is for, but rubber-stamping on the assumption that I had the best time zone availability as a reviewer.

**Comment by robertbastian** [comment]
Yep, thanks!

**Review by Manishearth — CHANGES_REQUESTED** [review]
I don't understand why this needs to be in ZVL, and I'd rather not maintain permutation code in ZVL, it seems like a highly specific API.

ZVL is for supporting ZeroMap and none of the functions should be called directly. If this code isn't being called by ZeroMap it shouldn't be here.

Can we please back this out?

**Comment by robertbastian** [comment]
This is functionality required by ZeroHashMap

**Comment by Manishearth** [comment]
Can we discuss that first?

Kinda wary of maintaining a full hashtable in this crate.

**Comment by robertbastian** [comment]
Leave a comment on the issue? https://github.com/unicode-org/icu4x/issues/2532

**Comment by robertbastian** [comment]
We can of course put the permutation logic at the call site, but then we'd still need `zvl_swap`. And repeated swapping is really inefficient for the unsized collections.

**Comment by sffc** [comment]
I'm OK adding things to ZVLike that are useful, but I would like to understand what makes them useful first.

**Comment by pdogr** [comment]
For `ZeroHashMapStatic` we were keeping `reverse_mapping` which kept original index of the key, value.
So instead of storing that, we could permute the container by applying the `reverse_mapping` to both key, values. This way we save bytes by not storing `reverse_mapping`.

**Pull request merged**
