### PR TITLE
Hide `icu::properties::runtime::*` again

### PR DESCRIPTION
**Pull request by robertbastian**

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Review by Manishearth — COMMENTED** [review]
not a huge fan of always having the parse step but I think this is fine for now

**Review by Manishearth — CHANGES_REQUESTED** [review]
Actually, no. I recall a major use case in actual code for this stuff was parsing a property and figuring out whether it is binary or enumerated, which dictates what code you use after that. Having a runtime way of talking about which property you have (which doesn't require parsing multiple times) is useful for that.

**Comment by robertbastian** [comment]
This restores what is currently launched.

**Review by Manishearth — APPROVED** [review]

**Review by Manishearth — APPROVED** [review]

**Comment by robertbastian** [comment]
#3573

**Pull request merged**
