### PR TITLE
Attempt to remove YokeTraitHack

### PR DESCRIPTION
**Pull request by sffc**
I get a lot further than before, but there's still an error on StructProvider.

### CODE REVIEW

**Comment by sffc** [comment]
Blocked on https://github.com/rust-lang/rust/issues/89196

**Comment by sffc** [comment]
Based on @Manishearth's respose https://github.com/rust-lang/rust/issues/89196#issuecomment-931977890, it seems unlikely that we will be able to get rid of YokeTraitHack, unless it turns out that the inference bug is solvable.

Shall I close this PR and open a new bug to track the new Rust bug in the chance that it is fixed at some point?

**Comment by Manishearth** [comment]
@sffc sounds good. We can still remove the `_with_capture` and other hacks we had to add.

I was a bit worried about this when introducing `DataMarker` (because of the kind of indirection it introduces) but on balance I think having to use the trait hack is better than not having `DataMarker`'s ergonomics

**Comment by sffc** [comment]
This PR is superseded by #1134

#1061 is the issue to track removing the workarounds for Rust bugs.

I am attempting to remove `_with_capture` in https://github.com/unicode-org/icu4x/pull/1133 but I hit another issue, which is explained over there.

**Pull request closed without merging**
