### PR TITLE
Move ffi data struct

### PR DESCRIPTION
**Pull request by robertbastian**
This should live in the decimal module.

### CODE REVIEW

**Comment by Manishearth** [comment]
Wait, why? We may add more data structs to it in the longer term as needed.

**Comment by robertbastian** [comment]
Oh I thought this was a leftover. What's the advantage of having `ICU4XDataStruct::create_decimal_symbols_v1(&DiplomatStr, &DiplomatStr, &DiplomatStr, &DiplomatStr, &DiplomatStr, &DiplomatStr, u8, u8, u8, &[DiplomatChar])` and `ICU4XDecimalFormatter::create_with_decimal_symbols_v1(&ICU4XDataStruct, ICU4XFixedDecimalGroupingStrategy)` instead of `ICU4XDataStruct::create(&DiplomatStr, &DiplomatStr, &DiplomatStr, &DiplomatStr, &DiplomatStr, &DiplomatStr, u8, u8, u8, &[DiplomatChar], ICU4XFixedDecimalGroupingStrategy)`? The data payload uses dynamic typing, and allocates an `Rc`, so there seems to be a lot of overhead.

**Comment by Manishearth** [comment]
You can use your own data that you already have access to. WearOS uses this and they want to use their own data they get from Android

**Comment by Manishearth** [comment]
I think we had that first and we moved to this after some discussion. This was a deliberate choice to make data struct API kind of unobtrusive. It's not a huge runtime overhead.

**Comment by Manishearth** [comment]
Instead of using dyn we could internally have an enum!

**Pull request closed without merging**
