### PR TITLE
Try to remove docker images again

### PR DESCRIPTION
**Pull request by robertbastian**

### CODE REVIEW

**Comment by sffc** [comment]
The containers solved problems in the past and they provide a more stable/reproducible environment. What motivates the change?

**Comment by robertbastian** [comment]
Docker was down yesterday evening and this was blocking merges. The new Ubuntu runner ships with the LLVM versions for which you added the docker images.

**Comment by robertbastian** [comment]
It also ships with node preinstalled, unlike that docker image.

**Comment by robertbastian** [comment]
And Rust

**Review by sffc — APPROVED** [review]

**Pull request merged**
