### PR TITLE
Use `DataPayload::from_static_ref` in databake

### PR DESCRIPTION
**Pull request by robertbastian**
This allows inlining the lookup functions and `AnyProvider` to be backed by `DataProvider`.

I've also inlined the skeletons special case, as it's only called in one location now and I don't like having the hacky zerocopy on the API.

### CODE REVIEW

**Comment by Manishearth** [comment]
Any particular reason for killing the lookup method? It feels like it's still neater for diagnostics and debugging.

**Review by Manishearth — APPROVED** [review]
r=me but i kinda liked the separate lookup method, it felt cleaner. We don't have to call it from other spots.

(also: the lack of .data.rs for the macro files is kinda annoying, not opposed to that fix being rolled into this PR as well. I'm okay with macros.rs still being .rs)

**Comment by robertbastian** [comment]
> Any particular reason for killing the lookup method? It feels like it's still neater for diagnostics and debugging.

It simplifies adding the fallback (#3487), because we need to put the resolved locale in the metadata. With an inlined `#lookup` expression it's much simpler, because we can access `load`'s local variables, with a separate `fn lookup` we'd have to return `Result<(&'static #data_struct, Option<DataLocale>), DataErrorKind>` which I think gets messy.

I also don't necessarily want this to be publicly accessible.

**Comment by robertbastian** [comment]
> (also: the lack of .data.rs for the macro files is kinda annoying, not opposed to that fix being rolled into this PR as well. I'm okay with macros.rs still being .rs)

Why is that annoying? They're still marked as generated files.

**Comment by Manishearth** [comment]
Yeah but you can no longer make them go away completely in the github review view

**Review by Manishearth — APPROVED** [review]

**Pull request merged**
