### PR TITLE
Update to CLDR 46.1 beta1

### PR DESCRIPTION
**Pull request by sffc**
Mostly clean except there is an error in transliterator datagen.

The fixes to datetime patterns won't happen until #5826 lands.

### CODE REVIEW

**Comment by sffc** [comment]
```
2024-12-11T20:34:12.223Z WARN  [icu_provider::error] ICU4X data error: Invalid transliterator: at 15:3 '[[:Zs:]0-9!\?\+/@()\[\]_:;,\.'"\\$=\-[:Ethiopic:]] ;'
2024-12-11T20:34:12.223Z WARN  [icu_provider::error] ICU4X data error: Invalid transliterator: UnicodeSetError(ParseError { offset: Some(34), kind: UnexpectedChar('=') })
```

**Comment by sffc** [comment]
The diff is:

https://github.com/unicode-org/cldr/commit/48afc24e154d0a59d0e957caeb7db7d4f3409cf0#diff-60e74ce06705fbcf14adbd95f27b55e055dc55db5a17fa3c43b513654e2e24aa

It appears to have fixed an unescaped `$`, which then unshadowed an unescaped `=`

**Review by Manishearth — APPROVED** [review]
ty for making it clear what the changes are!

**Comment by sffc** [comment]
Rebased on top of #5891

**Review by Manishearth — APPROVED** [review]

**Pull request merged**
