### PR TITLE
Remove ZeroVec T: Bake bound.

### PR DESCRIPTION
**Pull request by sffc**
zervec and zervec derive to 0.9.6

https://github.com/unicode-org/icu4x/issues/4065

### CODE REVIEW

**Comment by sffc** [comment]
tutorials-cratesio is failing because of this, but _should_ be fixed after we publish

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
Published and yanked

**Comment by robertbastian** [comment]
Why was this done?

**Comment by sffc** [comment]
After we uploaded zerovec 0.9.5 with `T: Bake`, `icu_timezone@1.2` started failing to compile. This PR fixed that problem, and then we moved the breaking zerovec change to 0.10.0

**Comment by robertbastian** [comment]
I see, so this has been reverted in another PR?

**Comment by sffc** [comment]
`T: Bake` was added back in https://github.com/unicode-org/icu4x/pull/4081 which updated zerovec to 0.10.0

**Pull request merged**
