### PR TITLE
Improving `icu` crate docs, features, modules

### PR DESCRIPTION
**Pull request by robertbastian**
Some of these have diverged a lot

### CODE REVIEW

**Review by sffc — DISMISSED** [review]
Looks good to me, but adding @zbraniecki who first wrote these docs

**Comment by zbraniecki** [comment]
> `icu_X` is one of the [`ICU4X`] components.

is a convention we use to start every (?) component doc - the aim is to help lost traveler who discovers this set find their way home.
You diverge from that in two places - I'm not sure if we should and if we do then:
a) we should have a discussion about it
b) we should do it everywhere

**Comment by robertbastian** [comment]
Also reexported collator and normalizer, which are stable components that weren't included before. `fixed_decimal` was a dependency of `icu`, but not reexported, so I removed it. I think we have a thread about utils reexports somewhere?

**Comment by robertbastian** [comment]
http://icu4x-pr-artifacts.storage.googleapis.com/gha/088ece93baa29e6ede2078905994ffb51623dac1/docs/icu/index.html

**Review by sffc — APPROVED** [review]

**Pull request merged**
