### PR TITLE
Add no-git-tag to instructions

### PR DESCRIPTION
**Pull request by sffc**

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by robertbastian** [comment]
I don't think it matters because tags don't survive squashing

**Comment by Manishearth** [comment]
I don't think so? They'll still be around locally and get pushed when you `git push --tags`, git doesn't care if they're pointing to commits not on a branch

**Comment by robertbastian** [comment]
I guess they'll be on your fork yeah

**Comment by Manishearth** [comment]
Well, when you make the final git tag (or an `indep/` release) you'll be pushing to `origin`

**Comment by robertbastian** [comment]
Most of us aren't allowed to do that and have to create the tag in the UI 😉

**Comment by Manishearth** [comment]
Well, three of the four people who regularly run releases are :smile:

**Review by robertbastian — APPROVED** [review]

**Pull request merged**
