### PR TITLE
Remove unused testdata deps

### PR DESCRIPTION
**Pull request by robertbastian**

### CODE REVIEW

**Review by Manishearth — DISMISSED** [review]

**Comment by sffc** [comment]
Shouldn't this now also affect the other Cargo.lock file in docs/tutorials/crates?

**Comment by robertbastian** [comment]
ugh

**Comment by robertbastian** [comment]
It's annoying because they don't get automatically updated.

**Comment by sffc** [comment]
I think we should make CI fail for that?

**Review by sffc — APPROVED** [review]

**Review by Manishearth — APPROVED** [review]

**Comment by robertbastian** [comment]
That'd be even more annoying

**Pull request merged**
