### PR TITLE
Make clippy warnings report as errors and update clippy args

### LINKED ISSUE #643: Investigate why clippy CI isn't failing
See #642.  There were over 300 clippy warnings, which accumulated over some time, but CI failed to flag them.  Figure out why it isn't being flagged.

CC @zbraniecki @echeran @gregtatum

### PR DESCRIPTION
**Pull request by echeran**
Fixes #643

### CODE REVIEW

**Review by Manishearth — DISMISSED** [review]

**Comment by echeran** [comment]
Currently blocked on #713

**Comment by sffc** [comment]
@echeran can you update this PR given that #719 is merged?

**Review by Manishearth — APPROVED** [review]

**Comment by echeran** [comment]
@Manishearth , after bringing in the new changes, there's (at least) one more clippy warning. ([Link to output in CI](https://github.com/unicode-org/icu4x/runs/2625232368?check_suite_focus=true#step:5:688)). Is it correct to assume that, because the code is inside an unsafe block, and because the clippy suggestion seems far more unreadable, that we can place an override for the clippy suggestion here?

```
error: transmute from a reference to a reference
  --> utils/zerovec/src/yoke_impls.rs:73:13
   |
73 |             mem::transmute::<&Self, &Self::Output>(self)
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `&*(self as *const map::ZeroMap<K, V> as *const map::ZeroMap<<K as yoke::Yokeable>::Output, <V as yoke::Yokeable>::Output>)`
   |
   = note: `-D clippy::transmute-ptr-to-ptr` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#transmute_ptr_to_ptr
```

**Comment by Manishearth** [comment]
Yes, this an explicit choice

**Review by Manishearth — APPROVED** [review]

**Review by sffc — APPROVED** [review]

**Pull request merged**
