### PR TITLE
Using a git submodule for Diplomat

### PR DESCRIPTION
**Pull request by robertbastian**
This makes it easier to iterate on ICU4X and Diplomat in parallel. ~It also simplifies CI as it can use the local diplomat-tool instead of having to `cargo install` it.~

### CODE REVIEW

**Comment by sffc** [comment]
Not opposed but we should discuss this because adding a git submodule increases the complexity for _everyone_ hacking on ICU4X even if they don't interact with Diplomat/FFI.

**Comment by robertbastian** [comment]
Yes we should discuss.

**Comment by robertbastian** [comment]
I've achieved most of what I wanted to achieve here with https://github.com/rust-diplomat/diplomat/pull/348 and #4197

**Review by Manishearth — APPROVED** [review]

**Comment by sffc** [comment]
Discussion:

- @sffc - The number of people this helps is smallish, and the number of people it annoys is large. If you need fast iteration on diplomat locally, you can patch it locally to use path dependencies.
- @robertbastian - The changes I made in upstream about dependencies make the git submodule mostly obsolete, because you can now patch it locally.

Conclusion: Not worth the submodule.

LGTM: @robertbastian @Manishearth @sffc

**Pull request closed without merging**
