### PR TITLE
Removing big postcard test files

### PR DESCRIPTION
**Pull request by robertbastian**
`litemap` and `zerovec` have multiple MBs of test files.

### CODE REVIEW

**Comment by robertbastian** [comment]
I'm removing the large ZeroHashMap benches, because it currently seems computationally infeasible to generate such a ZHM.

**Review by Manishearth — DISMISSED** [review]

**Review by sffc — COMMENTED** [review]
What problem does this solve?

I'm not super concerned about 3MB files that don't change often. That won't cause repo bloat. I think it's good that we got rid of the big testdata postcard file primarily because it changes often.

**Review by sffc — CHANGES_REQUESTED** [review]
Instead of removing the large zerohashmap benches can we please replace them with something we can compute? I'm not a fan of deleting useful benches, and I consider this a useful benchmark. Wearing my TL hat, it's hard to get people to write benches, and I don't like reducing our benchmark coverage.

**Comment by Manishearth** [comment]
> What problem does this solve?

In general I would prefer to not check in files we can generate equally well on the fly.

Having a test for a medium size ZHM seems good though.

**Comment by robertbastian** [comment]
I'll have to find a size where generation works. I don't think there's any point in benching lookup times for ZHMs that we cannot realistically generate.

**Review by sffc — DISMISSED** [review]

**Review by sffc — APPROVED** [review]

**Pull request merged**
