### PR TITLE
Enable test-all-features

### PR DESCRIPTION
**Pull request by sffc**
I previously advocated for build-all-features by itself, but test-all-features also covers docs tests, which it would be nice to verify as well.

### CODE REVIEW

**Comment by zbraniecki** [comment]
Do we need both build *and* test?

**Review by srl295 — DISMISSED** [review]

**Comment by sffc** [comment]
> Do we need both build _and_ test?

My answer:

> I previously advocated for build-all-features by itself, but test-all-features also covers docs tests, which it would be nice to verify as well.

**Comment by zbraniecki** [comment]
Sorry, should have been more clear - can we skip `build` and only do `test` (which also builds)?

**Review by zbraniecki — DISMISSED** [review]

**Review by zbraniecki — APPROVED** [review]

**Comment by sffc** [comment]
When the build-all-features and test-all-features tasks were separate, I got runtime of: 3m 51s for the initial build, 3m 51s for the permutation build, and 5m 47s for the permutation test.  With all three steps combined, I get a runtime of 9m 10s, which is faster overall.  So I think we should keep the steps combined.

**Pull request merged**
