### PR TITLE
Experimental features for `icu_datagen`

### PR DESCRIPTION
**Pull request by robertbastian**
Part of #3165

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
relatively straightforward after all the other refactorings, nice

**Comment by robertbastian** [comment]
whoops features times out

**Review by Manishearth — DISMISSED** [review]

**Comment by robertbastian** [comment]
Numbers for main

crate | user | system | elapsed
-- | -- | -- | --
icu_datagen | 475.66 | 35.06 | 7:27.80
icu_datetime | 186.93 | 10.67 | 3:10.03
icu_capi | 140.56 | 22.03 | 2:28.25
icu_segmenter | 60.01 | 9.53 | 1:09.58
icu_provider | 56.43 | 14.04 | 1:02.41
zerovec | 58.65 | 7.25 | 1:02.17
icu_properties | 34.17 | 3.63 | 0:37.79
icu_locid_transform | 49.87 | 7.84 | 0:35.47
icu_relativetime | 29.36 | 1.89 | 0:31.26
icu_calendar | 20.93 | 2.79 | 0:23.19
icu_plurals | 17.2 | 3.25 | 0:20.46
icu_codepointtrie_builder | 62.01 | 12.05 | 0:17.10
icu_locid | 17.03 | 2.4 | 0:16.68
icu_provider_adapters | 14.07 | 2.36 | 0:16.40
icu_harfbuzz | 32.62 | 3.14 | 0:16.28
icu_list | 13.26 | 2.11 | 0:15.28
icu_decimal | 11.86 | 2.29 | 0:13.43
icu_collator | 11.43 | 1.92 | 0:13.35
icu_normalizer | 11.15 | 2.23 | 0:13.31
icu4x_ecma402 | 16.82 | 1.2 | 0:13.22
tinystr | 12.17 | 2.84 | 0:13.15
icu_casemap | 11.21 | 1.82 | 0:10.94
icu_testdata_scripts | 23.48 | 3.95 | 0:10.91
icu_displaynames | 9.08 | 1.2 | 0:10.28
icu_timezone | 6.77 | 1.27 | 0:08.04
icu_collections | 6.66 | 0.84 | 0:07.49
icu_compactdecimal | 6.47 | 1.34 | 0:07.33
yoke | 6.07 | 1.51 | 0:06.91
icu_ffi_coverage | 11.11 | 1.06 | 0:06.36
icu_benchmark_memory | 9.35 | 1 | 0:04.68
icu_provider_blob | 4.33 | 0.77 | 0:04.66
databake | 5.64 | 0.96 | 0:04.50
icu_benchmark_macros | 10.29 | 2.29 | 0:04.16
icu_provider_fs | 4.05 | 0.71 | 0:04.10
litemap | 3.1 | 0.9 | 0:04.00
tzif | 3.36 | 0.21 | 0:03.58
zerofrom | 4.87 | 0.93 | 0:03.56
icu_personnames | 3.31 | 0.7 | 0:03.52
bies | 5.24 | 1.06 | 0:03.06
icu_benchmark_binsize | 3.97 | 0.84 | 0:02.82
databake-derive | 2.49 | 0.58 | 0:02.57
zerovec-derive | 1.65 | 0.21 | 0:01.87
icu_datetime_data | 1.56 | 0.3 | 0:01.84
icu_freertos | 1.34 | 0.55 | 0:01.57
icu_provider_macros | 1.41 | 0.15 | 0:01.56
fixed_decimal | 1.18 | 0.33 | 0:01.52
icu_relativetime_data | 0.68 | 0.19 | 0:00.85
icu_unicodeset_parser | 0.62 | 0.22 | 0:00.85
icu_segmenter_data | 0.54 | 0.2 | 0:00.72
icu_displaynames_data | 0.5 | 0.21 | 0:00.69
icu_list_data | 0.44 | 0.23 | 0:00.65
icu_properties_data | 0.44 | 0.2 | 0:00.63
icu_compactdecimal_data | 0.43 | 0.21 | 0:00.62
icu_collator_data | 0.41 | 0.22 | 0:00.61
icu_decimal_data | 0.42 | 0.21 | 0:00.61
icu_plurals_data | 0.41 | 0.22 | 0:00.61
icu_timezone_data | 0.42 | 0.19 | 0:00.60
icu_calendar_data | 0.43 | 0.19 | 0:00.59
icu_locid_transform_data | 0.44 | 0.16 | 0:00.58
icu_casemap_data | 0.38 | 0.23 | 0:00.58
icu_normalizer_data | 0.43 | 0.16 | 0:00.58
yoke-derive | 0.42 | 0.12 | 0:00.54
icu_pattern | 0.41 | 0.11 | 0:00.53
writeable | 0.33 | 0.15 | 0:00.49
icu_depcheck | 0.39 | 0.1 | 0:00.49
zerofrom-derive | 0.34 | 0.13 | 0:00.48
deduplicating_array | 0.36 | 0.11 | 0:00.48
crlify | 0.35 | 0.08 | 0:00.48
ixdtf | 0.34 | 0.12 | 0:00.46

**Comment by robertbastian** [comment]
Seems to be the size of the target directory, which I don't know how to limit. I already tried making more space on the runners in [5b4876a](https://github.com/unicode-org/icu4x/pull/3665/commits/5b4876a7a1d4312f22b1f87086de16c9f96be9df), but that didn't help.

**Comment by Manishearth** [comment]
One way to solve this is to provide cargo-all-features with a chunking argument `--chunked 4 --chunk 1`, and then run the separate chunks on separate runners; or on the same runner with a target dir cleanup in between.



The way CAF works is that it currently iterates per-package and then iterates over features within each package. We could do one of the following to implement this: either we chunk at the package level, or we expand the package/feature set and chunk that instead. I think the former ought to be _fine_, there may be a long tail effect but it seems nicer to keep packages together. A third way is to preexpand the package/feature set but then chunk by package, using the feature set size as a weight.

I've filed an issue upstream about this and there's some discussion already https://github.com/frewsxcv/cargo-all-features/issues/28

**Comment by Manishearth** [comment]
Alternatively, supporting [this mode](https://github.com/frewsxcv/cargo-all-features/issues/28#issuecomment-1092216464) may help, but getting the nuances of what build command to run will be tricky.

**Comment by robertbastian** [comment]
We could merge this now without coverage for disabling these features. Thoughts?

**Comment by Manishearth** [comment]
Works fine for me if we have a followup to fix this.

**Comment by Manishearth** [comment]
I think we should also just set max_combination_size on all the component crates

**Review by Manishearth — APPROVED** [review]

**Review by sffc — COMMENTED** [review]
Nit: I would like to have a feature that enables all components so that we don't need to maintain this list of feature flags all over the place

**Pull request merged**
